import { NextResponse } from "next/server";
import { createServerClient } from "@aihkya/db";
import { cookies } from "next/headers";

export async function GET(request: Request) {
  const { searchParams } = new URL(request.url);
  const q = searchParams.get("q");
  const limit = parseInt(searchParams.get("limit") || "10", 10);

  const cookieStore = await cookies();
  const supabase = createServerClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,
    cookieStore,
  );

  if (!q) {
    return NextResponse.json({ tools: [], message: "No query provided" });
  }

  // Use PostgREST Full Text Search utilizing the `search_vector` generated by the database trigger
  // For fuzzy search, we trigger `.textSearch` against the `search_vector`
  const { data: tools, error } = await supabase
    .from("ai_tools")
    .select("*")
    .eq("status", "approved")
    .textSearch("search_vector", q, {
      type: "websearch",
      config: "english",
    })
    .order("rating_avg", { ascending: false })
    .limit(limit);

  if (error) {
    console.error("Search Error:", error);
    return NextResponse.json({ error: error.message }, { status: 500 });
  }

  // Log the search asynchronously for Analytics (Fire and Forget)
  (supabase.from("search_logs") as any)
    .insert({
      query: q,
      results_count: tools?.length || 0,
      filters_used: { search_type: "api_route" },
    })
    .then(({ error: logError }: any) => {
      if (logError) console.error("Failed to log search:", logError);
    });

  return NextResponse.json({ tools });
}
