-- ============================================================
-- AIHKYA: Tool Content Fields
-- Adds features, pros, cons, use_cases, alternatives,
-- hindi_summary, screenshot_url to ai_tools
-- Migration 0010
-- ============================================================

ALTER TABLE public.ai_tools
  ADD COLUMN IF NOT EXISTS features      JSONB DEFAULT '{"en":[],"hi":[],"hinglish":[]}',
  ADD COLUMN IF NOT EXISTS pros          JSONB DEFAULT '{"en":[],"hi":[],"hinglish":[]}',
  ADD COLUMN IF NOT EXISTS cons          JSONB DEFAULT '{"en":[],"hi":[],"hinglish":[]}',
  ADD COLUMN IF NOT EXISTS use_cases     JSONB DEFAULT '{"en":[],"hi":[],"hinglish":[]}',
  ADD COLUMN IF NOT EXISTS alternatives  TEXT[]  DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS hindi_summary TEXT,
  ADD COLUMN IF NOT EXISTS screenshot_url VARCHAR(500);


-- ── ChatGPT ──────────────────────────────────────────────────────────────────
UPDATE public.ai_tools SET
  features = '{"en":["Multi-turn conversations with memory","Code writing, review and debugging","Image analysis and generation (GPT-4o)","Voice conversation mode","Math, logic and data analysis","PDF and document reading","40+ language support including Hindi"],"hi":["मेमोरी के साथ बहु-बारी बातचीत","कोड लिखना, समीक्षा और डीबगिंग","इमेज विश्लेषण और निर्माण (GPT-4o)","वॉइस बातचीत मोड","गणित, तर्क और डेटा विश्लेषण","PDF और दस्तावेज़ पढ़ना","हिंदी सहित 40+ भाषाओं का समर्थन"],"hinglish":["Memory ke saath multi-turn conversations","Code likhna, review aur debugging","Image analysis aur generation (GPT-4o)","Voice conversation mode","Math, logic aur data analysis","PDF aur document reading","Hindi sametan 40+ languages ka support"]}',
  pros = '{"en":["Handles almost any task — most versatile AI available","Best-in-class conversational understanding","Strong coding and debugging assistant","Generous free tier with GPT-4o access","Massive plugin and integration ecosystem"],"hi":["लगभग कोई भी काम — सबसे बहुमुखी AI","बेहतरीन बातचीत की समझ","मजबूत कोडिंग असिस्टेंट","उदार मुफ्त टियर GPT-4o के साथ","विशाल प्लगइन और इंटीग्रेशन इकोसिस्टम"],"hinglish":["Almost koi bhi kaam — sabse versatile AI","Best-in-class conversational understanding","Strong coding aur debugging assistant","Generous free tier GPT-4o ke saath","Massive plugin aur integration ecosystem"]}',
  cons = '{"en":["Free tier has daily usage limits","Can state wrong facts confidently (hallucination)","No real-time web access on free plan","Hindi output quality can be inconsistent"],"hi":["मुफ्त टियर में दैनिक उपयोग की सीमा","कभी-कभी गलत जानकारी आत्मविश्वास से देता है","मुफ्त प्लान में रियल-टाइम वेब नहीं","हिंदी आउटपुट कभी-कभी असंगत हो सकता है"],"hinglish":["Free tier mein daily usage limits","Kabhi kabhi galat facts confidently bolta hai","Free plan pe real-time web access nahi","Hindi output kabhi kabhi inconsistent ho sakta hai"]}',
  use_cases = '{"en":["Writing blogs, emails and social media content","Coding help and debugging for developers","Business planning, analysis and reports","Answering complex academic or research questions","Customer support script and template creation","Quick learning of new subjects or skills"],"hi":["ब्लॉग, ईमेल और सोशल मीडिया कंटेंट लिखना","डेवलपर्स के लिए कोडिंग और डीबगिंग","बिज़नेस प्लानिंग, विश्लेषण और रिपोर्ट","जटिल अकादमिक या शोध सवालों के जवाब","कस्टमर सपोर्ट स्क्रिप्ट और टेम्पलेट","नए विषय या कौशल तेज़ी से सीखना"],"hinglish":["Blog, email aur social media content likhna","Developers ke liye coding aur debugging","Business planning, analysis aur reports","Complex academic ya research sawaalon ke jawaab","Customer support scripts aur templates banana","Naye subjects ya skills seekhna"]}',
  alternatives = ARRAY['claude','gemini','perplexity-ai','microsoft-copilot','meta-ai'],
  hindi_summary = 'ChatGPT भारत में सबसे ज़्यादा इस्तेमाल होने वाला AI टूल है। यह हिंदी में कंटेंट लिखने, सवाल-जवाब करने, कोडिंग और बिज़नेस प्लानिंग — सभी कामों में उपयोगी है। मुफ्त वर्शन में भी GPT-4o का उपयोग होता है और ज़्यादातर काम हो जाता है।'
WHERE slug = 'chatgpt';


-- ── Claude ───────────────────────────────────────────────────────────────────
UPDATE public.ai_tools SET
  features = '{"en":["200K token context window (longest available)","Superior document analysis and summarization","Nuanced creative writing and editing","Strong coding across 20+ languages","Thoughtful and safe AI responses","File uploads: PDF, Word, code files","Multilingual support including Hindi"],"hi":["200K टोकन कॉन्टेक्स्ट विंडो (सबसे लंबा)","बेहतरीन दस्तावेज़ विश्लेषण और सारांश","सूक्ष्म क्रिएटिव लेखन और संपादन","20+ भाषाओं में मजबूत कोडिंग","विचारशील और सुरक्षित AI जवाब","PDF, Word, कोड फाइलें अपलोड करें","हिंदी सहित बहुभाषी समर्थन"],"hinglish":["200K token context window (sabse lamba)","Superior document analysis aur summarization","Nuanced creative writing aur editing","20+ languages mein strong coding","Thoughtful aur safe AI responses","PDF, Word, code files upload karo","Hindi sametan multilingual support"]}',
  pros = '{"en":["Best for long document analysis (books, contracts, reports)","More thoughtful and nuanced than competitors","Excellent coding assistant with explanations","Honest about its limitations","Strong privacy commitment from Anthropic"],"hi":["लंबे दस्तावेज़ विश्लेषण के लिए सबसे अच्छा","प्रतिस्पर्धियों से अधिक विचारशील और सूक्ष्म","बेहतरीन कोडिंग असिस्टेंट","अपनी सीमाओं के बारे में ईमानदार","Anthropic की मजबूत गोपनीयता प्रतिबद्धता"],"hinglish":["Long documents ke liye best (books, contracts, reports)","Competitors se zyada thoughtful aur nuanced","Excellent coding assistant with explanations","Apni limitations ke baare mein honest","Anthropic ki strong privacy commitment"]}',
  cons = '{"en":["No image generation capability","Slower response speed on free tier","Limited integrations compared to ChatGPT","Less popular in India — fewer Hindi tutorials"],"hi":["इमेज बनाने की क्षमता नहीं","मुफ्त टियर पर धीमी प्रतिक्रिया गति","ChatGPT की तुलना में कम इंटीग्रेशन","भारत में कम लोकप्रिय — कम हिंदी ट्यूटोरियल"],"hinglish":["Image generation capability nahi hai","Free tier pe slow response speed","ChatGPT ke comparison mein kam integrations","India mein kam popular — kam Hindi tutorials"]}',
  use_cases = '{"en":["Analyzing lengthy legal contracts or financial reports","Academic research paper reading and summarization","Long-form content writing (books, manuals)","Complex coding projects and architecture review","Business document drafting with high accuracy","Deep research on any topic"],"hi":["लंबे कानूनी अनुबंध या वित्तीय रिपोर्ट का विश्लेषण","अकादमिक शोध पत्र पढ़ना और सारांश बनाना","लंबे-फॉर्म कंटेंट लेखन (पुस्तकें, मैनुअल)","जटिल कोडिंग प्रोजेक्ट और आर्किटेक्चर समीक्षा","उच्च सटीकता के साथ व्यापार दस्तावेज़","किसी भी विषय पर गहन शोध"],"hinglish":["Lambe legal contracts ya financial reports ka analysis","Academic research papers padhna aur summarize karna","Long-form content likhna (books, manuals)","Complex coding projects aur architecture review","High accuracy ke saath business documents banana","Kisi bhi topic pe deep research"]}',
  alternatives = ARRAY['chatgpt','gemini','perplexity-ai','microsoft-copilot'],
  hindi_summary = 'Claude लंबे दस्तावेज़ पढ़ने और विश्लेषण करने में सबसे अच्छा AI है। अगर आपके पास बड़ी PDF, कानूनी दस्तावेज़, या रिसर्च पेपर हैं, तो Claude उन्हें आसानी से समझ सकता है। यह ChatGPT से ज़्यादा सावधान और विश्वसनीय जवाब देता है।'
WHERE slug = 'claude';


-- ── Gemini ───────────────────────────────────────────────────────────────────
UPDATE public.ai_tools SET
  features = '{"en":["Native Google Search integration for real-time info","Multimodal: text, images, audio, video and code","Deep integration with Google Workspace (Docs, Sheets)","Gemini Advanced (1.5 Pro) for complex reasoning","1 million token context window in Advanced","Strong Hindi and Indian language support","Free tier available via Google account"],"hi":["रियल-टाइम जानकारी के लिए Google Search इंटीग्रेशन","मल्टीमोडल: टेक्स्ट, इमेज, ऑडियो, वीडियो और कोड","Google Workspace के साथ गहरा इंटीग्रेशन","जटिल रीज़निंग के लिए Gemini Advanced","Advanced में 10 लाख टोकन कॉन्टेक्स्ट","मजबूत हिंदी और भारतीय भाषा समर्थन","Google अकाउंट से मुफ्त टियर"],"hinglish":["Real-time info ke liye Google Search integration","Multimodal: text, image, audio, video aur code","Google Workspace ke saath deep integration","Complex reasoning ke liye Gemini Advanced","Advanced mein 1 million token context","Strong Hindi aur Indian language support","Google account se free tier available"]}',
  pros = '{"en":["Real-time web access included for free","Best Google ecosystem integration","Strong Hindi understanding","Free tier is very capable","Excellent for research with live data"],"hi":["मुफ्त में रियल-टाइम वेब एक्सेस","सबसे अच्छा Google इकोसिस्टम इंटीग्रेशन","मजबूत हिंदी समझ","मुफ्त टियर बहुत सक्षम","लाइव डेटा के साथ रिसर्च के लिए बेहतरीन"],"hinglish":["Free mein real-time web access","Best Google ecosystem integration","Strong Hindi understanding","Free tier bahut capable hai","Live data ke saath research ke liye excellent"]}',
  cons = '{"en":["Creative writing less natural than ChatGPT/Claude","Advanced features need Google One subscription","Privacy concerns for enterprise users","Inconsistent response quality sometimes"],"hi":["क्रिएटिव लेखन ChatGPT/Claude से कम स्वाभाविक","Advanced फीचर्स के लिए Google One सब्सक्रिप्शन","एंटरप्राइज़ यूज़र्स के लिए गोपनीयता चिंताएं","कभी-कभी असंगत जवाब की गुणवत्ता"],"hinglish":["Creative writing ChatGPT/Claude se kam natural","Advanced features ke liye Google One subscription","Enterprise users ke liye privacy concerns","Kabhi kabhi inconsistent response quality"]}',
  use_cases = '{"en":["Current events research with live sources","Google Docs and Sheets automation","Searching and summarizing recent news in Hindi","Travel and local business information lookup","Student homework help with verified sources","YouTube video summarization"],"hi":["लाइव स्रोतों के साथ वर्तमान घटनाओं की रिसर्च","Google Docs और Sheets ऑटोमेशन","हिंदी में हालिया समाचार खोज और सारांश","यात्रा और स्थानीय व्यापार जानकारी खोज","सत्यापित स्रोतों के साथ छात्र गृहकार्य","YouTube वीडियो सारांश"],"hinglish":["Live sources ke saath current events research","Google Docs aur Sheets automation","Hindi mein recent news search aur summary","Travel aur local business info lookup","Verified sources ke saath student homework help","YouTube video summarization"]}',
  alternatives = ARRAY['chatgpt','claude','perplexity-ai','microsoft-copilot','meta-ai'],
  hindi_summary = 'Gemini Google का AI है जो रियल-टाइम इंटरनेट से जुड़ा है — इसलिए यह आज की खबरें और ताज़ा जानकारी दे सकता है। Google Docs और YouTube के साथ इसका इंटीग्रेशन बहुत उपयोगी है। हिंदी भाषा की समझ भी अच्छी है।'
WHERE slug = 'gemini';


-- ── Perplexity AI ─────────────────────────────────────────────────────────────
UPDATE public.ai_tools SET
  features = '{"en":["Real-time web search with cited sources","AI answer engine — not just links but explanations","Follow-up question support in same thread","Perplexity Pro with GPT-4 and Claude","Focus modes: Academic, YouTube, Reddit, News","PDF and file upload analysis","Mobile app for iOS and Android"],"hi":["उद्धृत स्रोतों के साथ रियल-टाइम वेब सर्च","AI उत्तर इंजन — सिर्फ लिंक नहीं बल्कि स्पष्टीकरण","एक ही थ्रेड में फॉलो-अप सवाल","GPT-4 और Claude के साथ Perplexity Pro","फोकस मोड: Academic, YouTube, Reddit, News","PDF और फाइल अपलोड विश्लेषण","iOS और Android मोबाइल ऐप"],"hinglish":["Cited sources ke saath real-time web search","AI answer engine — sirf links nahi balki explanations","Same thread mein follow-up questions","GPT-4 aur Claude ke saath Perplexity Pro","Focus modes: Academic, YouTube, Reddit, News","PDF aur file upload analysis","iOS aur Android mobile app"]}',
  pros = '{"en":["Every answer cites real sources you can verify","Best AI for research and fact-checking","No hallucination risk — grounded in real web results","Excellent for current events and news","Free tier is generous with web search"],"hi":["हर जवाब असली स्रोत उद्धृत करता है जिसे आप सत्यापित कर सकते हैं","रिसर्च और फैक्ट-चेकिंग के लिए सबसे अच्छा AI","हेल्यूसिनेशन का कम जोखिम — असली वेब परिणामों पर आधारित","वर्तमान घटनाओं और समाचार के लिए बेहतरीन","मुफ्त टियर में वेब सर्च उदार है"],"hinglish":["Har jawab real sources cite karta hai jo verify kar sako","Research aur fact-checking ke liye best AI","Hallucination ka kam risk — real web results pe grounded","Current events aur news ke liye excellent","Free tier mein generous web search"]}',
  cons = '{"en":["Not ideal for creative writing or long-form content","Hindi interface and results less refined","Limited conversation memory compared to ChatGPT","Pro plan needed for unlimited searches"],"hi":["क्रिएटिव लेखन या लंबे-फॉर्म कंटेंट के लिए आदर्श नहीं","हिंदी इंटरफेस और परिणाम कम परिष्कृत","ChatGPT की तुलना में सीमित बातचीत मेमोरी","असीमित खोज के लिए Pro प्लान चाहिए"],"hinglish":["Creative writing ya long-form content ke liye ideal nahi","Hindi interface aur results kam refined","ChatGPT ke comparison mein limited conversation memory","Unlimited searches ke liye Pro plan chahiye"]}',
  use_cases = '{"en":["Fact-checking news articles and claims","Research for academic assignments with sources","Competitor analysis with live data","Finding latest government schemes and policies","Medical or legal information with citations","Stock and financial news lookup"],"hi":["समाचार लेखों और दावों की तथ्य-जांच","स्रोतों के साथ अकादमिक कार्यों की रिसर्च","लाइव डेटा के साथ प्रतिस्पर्धी विश्लेषण","नवीनतम सरकारी योजनाएं और नीतियां खोजना","उद्धरणों के साथ चिकित्सा या कानूनी जानकारी","शेयर और वित्तीय समाचार खोज"],"hinglish":["News articles aur claims ki fact-checking","Sources ke saath academic assignments ki research","Live data ke saath competitor analysis","Latest government schemes aur policies dhundhna","Citations ke saath medical ya legal info","Stock aur financial news lookup"]}',
  alternatives = ARRAY['chatgpt','gemini','you-com','microsoft-copilot'],
  hindi_summary = 'Perplexity AI एक AI सर्च इंजन है जो हर जवाब के साथ असली वेबसाइटों के लिंक और स्रोत देता है। किसी भी सरकारी योजना, खबर, या जानकारी को सत्यापित करने के लिए यह सबसे भरोसेमंद टूल है। फैक्ट-चेकिंग के लिए भारत में बहुत उपयोगी।'
WHERE slug = 'perplexity-ai';


-- ── Midjourney ───────────────────────────────────────────────────────────────
UPDATE public.ai_tools SET
  features = '{"en":["Photorealistic and artistic image generation","V6 model with stunning quality and detail","Stylized art, illustrations and concept art","Text rendering in images (V6+)","Variation and upscaling controls","Community gallery for inspiration","Discord-based interface with web app option"],"hi":["फोटोरिअलिस्टिक और कलात्मक इमेज जनरेशन","V6 मॉडल बेहतरीन गुणवत्ता और विवरण के साथ","शैलीगत कला, चित्र और कॉन्सेप्ट आर्ट","इमेज में टेक्स्ट रेंडरिंग (V6+)","वेरिएशन और अपस्केलिंग कंट्रोल","प्रेरणा के लिए कम्युनिटी गैलरी","Discord-आधारित इंटरफेस वेब ऐप विकल्प के साथ"],"hinglish":["Photorealistic aur artistic image generation","V6 model stunning quality aur detail ke saath","Stylized art, illustrations aur concept art","Images mein text rendering (V6+)","Variation aur upscaling controls","Inspiration ke liye community gallery","Discord-based interface web app option ke saath"]}',
  pros = '{"en":["Unmatched image quality for artistic and creative work","Huge community of artists for prompt inspiration","Consistent style across variations","Excellent for marketing visuals, posters, thumbnails","Fastest image generation among premium tools"],"hi":["कलात्मक और क्रिएटिव काम के लिए अद्वितीय इमेज गुणवत्ता","प्रॉम्प्ट प्रेरणा के लिए कलाकारों का विशाल समुदाय","वेरिएशन में सुसंगत शैली","मार्केटिंग विजुअल, पोस्टर, थंबनेल के लिए बेहतरीन","प्रीमियम टूल्स में सबसे तेज़ इमेज जनरेशन"],"hinglish":["Artistic aur creative kaam ke liye unmatched image quality","Prompt inspiration ke liye artists ki huge community","Variations mein consistent style","Marketing visuals, posters, thumbnails ke liye excellent","Premium tools mein fastest image generation"]}',
  cons = '{"en":["Requires paid subscription — no free tier","Works via Discord (less intuitive for beginners)","Cannot generate images of real people accurately","Slow to add new features compared to competitors"],"hi":["भुगतान सब्सक्रिप्शन आवश्यक — मुफ्त टियर नहीं","Discord के माध्यम से काम करता है (शुरुआती लोगों के लिए कम सहज)","असली लोगों की इमेज सटीक रूप से नहीं बना सकता","प्रतिस्पर्धियों की तुलना में नए फीचर्स धीमे"],"hinglish":["Paid subscription chahiye — free tier nahi","Discord ke through kaam karta hai (beginners ke liye less intuitive)","Real logon ki images accurately nahi bana sakta","Competitors ke comparison mein new features slow aate hain"]}',
  use_cases = '{"en":["Creating YouTube video thumbnails","Social media post illustrations and banners","Product mockups and marketing creatives","Book cover and poster design","Concept art for games and animation","Wedding and event invitation designs"],"hi":["YouTube वीडियो थंबनेल बनाना","सोशल मीडिया पोस्ट चित्र और बैनर","प्रोडक्ट मॉकअप और मार्केटिंग क्रिएटिव","बुक कवर और पोस्टर डिज़ाइन","गेम्स और एनिमेशन के लिए कॉन्सेप्ट आर्ट","शादी और इवेंट इनविटेशन डिज़ाइन"],"hinglish":["YouTube video thumbnails banana","Social media post illustrations aur banners","Product mockups aur marketing creatives","Book cover aur poster design","Games aur animation ke liye concept art","Shaadi aur event invitation designs"]}',
  alternatives = ARRAY['dall-e-3','adobe-firefly','leonardo-ai','ideogram','stable-diffusion'],
  hindi_summary = 'Midjourney दुनिया का सबसे अच्छा AI इमेज जनरेटर है। YouTube थंबनेल, पोस्टर, सोशल मीडिया ग्राफिक्स — सभी के लिए शानदार। भारतीय फ्रीलांसर और डिजिटल मार्केटर्स के लिए यह एक बेहतरीन टूल है, लेकिन इसके लिए भुगतान करना पड़ता है।'
WHERE slug = 'midjourney';


-- ── Canva AI Magic Studio ─────────────────────────────────────────────────────
UPDATE public.ai_tools SET
  features = '{"en":["Drag-and-drop design editor with 100M+ templates","Magic Write — AI text generation inside Canva","Magic Design — auto-generate designs from a prompt","Background remover and image enhancer","Text-to-image AI generation","Brand Kit for consistent visual identity","Presentations, videos, social posts in one tool","Hindi interface available"],"hi":["100M+ टेम्पलेट के साथ ड्रैग-एंड-ड्रॉप डिज़ाइन एडिटर","Magic Write — Canva में AI टेक्स्ट जनरेशन","Magic Design — प्रॉम्प्ट से ऑटो-जेनरेट डिज़ाइन","बैकग्राउंड रिमूवर और इमेज एन्हांसर","टेक्स्ट-टू-इमेज AI जनरेशन","सुसंगत विजुअल पहचान के लिए Brand Kit","एक टूल में प्रेजेंटेशन, वीडियो, सोशल पोस्ट","हिंदी इंटरफेस उपलब्ध"],"hinglish":["100M+ templates ke saath drag-and-drop design editor","Magic Write — Canva ke andar AI text generation","Magic Design — prompt se auto-generate designs","Background remover aur image enhancer","Text-to-image AI generation","Consistent visual identity ke liye Brand Kit","Ek tool mein presentations, videos, social posts","Hindi interface available"]}',
  pros = '{"en":["Easiest design tool — no design skills needed","Huge free template library for every use case","UPI payment accepted — affordable for Indians","Hindi UI makes it accessible nationwide","Best tool for non-designers to look professional"],"hi":["सबसे आसान डिज़ाइन टूल — कोई डिज़ाइन कौशल ज़रूरी नहीं","हर उपयोग के लिए विशाल मुफ्त टेम्पलेट लाइब्रेरी","UPI भुगतान स्वीकृत — भारतीयों के लिए किफायती","हिंदी UI देशभर में सुलभ बनाता है","नॉन-डिज़ाइनर्स के लिए प्रोफेशनल दिखने का सबसे अच्छा टूल"],"hinglish":["Sabse easy design tool — koi design skills nahi chahiye","Har use case ke liye huge free template library","UPI payment accepted — Indians ke liye affordable","Hindi UI nationwide accessible banata hai","Non-designers ke liye professional dikhne ka best tool"]}',
  cons = '{"en":["AI features require Canva Pro (paid)","Limited customization compared to professional tools","Cannot replace Photoshop for complex editing","Export quality limits on free tier"],"hi":["AI फीचर्स के लिए Canva Pro चाहिए (भुगतान)","प्रोफेशनल टूल्स की तुलना में सीमित कस्टमाइज़ेशन","जटिल एडिटिंग के लिए Photoshop की जगह नहीं ले सकता","मुफ्त टियर पर एक्सपोर्ट गुणवत्ता सीमित"],"hinglish":["AI features ke liye Canva Pro chahiye (paid)","Professional tools ke comparison mein limited customization","Complex editing ke liye Photoshop replace nahi kar sakta","Free tier pe export quality limited"]}',
  use_cases = '{"en":["Social media posts for Instagram and Facebook","Business presentations and pitch decks","WhatsApp marketing materials and flyers","Diwali, Holi and festival greeting cards","YouTube channel art and thumbnails","Shop and business menu design","Wedding card and event invitation creation"],"hi":["Instagram और Facebook के लिए सोशल मीडिया पोस्ट","बिज़नेस प्रेजेंटेशन और पिच डेक","WhatsApp मार्केटिंग सामग्री और फ्लायर","दिवाली, होली और त्योहार ग्रीटिंग कार्ड","YouTube चैनल आर्ट और थंबनेल","दुकान और बिज़नेस मेनू डिज़ाइन","शादी कार्ड और इवेंट इनविटेशन"],"hinglish":["Instagram aur Facebook ke liye social media posts","Business presentations aur pitch decks","WhatsApp marketing materials aur flyers","Diwali, Holi aur festival greeting cards","YouTube channel art aur thumbnails","Dukaan aur business menu design","Shaadi card aur event invitations banana"]}',
  alternatives = ARRAY['adobe-firefly','midjourney','looka','figma-ai'],
  hindi_summary = 'Canva भारत में सबसे लोकप्रिय डिज़ाइन टूल है क्योंकि इसे इस्तेमाल करना बेहद आसान है। दुकान के पोस्टर, WhatsApp ग्राफिक्स, सोशल मीडिया पोस्ट — सब Canva में मिनटों में बन सकते हैं। UPI से भुगतान होता है और हिंदी में भी काम करता है।'
WHERE slug = 'canva-ai-magic-studio';


-- ── DALL-E 3 ─────────────────────────────────────────────────────────────────
UPDATE public.ai_tools SET
  features = '{"en":["Integrated directly in ChatGPT (no separate signup)","High coherence — follows text prompts accurately","Natural language instructions (no prompt engineering needed)","Safe and content-moderated generation","Multiple aspect ratios and styles","Editing and in-painting via ChatGPT","Available via API for developers"],"hi":["ChatGPT में सीधे इंटीग्रेटेड (अलग साइनअप नहीं)","उच्च सुसंगतता — टेक्स्ट प्रॉम्प्ट को सटीक रूप से फॉलो करता है","प्राकृतिक भाषा निर्देश (प्रॉम्प्ट इंजीनियरिंग ज़रूरी नहीं)","सुरक्षित और कंटेंट-मॉडरेटेड जनरेशन","एकाधिक आस्पेक्ट रेशियो और शैलियां","ChatGPT के माध्यम से एडिटिंग और इन-पेंटिंग","डेवलपर्स के लिए API उपलब्ध"],"hinglish":["ChatGPT mein directly integrated (alag signup nahi)","High coherence — text prompts accurately follow karta hai","Natural language instructions (prompt engineering nahi chahiye)","Safe aur content-moderated generation","Multiple aspect ratios aur styles","ChatGPT ke through editing aur in-painting","Developers ke liye API available"]}',
  pros = '{"en":["No separate tool — works right inside ChatGPT","Understands complex text descriptions accurately","Great for beginners — plain language prompts work","Safety filters prevent misuse","Best coherence for text-in-image generation"],"hi":["अलग टूल नहीं — ChatGPT के अंदर ही काम करता है","जटिल टेक्स्ट विवरण को सटीक समझता है","शुरुआती लोगों के लिए बेहतरीन — सरल भाषा काम करती है","दुरुपयोग रोकने के लिए सुरक्षा फ़िल्टर","टेक्स्ट-इन-इमेज जनरेशन के लिए सबसे अच्छी सुसंगतता"],"hinglish":["Alag tool nahi — ChatGPT ke andar hi kaam karta hai","Complex text descriptions accurately samjhta hai","Beginners ke liye great — plain language prompts kaam karte hain","Safety filters misuse rokti hain","Text-in-image generation ke liye best coherence"]}',
  cons = '{"en":["Requires ChatGPT Plus for DALL-E 3 (paid)","Artistic quality lower than Midjourney","Limited style control compared to Stable Diffusion","Rate limits even on paid plans"],"hi":["DALL-E 3 के लिए ChatGPT Plus चाहिए (भुगतान)","Midjourney की तुलना में कलात्मक गुणवत्ता कम","Stable Diffusion की तुलना में सीमित स्टाइल कंट्रोल","भुगतान प्लान पर भी रेट लिमिट"],"hinglish":["DALL-E 3 ke liye ChatGPT Plus chahiye (paid)","Midjourney ke comparison mein artistic quality kam","Stable Diffusion ke comparison mein limited style control","Paid plans pe bhi rate limits hain"]}',
  use_cases = '{"en":["Quick illustrations for blog posts and articles","Social media visuals without design skills","Product concept visualization","Educational diagrams and infographics","Greeting card and invite image generation","Generating images from a story or idea"],"hi":["ब्लॉग पोस्ट और लेखों के लिए त्वरित चित्र","डिज़ाइन कौशल के बिना सोशल मीडिया विजुअल","प्रोडक्ट कॉन्सेप्ट विज़ुअलाइज़ेशन","शैक्षिक आरेख और इन्फोग्राफिक्स","ग्रीटिंग कार्ड और इनविटेशन इमेज","किसी कहानी या विचार से इमेज"],"hinglish":["Blog posts aur articles ke liye quick illustrations","Design skills ke bina social media visuals","Product concept visualization","Educational diagrams aur infographics","Greeting card aur invite images","Kisi kahani ya idea se images banana"]}',
  alternatives = ARRAY['midjourney','adobe-firefly','leonardo-ai','ideogram','stable-diffusion'],
  hindi_summary = 'DALL-E 3 ChatGPT के अंदर ही मिलता है — अलग से डाउनलोड या साइनअप करने की ज़रूरत नहीं। बस ChatGPT में हिंदी में बताएं कि क्या इमेज चाहिए और यह बना देगा। शुरुआती लोगों के लिए सबसे आसान इमेज जनरेटर है।'
WHERE slug = 'dall-e-3';


-- ── Runway ML ────────────────────────────────────────────────────────────────
UPDATE public.ai_tools SET
  features = '{"en":["Gen-3 Alpha — state-of-the-art text-to-video","Image-to-video animation","Video inpainting and outpainting","Background removal from video","Motion brush for selective animation","AI color grading and video effects","Free credits for new users"],"hi":["Gen-3 Alpha — अत्याधुनिक टेक्स्ट-टू-वीडियो","इमेज-टू-वीडियो एनिमेशन","वीडियो इनपेंटिंग और आउटपेंटिंग","वीडियो से बैकग्राउंड हटाना","चयनात्मक एनिमेशन के लिए मोशन ब्रश","AI कलर ग्रेडिंग और वीडियो इफेक्ट्स","नए यूज़र्स के लिए मुफ्त क्रेडिट"],"hinglish":["Gen-3 Alpha — state-of-the-art text-to-video","Image-to-video animation","Video inpainting aur outpainting","Video se background hatana","Selective animation ke liye motion brush","AI color grading aur video effects","Naye users ke liye free credits"]}',
  pros = '{"en":["Best-in-class video generation quality","Wide range of video editing AI tools","Strong community and tutorial resources","Free tier for experimenting","Used by professional filmmakers and studios"],"hi":["सबसे अच्छी वीडियो जनरेशन गुणवत्ता","वीडियो एडिटिंग AI टूल्स की विस्तृत श्रृंखला","मजबूत समुदाय और ट्यूटोरियल संसाधन","प्रयोग के लिए मुफ्त टियर","प्रोफेशनल फिल्ममेकर और स्टूडियो उपयोग करते हैं"],"hinglish":["Best-in-class video generation quality","Video editing AI tools ki wide range","Strong community aur tutorial resources","Experimenting ke liye free tier","Professional filmmakers aur studios use karte hain"]}',
  cons = '{"en":["Expensive for heavy video generation use","Generated videos limited to ~10 seconds","Learning curve for advanced features","Paid credits deplete quickly on complex generations"],"hi":["भारी वीडियो जनरेशन के लिए महंगा","जेनरेटेड वीडियो ~10 सेकंड तक सीमित","उन्नत फीचर्स के लिए सीखने की ज़रूरत","जटिल जनरेशन पर भुगतान क्रेडिट तेज़ी से खत्म"],"hinglish":["Heavy video generation ke liye expensive","Generated videos ~10 seconds tak limited","Advanced features ke liye learning curve","Complex generations pe paid credits jaldi khatam"]}',
  use_cases = '{"en":["Creating short cinematic video clips from text","Animating still product images for ads","Background removal from recorded videos","Social media reels from existing images","Film and commercial production prototyping","YouTube intro and animation sequences"],"hi":["टेक्स्ट से छोटे सिनेमाई वीडियो क्लिप बनाना","विज्ञापनों के लिए स्थिर प्रोडक्ट इमेज को एनिमेट करना","रिकॉर्डेड वीडियो से बैकग्राउंड हटाना","मौजूदा इमेज से सोशल मीडिया रील","फिल्म और कमर्शियल प्रोडक्शन प्रोटोटाइपिंग","YouTube इंट्रो और एनिमेशन सीक्वेंस"],"hinglish":["Text se short cinematic video clips banana","Ads ke liye still product images animate karna","Recorded videos se background hatana","Existing images se social media reels","Film aur commercial production prototyping","YouTube intro aur animation sequences"]}',
  alternatives = ARRAY['pika','sora','luma-ai','kling-ai','invideo-ai'],
  hindi_summary = 'Runway ML दुनिया के सबसे उन्नत AI वीडियो जनरेशन टूल्स में से एक है। टेक्स्ट लिखो और छोटा वीडियो क्लिप बन जाएगा। भारत में YouTube क्रिएटर्स और डिजिटल मार्केटर्स के लिए यह एक उपयोगी टूल है, हालांकि ज़्यादा उपयोग के लिए भुगतान करना होगा।'
WHERE slug = 'runway-ml';


-- ── InVideo AI ───────────────────────────────────────────────────────────────
UPDATE public.ai_tools SET
  features = '{"en":["Text-to-video — paste script, get full video","AI voiceover in Hindi and 50+ languages","5000+ professional video templates","Auto-subtitles and caption generation","Stock footage and music library included","Social media optimized video formats","Made in India — strong Hindi support"],"hi":["टेक्स्ट-टू-वीडियो — स्क्रिप्ट डालें, पूरा वीडियो पाएं","हिंदी और 50+ भाषाओं में AI वॉइसओवर","5000+ प्रोफेशनल वीडियो टेम्पलेट","ऑटो-सब्टाइटल और कैप्शन जनरेशन","स्टॉक फुटेज और म्यूजिक लाइब्रेरी","सोशल मीडिया-ऑप्टिमाइज़्ड वीडियो फॉर्मेट","भारत में बनाया — मजबूत हिंदी समर्थन"],"hinglish":["Text-to-video — script daalo, poora video pao","Hindi aur 50+ languages mein AI voiceover","5000+ professional video templates","Auto-subtitles aur caption generation","Stock footage aur music library included","Social media optimized video formats","Made in India — strong Hindi support"]}',
  pros = '{"en":["Made in India — best Hindi voiceover quality","Easiest video creation tool for non-editors","Huge template library for all niches","UPI payment accepted","Free plan available with watermark","Excellent for YouTube and Instagram Reels"],"hi":["भारत में बना — सबसे अच्छी हिंदी वॉइसओवर गुणवत्ता","नॉन-एडिटर्स के लिए सबसे आसान वीडियो क्रिएशन टूल","सभी निचे के लिए विशाल टेम्पलेट लाइब्रेरी","UPI भुगतान स्वीकृत","वॉटरमार्क के साथ मुफ्त प्लान","YouTube और Instagram Reels के लिए बेहतरीन"],"hinglish":["India mein bana — best Hindi voiceover quality","Non-editors ke liye sabse easy video creation tool","Sab niches ke liye huge template library","UPI payment accepted","Watermark ke saath free plan available","YouTube aur Instagram Reels ke liye excellent"]}',
  cons = '{"en":["Free plan adds InVideo watermark","Advanced editing limited vs professional tools","AI-generated videos can look templated","Requires good internet — cloud-based"],"hi":["मुफ्त प्लान InVideo वॉटरमार्क जोड़ता है","प्रोफेशनल टूल्स की तुलना में उन्नत एडिटिंग सीमित","AI-जेनरेटेड वीडियो टेम्पलेटेड लग सकते हैं","अच्छे इंटरनेट की ज़रूरत — क्लाउड-आधारित"],"hinglish":["Free plan InVideo watermark lagata hai","Professional tools ke comparison mein advanced editing limited","AI-generated videos templated lag sakte hain","Achha internet chahiye — cloud-based hai"]}',
  use_cases = '{"en":["YouTube Shorts and long-form video content in Hindi","Instagram Reels for business marketing","News and educational explainer videos","Product promotion videos for small businesses","Online course and tutorial video creation","Social media ads for local businesses"],"hi":["हिंदी में YouTube Shorts और लंबे वीडियो","बिज़नेस मार्केटिंग के लिए Instagram Reels","समाचार और शैक्षिक एक्सप्लेनर वीडियो","छोटे व्यवसायों के लिए प्रोडक्ट प्रमोशन वीडियो","ऑनलाइन कोर्स और ट्यूटोरियल वीडियो","स्थानीय व्यवसायों के लिए सोशल मीडिया विज्ञापन"],"hinglish":["Hindi mein YouTube Shorts aur long-form videos","Business marketing ke liye Instagram Reels","News aur educational explainer videos","Chhote businesses ke liye product promotion videos","Online course aur tutorial video creation","Local businesses ke liye social media ads"]}',
  alternatives = ARRAY['runway-ml','pictory-ai','descript','synthesia','heygen'],
  hindi_summary = 'InVideo AI भारत की कंपनी है और हिंदी वॉइसओवर के साथ वीडियो बनाने के लिए सबसे अच्छा टूल है। बस अपनी स्क्रिप्ट डालें और मिनटों में पूरा YouTube या Instagram वीडियो तैयार हो जाएगा। UPI से भुगतान होता है।'
WHERE slug = 'invideo-ai';


-- ── GitHub Copilot ───────────────────────────────────────────────────────────
UPDATE public.ai_tools SET
  features = '{"en":["Real-time code suggestions in your editor","Copilot Chat — AI pair programmer in VS Code","Supports 15+ programming languages","PR summaries and code review assistance","CLI command suggestions","Test generation for your code","Works in VS Code, JetBrains, Vim, Neovim"],"hi":["एडिटर में रियल-टाइम कोड सुझाव","Copilot Chat — VS Code में AI पेयर प्रोग्रामर","15+ प्रोग्रामिंग भाषाओं का समर्थन","PR सारांश और कोड समीक्षा सहायता","CLI कमांड सुझाव","आपके कोड के लिए टेस्ट जनरेशन","VS Code, JetBrains, Vim, Neovim में काम करता है"],"hinglish":["Editor mein real-time code suggestions","Copilot Chat — VS Code mein AI pair programmer","15+ programming languages ka support","PR summaries aur code review assistance","CLI command suggestions","Apne code ke liye test generation","VS Code, JetBrains, Vim, Neovim mein kaam karta hai"]}',
  pros = '{"en":["Dramatically speeds up coding — 55% faster","Best IDE integration among coding assistants","Understands your project context deeply","Free for verified students and open-source maintainers","Excellent for repetitive and boilerplate code"],"hi":["कोडिंग को नाटकीय रूप से तेज़ करता है — 55% तेज़","कोडिंग असिस्टेंट में सबसे अच्छा IDE इंटीग्रेशन","आपके प्रोजेक्ट कॉन्टेक्स्ट को गहराई से समझता है","सत्यापित छात्रों और ओपन-सोर्स मेंटेनर्स के लिए मुफ्त","बॉयलरप्लेट कोड के लिए उत्कृष्ट"],"hinglish":["Coding dramatically tez karta hai — 55% faster","Coding assistants mein best IDE integration","Aapke project context ko deeply samjhta hai","Verified students aur open-source maintainers ke liye free","Repetitive aur boilerplate code ke liye excellent"]}',
  cons = '{"en":["Requires paid subscription for most users","Can suggest insecure or outdated code patterns","Heavy internet reliance — not ideal offline","Privacy concerns for proprietary code bases"],"hi":["अधिकांश उपयोगकर्ताओं के लिए भुगतान सब्सक्रिप्शन","असुरक्षित या पुराने कोड पैटर्न सुझा सकता है","भारी इंटरनेट निर्भरता — ऑफलाइन के लिए आदर्श नहीं","मालिकाना कोड बेस के लिए गोपनीयता चिंताएं"],"hinglish":["Zyaadatar users ke liye paid subscription chahiye","Insecure ya outdated code patterns suggest kar sakta hai","Heavy internet reliance — offline ke liye ideal nahi","Proprietary code bases ke liye privacy concerns"]}',
  use_cases = '{"en":["Autocompleting functions and class definitions","Writing unit tests for existing code","Generating SQL queries from natural language","Explaining legacy code to new team members","Building REST API endpoints quickly","Learning a new programming language faster"],"hi":["फंक्शन और क्लास डेफिनिशन ऑटोकंप्लीट करना","मौजूदा कोड के लिए यूनिट टेस्ट लिखना","प्राकृतिक भाषा से SQL क्वेरी जनरेट करना","नए टीम सदस्यों को लेगेसी कोड समझाना","REST API एंडपॉइंट जल्दी बनाना","नई प्रोग्रामिंग भाषा तेज़ी से सीखना"],"hinglish":["Functions aur class definitions autocomplete karna","Existing code ke liye unit tests likhna","Natural language se SQL queries generate karna","Naye team members ko legacy code samjhana","REST API endpoints jaldi banana","Nayi programming language faster seekhna"]}',
  alternatives = ARRAY['claude','chatgpt','gemini','cursor'],
  hindi_summary = 'GitHub Copilot डेवलपर्स के लिए सबसे उपयोगी AI टूल है। यह VS Code जैसे एडिटर में सीधे कोड लिखने में मदद करता है। भारतीय IT प्रोफेशनल्स और स्टूडेंट्स के लिए यह कोडिंग को 50% तेज़ कर सकता है। छात्रों के लिए मुफ्त में उपलब्ध है।'
WHERE slug = 'github-copilot';


-- ── Grammarly ────────────────────────────────────────────────────────────────
UPDATE public.ai_tools SET
  features = '{"en":["Real-time grammar and spell checking","Tone detection and suggestions","Plagiarism checker (Business plan)","AI-powered rewriting and paraphrase","Style and clarity improvements","Browser extension for everywhere writing","Works in Gmail, LinkedIn, Google Docs and more"],"hi":["रियल-टाइम व्याकरण और वर्तनी जांच","टोन डिटेक्शन और सुझाव","प्लेगियरिज़म चेकर (Business प्लान)","AI-पावर्ड रीराइटिंग और पेराफ्रेज़","शैली और स्पष्टता सुधार","हर जगह लिखने के लिए ब्राउज़र एक्सटेंशन","Gmail, LinkedIn, Google Docs में काम करता है"],"hinglish":["Real-time grammar aur spell checking","Tone detection aur suggestions","Plagiarism checker (Business plan)","AI-powered rewriting aur paraphrase","Style aur clarity improvements","Har jagah likhne ke liye browser extension","Gmail, LinkedIn, Google Docs mein kaam karta hai"]}',
  pros = '{"en":["Best grammar tool in the market — highly accurate","Browser extension works everywhere you type","Excellent for non-native English speakers","Helps improve English writing skills over time","Generous free tier for basic corrections"],"hi":["बाज़ार में सबसे अच्छा व्याकरण टूल — अत्यधिक सटीक","ब्राउज़र एक्सटेंशन जहाँ भी टाइप करें वहां काम करता है","गैर-नेटिव अंग्रेज़ी बोलने वालों के लिए बेहतरीन","समय के साथ अंग्रेज़ी लेखन कौशल सुधारने में मदद","बेसिक करेक्शन के लिए उदार मुफ्त टियर"],"hinglish":["Market mein best grammar tool — highly accurate","Browser extension har jagah kaam karta hai jahan type karo","Non-native English speakers ke liye excellent","Time ke saath English writing skills improve hoti hain","Basic corrections ke liye generous free tier"]}',
  cons = '{"en":["Hindi writing not supported","Advanced AI features locked behind Premium plan","Suggestions sometimes change intended meaning","Privacy: analyzes all your text on their servers"],"hi":["हिंदी लेखन समर्थित नहीं","उन्नत AI फीचर्स Premium प्लान में बंद","सुझाव कभी-कभी इच्छित अर्थ बदल देते हैं","गोपनीयता: उनके सर्वर पर आपके सभी टेक्स्ट का विश्लेषण"],"hinglish":["Hindi writing supported nahi","Advanced AI features Premium plan mein locked","Suggestions kabhi kabhi intended meaning change kar dete hain","Privacy: sare text unke servers pe analyze hota hai"]}',
  use_cases = '{"en":["Proofreading professional emails before sending","Writing error-free LinkedIn and job application content","Academic assignment and essay improvement","Blog and article writing for Indian professionals","Business proposal and pitch deck content","Improving English for non-native speakers"],"hi":["भेजने से पहले प्रोफेशनल ईमेल प्रूफरीडिंग","त्रुटि-मुक्त LinkedIn और नौकरी आवेदन कंटेंट","अकादमिक असाइनमेंट और निबंध सुधार","भारतीय प्रोफेशनल्स के लिए ब्लॉग और लेख","बिज़नेस प्रपोज़ल और पिच डेक कंटेंट","गैर-नेटिव स्पीकर्स के लिए अंग्रेज़ी सुधार"],"hinglish":["Bhejna se pehle professional emails proofreading","Error-free LinkedIn aur job application content","Academic assignments aur essays improve karna","Indian professionals ke liye blog aur articles","Business proposals aur pitch decks","Non-native speakers ke liye English improve karna"]}',
  alternatives = ARRAY['chatgpt','claude','quillbot'],
  hindi_summary = 'Grammarly अंग्रेज़ी लिखने वाले भारतीयों के लिए सबसे उपयोगी टूल है। ईमेल, LinkedIn पोस्ट, जॉब एप्लीकेशन — हर जगह अंग्रेज़ी सही करने में मदद करता है। जो लोग अंग्रेज़ी में बेहतर बनना चाहते हैं उनके लिए यह बेहद उपयोगी है।'
WHERE slug = 'grammarly';


-- ── ElevenLabs ───────────────────────────────────────────────────────────────
UPDATE public.ai_tools SET
  features = '{"en":["Ultra-realistic AI voice synthesis","Voice cloning from 1-minute audio sample","1000+ pre-built voices in 29 languages","Hindi and Indian accent voice options","Audio book and podcast creation","Dubbing — translate and dub videos automatically","API for developers to integrate TTS"],"hi":["अल्ट्रा-रियलिस्टिक AI वॉइस सिंथेसिस","1 मिनट के ऑडियो सैंपल से वॉइस क्लोनिंग","29 भाषाओं में 1000+ पूर्व-निर्मित आवाज़ें","हिंदी और भारतीय एक्सेंट वॉइस विकल्प","ऑडियोबुक और पॉडकास्ट क्रिएशन","डबिंग — वीडियो को स्वचालित रूप से ट्रांसलेट और डब करें","TTS इंटीग्रेट करने के लिए डेवलपर API"],"hinglish":["Ultra-realistic AI voice synthesis","1 minute ke audio sample se voice cloning","29 languages mein 1000+ pre-built voices","Hindi aur Indian accent voice options","Audiobook aur podcast creation","Dubbing — videos ko automatically translate aur dub karo","Developers ke liye TTS integrate karne ka API"]}',
  pros = '{"en":["Most realistic AI voice — nearly indistinguishable from human","Voice cloning is exceptional quality","Excellent Hindi voice options","Great for content creators and YouTubers","Powerful dubbing tool for Indian language content"],"hi":["सबसे यथार्थवादी AI आवाज़ — मानव से लगभग अप्रभेद्य","वॉइस क्लोनिंग असाधारण गुणवत्ता","बेहतरीन हिंदी वॉइस विकल्प","कंटेंट क्रिएटर्स और YouTubers के लिए बेहतरीन","भारतीय भाषा कंटेंट के लिए शक्तिशाली डबिंग टूल"],"hinglish":["Sabse realistic AI voice — human se almost indistinguishable","Voice cloning exceptional quality ka","Excellent Hindi voice options","Content creators aur YouTubers ke liye great","Indian language content ke liye powerful dubbing tool"]}',
  cons = '{"en":["Free tier has monthly character limits","Voice cloning raises ethical concerns if misused","Indian regional language support limited","Premium voices only on paid plans"],"hi":["मुफ्त टियर में मासिक कैरेक्टर सीमा","दुरुपयोग होने पर वॉइस क्लोनिंग नैतिक चिंताएं उठाती है","भारतीय क्षेत्रीय भाषा समर्थन सीमित","भुगतान प्लान पर ही प्रीमियम आवाज़ें"],"hinglish":["Free tier mein monthly character limits","Misuse hone pe voice cloning ethical concerns uthata hai","Indian regional language support limited","Paid plans pe hi premium voices"]}',
  use_cases = '{"en":["Hindi YouTube video voiceovers without recording","Podcast creation in Hindi or English","Dubbing English content to Hindi for Indian audience","Audiobook narration from written content","E-learning course voiceovers","AI customer service voice for businesses"],"hi":["रिकॉर्डिंग के बिना हिंदी YouTube वीडियो वॉइसओवर","हिंदी या अंग्रेज़ी में पॉडकास्ट क्रिएशन","भारतीय दर्शकों के लिए अंग्रेज़ी कंटेंट हिंदी में डब करना","लिखित कंटेंट से ऑडियोबुक नैरेशन","ई-लर्निंग कोर्स वॉइसओवर","बिज़नेस के लिए AI कस्टमर सर्विस वॉइस"],"hinglish":["Recording ke bina Hindi YouTube video voiceovers","Hindi ya English mein podcast creation","Indian audience ke liye English content Hindi mein dub karna","Written content se audiobook narration","E-learning course voiceovers","Businesses ke liye AI customer service voice"]}',
  alternatives = ARRAY['murf-ai','descript','adobe-firefly'],
  hindi_summary = 'ElevenLabs से आप बिना माइक के भी शानदार हिंदी वॉइसओवर बना सकते हैं। YouTube वीडियो, पॉडकास्ट, और ऑडियोबुक के लिए यह सबसे अच्छा AI आवाज़ टूल है। आपकी खुद की आवाज़ का क्लोन भी बना सकता है सिर्फ 1 मिनट की रिकॉर्डिंग से।'
WHERE slug = 'elevenlabs';


-- ── Murf AI ──────────────────────────────────────────────────────────────────
UPDATE public.ai_tools SET
  features = '{"en":["120+ AI voices across Hindi, English and regional languages","Hindi, Tamil, Telugu, Kannada, Bengali voice support","Script-to-speech with timeline editor","Background music and sound effects","Voice pitch, speed and emphasis control","Team collaboration on voice projects","Presentations with voiceover export"],"hi":["हिंदी, अंग्रेज़ी और क्षेत्रीय भाषाओं में 120+ AI आवाज़ें","हिंदी, तमिल, तेलुगु, कन्नड़, बंगाली आवाज़ समर्थन","टाइमलाइन एडिटर के साथ स्क्रिप्ट-टू-स्पीच","बैकग्राउंड म्यूजिक और साउंड इफेक्ट्स","वॉइस पिच, गति और जोर नियंत्रण","वॉइस प्रोजेक्ट पर टीम सहयोग","वॉइसओवर के साथ प्रेजेंटेशन एक्सपोर्ट"],"hinglish":["Hindi, English aur regional languages mein 120+ AI voices","Hindi, Tamil, Telugu, Kannada, Bengali voice support","Timeline editor ke saath script-to-speech","Background music aur sound effects","Voice pitch, speed aur emphasis control","Voice projects pe team collaboration","Voiceover ke saath presentations export"]}',
  pros = '{"en":["Best Indian regional language AI voice quality","Made for Indian content — understands local context","Affordable pricing in INR with UPI support","Excellent for e-learning in regional languages","No recording equipment needed"],"hi":["सबसे अच्छी भारतीय क्षेत्रीय भाषा AI आवाज़ गुणवत्ता","भारतीय कंटेंट के लिए बना — स्थानीय संदर्भ समझता है","UPI समर्थन के साथ INR में किफायती मूल्य","क्षेत्रीय भाषाओं में ई-लर्निंग के लिए बेहतरीन","रिकॉर्डिंग उपकरण की ज़रूरत नहीं"],"hinglish":["Best Indian regional language AI voice quality","Indian content ke liye bana — local context samjhta hai","UPI support ke saath INR mein affordable pricing","Regional languages mein e-learning ke liye excellent","Recording equipment nahi chahiye"]}',
  cons = '{"en":["Free plan has limited character count","Voice cloning not available on base plans","Less expressive than ElevenLabs for emotional content","Fewer language models than global competitors"],"hi":["मुफ्त प्लान में सीमित कैरेक्टर काउंट","बेस प्लान पर वॉइस क्लोनिंग उपलब्ध नहीं","भावनात्मक कंटेंट के लिए ElevenLabs से कम अभिव्यंजक","वैश्विक प्रतिस्पर्धियों की तुलना में कम भाषा मॉडल"],"hinglish":["Free plan mein limited character count","Base plans pe voice cloning available nahi","Emotional content ke liye ElevenLabs se kam expressive","Global competitors ke comparison mein kam language models"]}',
  use_cases = '{"en":["Hindi educational and e-learning video narration","Regional language product explainer videos","IVR and customer service voice recordings","Dubbing YouTube content to Hindi, Tamil, Telugu","Corporate training videos in regional languages","Audiobooks and story narrations in Hindi"],"hi":["हिंदी शैक्षिक और ई-लर्निंग वीडियो नैरेशन","क्षेत्रीय भाषा प्रोडक्ट एक्सप्लेनर वीडियो","IVR और कस्टमर सर्विस वॉइस रिकॉर्डिंग","YouTube कंटेंट को हिंदी, तमिल, तेलुगु में डब करना","क्षेत्रीय भाषाओं में कॉर्पोरेट ट्रेनिंग वीडियो","हिंदी में ऑडियोबुक और कहानी नैरेशन"],"hinglish":["Hindi educational aur e-learning video narration","Regional language product explainer videos","IVR aur customer service voice recordings","YouTube content ko Hindi, Tamil, Telugu mein dub karna","Regional languages mein corporate training videos","Hindi mein audiobooks aur story narrations"]}',
  alternatives = ARRAY['elevenlabs','descript','invideo-ai'],
  hindi_summary = 'Murf AI भारत के लिए बना AI वॉइस टूल है। हिंदी, तमिल, तेलुगु, बंगाली — सभी भारतीय भाषाओं में शानदार AI आवाज़ें मिलती हैं। शिक्षा, YouTube, और बिज़नेस ट्रेनिंग वीडियो के लिए यह सबसे उपयुक्त भारतीय टूल है।'
WHERE slug = 'murf-ai';


-- ── Microsoft Copilot ─────────────────────────────────────────────────────────
UPDATE public.ai_tools SET
  features = '{"en":["Free GPT-4 access via Bing integration","Built into Windows 11 — no extra install","Microsoft 365 integration (Word, Excel, PowerPoint, Outlook)","Real-time web search with citations","Image generation with DALL-E 3","Voice interaction support","Mobile app for Android and iOS"],"hi":["Bing इंटीग्रेशन के माध्यम से मुफ्त GPT-4 एक्सेस","Windows 11 में बिल्ट-इन — कोई अतिरिक्त इंस्टॉल नहीं","Microsoft 365 इंटीग्रेशन (Word, Excel, PowerPoint, Outlook)","उद्धरणों के साथ रियल-टाइम वेब सर्च","DALL-E 3 के साथ इमेज जनरेशन","वॉइस इंटरेक्शन समर्थन","Android और iOS के लिए मोबाइल ऐप"],"hinglish":["Bing integration ke through free GPT-4 access","Windows 11 mein built-in — koi extra install nahi","Microsoft 365 integration (Word, Excel, PowerPoint, Outlook)","Citations ke saath real-time web search","DALL-E 3 ke saath image generation","Voice interaction support","Android aur iOS ke liye mobile app"]}',
  pros = '{"en":["Completely free — GPT-4 quality at zero cost","No signup needed — works with Microsoft account","Best for Office 365 users in corporate India","Real-time web search included","Works offline in basic mode on Windows 11"],"hi":["पूरी तरह मुफ्त — शून्य लागत पर GPT-4 गुणवत्ता","साइनअप ज़रूरी नहीं — Microsoft खाते से काम","भारतीय कॉर्पोरेट में Office 365 यूज़र्स के लिए सबसे अच्छा","रियल-टाइम वेब सर्च शामिल","Windows 11 पर बेसिक मोड में ऑफलाइन काम करता है"],"hinglish":["Bilkul free — zero cost pe GPT-4 quality","Signup nahi chahiye — Microsoft account se kaam","Corporate India mein Office 365 users ke liye best","Real-time web search included","Windows 11 pe basic mode mein offline kaam karta hai"]}',
  cons = '{"en":["Less capable than ChatGPT Plus for complex tasks","Tied to Microsoft ecosystem — less flexible","Hindi quality lower than dedicated Hindi AI tools","Corporate 365 Copilot is expensive for businesses"],"hi":["जटिल कार्यों के लिए ChatGPT Plus से कम सक्षम","Microsoft इकोसिस्टम से बंधा — कम लचीला","समर्पित हिंदी AI टूल्स की तुलना में हिंदी गुणवत्ता कम","बिज़नेस के लिए Corporate 365 Copilot महंगा"],"hinglish":["Complex tasks ke liye ChatGPT Plus se kam capable","Microsoft ecosystem se tied — kam flexible","Dedicated Hindi AI tools ke comparison mein Hindi quality kam","Businesses ke liye Corporate 365 Copilot expensive"]}',
  use_cases = '{"en":["Drafting Word documents and Excel formulas","Summarizing long email threads in Outlook","Free alternative to ChatGPT Plus for daily tasks","Web research and information lookup","PowerPoint presentation creation","General Q&A without paying for premium AI"],"hi":["Word दस्तावेज़ और Excel फ़ार्मूले तैयार करना","Outlook में लंबे ईमेल थ्रेड का सारांश","दैनिक कार्यों के लिए ChatGPT Plus का मुफ्त विकल्प","वेब रिसर्च और जानकारी खोज","PowerPoint प्रेजेंटेशन बनाना","प्रीमियम AI के लिए भुगतान किए बिना सामान्य Q&A"],"hinglish":["Word documents aur Excel formulas banana","Outlook mein lambe email threads summarize karna","Daily tasks ke liye ChatGPT Plus ka free alternative","Web research aur information lookup","PowerPoint presentations banana","Premium AI ke liye pay kiye bina general Q&A"]}',
  alternatives = ARRAY['chatgpt','gemini','perplexity-ai','claude'],
  hindi_summary = 'Microsoft Copilot बिल्कुल मुफ्त है और GPT-4 की तरह काम करता है। अगर आप Windows या Microsoft Office उपयोग करते हैं तो यह पहले से ही आपके कंप्यूटर में है। ChatGPT का एक अच्छा मुफ्त विकल्प जो रियल-टाइम इंटरनेट से भी जुड़ा है।'
WHERE slug = 'microsoft-copilot';


-- ── Notion AI ────────────────────────────────────────────────────────────────
UPDATE public.ai_tools SET
  features = '{"en":["AI writing and editing inside Notion workspace","Autofill tables and databases with AI","Summarize long notes and meeting transcripts","Translate content to multiple languages","Generate action items from meeting notes","Q&A chat over your entire Notion workspace","Works inside existing Notion pages"],"hi":["Notion वर्कस्पेस के अंदर AI लेखन और संपादन","AI के साथ टेबल और डेटाबेस ऑटोफिल करना","लंबे नोट्स और मीटिंग ट्रांसक्रिप्ट का सारांश","एकाधिक भाषाओं में कंटेंट अनुवाद","मीटिंग नोट्स से एक्शन आइटम जनरेट करना","आपके पूरे Notion वर्कस्पेस पर Q&A चैट","मौजूदा Notion पेज के अंदर काम करता है"],"hinglish":["Notion workspace ke andar AI writing aur editing","AI ke saath tables aur databases autofill karna","Lambe notes aur meeting transcripts summarize karna","Multiple languages mein content translate karna","Meeting notes se action items generate karna","Poore Notion workspace pe Q&A chat","Existing Notion pages ke andar kaam karta hai"]}',
  pros = '{"en":["Seamlessly integrated into your existing notes and docs","Excellent for meeting notes summarization","Helps teams collaborate with AI in one place","Available as add-on to existing Notion plans","Great for project management with AI assistance"],"hi":["आपके मौजूदा नोट्स और दस्तावेज़ों में सहजता से इंटीग्रेटेड","मीटिंग नोट्स सारांश के लिए बेहतरीन","टीमों को एक जगह AI के साथ सहयोग में मदद","मौजूदा Notion प्लान में ऐड-ऑन के रूप में उपलब्ध","AI सहायता के साथ प्रोजेक्ट मैनेजमेंट के लिए बेहतरीन"],"hinglish":["Existing notes aur docs mein seamlessly integrated","Meeting notes summarization ke liye excellent","Teams ko ek jagah AI ke saath collaborate karne mein madad","Existing Notion plans mein add-on ke roop mein available","AI assistance ke saath project management ke liye great"]}',
  cons = '{"en":["Requires Notion subscription to use AI features","Less powerful than standalone ChatGPT for complex tasks","Hindi support is limited","AI features add extra cost on top of Notion plan"],"hi":["AI फीचर्स के लिए Notion सब्सक्रिप्शन ज़रूरी","जटिल कार्यों के लिए standalone ChatGPT से कम शक्तिशाली","हिंदी समर्थन सीमित है","Notion प्लान के ऊपर AI फीचर्स की अतिरिक्त लागत"],"hinglish":["AI features ke liye Notion subscription chahiye","Complex tasks ke liye standalone ChatGPT se kam powerful","Hindi support limited hai","Notion plan ke upar AI features extra cost lagte hain"]}',
  use_cases = '{"en":["Summarizing weekly meeting notes automatically","Drafting project plans and SOPs inside Notion","Building personal knowledge base with AI search","Generating blog post outlines from bullet points","Team wikis and documentation with AI assistance","Student notes organization and summarization"],"hi":["साप्ताहिक मीटिंग नोट्स को स्वचालित रूप से सारांशित करना","Notion के अंदर प्रोजेक्ट प्लान और SOP तैयार करना","AI सर्च के साथ व्यक्तिगत ज्ञान आधार बनाना","बुलेट पॉइंट से ब्लॉग पोस्ट आउटलाइन जनरेट करना","AI सहायता के साथ टीम विकी और दस्तावेज़ीकरण","छात्र नोट्स संगठन और सारांश"],"hinglish":["Weekly meeting notes automatically summarize karna","Notion ke andar project plans aur SOPs draft karna","AI search ke saath personal knowledge base banana","Bullet points se blog post outlines generate karna","AI assistance ke saath team wikis aur documentation","Student notes organization aur summarization"]}',
  alternatives = ARRAY['chatgpt','claude','microsoft-copilot'],
  hindi_summary = 'Notion AI आपके Notion workspace के अंदर ही AI की शक्ति देता है। मीटिंग नोट्स का सारांश, प्रोजेक्ट प्लान, और बड़े दस्तावेज़ों का विश्लेषण — सब Notion में ही हो जाता है। टीम वर्क के लिए यह बहुत उपयोगी है।'
WHERE slug = 'notion-ai';


-- ── Adobe Firefly ────────────────────────────────────────────────────────────
UPDATE public.ai_tools SET
  features = '{"en":["Text-to-image generation trained on licensed content","Generative Fill — add/remove objects in Photoshop","Generative Expand — extend images outward","Text effects — apply textures and styles to text","Vector generation for illustrations","Commercial safe — all output is copyright-clear","Integrated in Photoshop, Illustrator and Express"],"hi":["लाइसेंस प्राप्त कंटेंट पर प्रशिक्षित टेक्स्ट-टू-इमेज","Generative Fill — Photoshop में ऑब्जेक्ट जोड़ें/हटाएं","Generative Expand — इमेज को बाहर की ओर फैलाएं","Text इफेक्ट्स — टेक्स्ट पर टेक्सचर और स्टाइल लगाएं","चित्रों के लिए वेक्टर जनरेशन","कमर्शियल सेफ — सभी आउटपुट कॉपीराइट-स्पष्ट","Photoshop, Illustrator और Express में इंटीग्रेटेड"],"hinglish":["Licensed content pe trained text-to-image","Generative Fill — Photoshop mein objects add/remove karo","Generative Expand — images ko outward extend karo","Text effects — text pe textures aur styles lagao","Illustrations ke liye vector generation","Commercial safe — sab output copyright-clear","Photoshop, Illustrator aur Express mein integrated"]}',
  pros = '{"en":["Commercially safe — trained on licensed Adobe content","Deep integration with Photoshop is unmatched","No copyright risk for commercial projects","Generative Fill is a revolutionary editing tool","Free credits available monthly"],"hi":["कमर्शियल रूप से सुरक्षित — लाइसेंस प्राप्त Adobe कंटेंट पर प्रशिक्षित","Photoshop के साथ गहरा इंटीग्रेशन अद्वितीय है","कमर्शियल प्रोजेक्ट के लिए कोई कॉपीराइट जोखिम नहीं","Generative Fill एक क्रांतिकारी एडिटिंग टूल है","मासिक रूप से मुफ्त क्रेडिट उपलब्ध"],"hinglish":["Commercially safe — licensed Adobe content pe trained","Photoshop ke saath deep integration unmatched hai","Commercial projects ke liye koi copyright risk nahi","Generative Fill ek revolutionary editing tool hai","Monthly free credits available hain"]}',
  cons = '{"en":["Artistic quality not as stunning as Midjourney","Requires Adobe Creative Cloud for best integration","Monthly credit limits — fast to exhaust","Steeper learning curve for non-Adobe users"],"hi":["Midjourney जितनी शानदार कलात्मक गुणवत्ता नहीं","सर्वोत्तम इंटीग्रेशन के लिए Adobe Creative Cloud ज़रूरी","मासिक क्रेडिट सीमाएं — जल्दी खत्म","नॉन-Adobe यूज़र्स के लिए अधिक सीखने की ज़रूरत"],"hinglish":["Midjourney jaisi stunning artistic quality nahi","Best integration ke liye Adobe Creative Cloud chahiye","Monthly credit limits — jaldi khatam","Non-Adobe users ke liye steep learning curve"]}',
  use_cases = '{"en":["Removing unwanted objects from photos professionally","Extending backgrounds in product photography","Creating logo designs and brand assets","Commercial poster and banner design","Editorial image enhancement and manipulation","Professional photo retouching for studios"],"hi":["फोटो से अनचाहे ऑब्जेक्ट पेशेवर रूप से हटाना","प्रोडक्ट फोटोग्राफी में बैकग्राउंड फैलाना","लोगो डिज़ाइन और ब्रांड एसेट बनाना","कमर्शियल पोस्टर और बैनर डिज़ाइन","एडिटोरियल इमेज एन्हांसमेंट और मैनीपुलेशन","स्टूडियो के लिए प्रोफेशनल फोटो रीटचिंग"],"hinglish":["Photos se unwanted objects professionally hatana","Product photography mein backgrounds extend karna","Logo designs aur brand assets banana","Commercial posters aur banner design","Editorial image enhancement aur manipulation","Studios ke liye professional photo retouching"]}',
  alternatives = ARRAY['midjourney','dall-e-3','stable-diffusion','canva-ai-magic-studio'],
  hindi_summary = 'Adobe Firefly Photoshop में सीधे AI की शक्ति देता है। किसी भी फोटो से अनचाहे हिस्से हटाने, बैकग्राउंड बदलने, या नई चीज़ें जोड़ने के लिए यह सबसे अच्छा टूल है। कमर्शियल प्रोजेक्ट के लिए कॉपीराइट-सेफ भी है।'
WHERE slug = 'adobe-firefly';
