# -*- coding: utf-8 -*-
"""Appends productivity + music + business + education + data tools."""

path = r'c:\p\p\Project\AITools\aihkya\supabase\migrations\0011_tool_content_seed_remaining.sql'

sql = """
-- ── Otter.ai ─────────────────────────────────────────────────
UPDATE public.ai_tools SET
  features = '{"en":["Real-time AI transcription of meetings","Auto-generated meeting summaries","Action item and keyword extraction","Integrates with Zoom, Google Meet, Teams","OtterPilot: joins meetings automatically","Shared notes for team collaboration","Mobile app for in-person meetings"],"hi":["मीटिंग की रियल-टाइम AI ट्रांसक्रिप्शन","ऑटो-जनरेटेड मीटिंग सारांश","Action item और keyword extraction","Zoom, Google Meet, Teams के साथ एकीकृत","OtterPilot: मीटिंग में स्वचालित रूप से join करता है","टीम सहयोग के लिए Shared notes","In-person मीटिंग के लिए Mobile app"],"hinglish":["Meetings ki real-time AI transcription","Auto-generated meeting summaries","Action items aur keyword extraction","Zoom, Google Meet, Teams ke saath integrated","OtterPilot: automatically meetings mein join karta hai","Team collaboration ke liye shared notes","In-person meetings ke liye mobile app"]}',
  pros = '{"en":["Best meeting transcription tool available","OtterPilot auto-joins and transcribes without effort","Summaries save hours of note-taking","Good integration with video conferencing tools","Free tier is very usable"],"hi":["उपलब्ध सबसे अच्छा मीटिंग ट्रांसक्रिप्शन टूल","OtterPilot बिना प्रयास के auto-join और transcribe करता है","Summaries note-taking में घंटों बचाती हैं","वीडियो कॉन्फ्रेंसिंग टूल के साथ अच्छा इंटीग्रेशन","मुफ्त टियर बहुत उपयोगी"],"hinglish":["Available best meeting transcription tool","OtterPilot bina effort ke auto-join aur transcribe karta hai","Summaries note-taking mein ghante bachati hain","Video conferencing tools ke saath achha integration","Free tier bahut usable"]}',
  cons = '{"en":["Hindi transcription accuracy is poor","Free tier limited to 300 minutes/month","Accuracy suffers with strong accents","Privacy concerns for sensitive meetings"],"hi":["हिंदी ट्रांसक्रिप्शन सटीकता खराब है","मुफ्त टियर 300 मिनट/माह तक सीमित","मजबूत उच्चारण के साथ सटीकता कम होती है","संवेदनशील मीटिंग के लिए गोपनीयता चिंताएं"],"hinglish":["Hindi transcription accuracy kharab hai","Free tier 300 minutes/month tak limited","Strong accents ke saath accuracy kam hoti hai","Sensitive meetings ke liye privacy concerns"]}',
  use_cases = '{"en":["Recording and transcribing business meetings","Interview transcription for journalists","Lecture recording for students","Sales call recording and analysis","Podcast transcription","Team meeting notes and action items"],"hi":["व्यापार मीटिंग रिकॉर्डिंग और ट्रांसक्रिप्शन","पत्रकारों के लिए इंटरव्यू ट्रांसक्रिप्शन","छात्रों के लिए लेक्चर रिकॉर्डिंग","सेल्स कॉल रिकॉर्डिंग और विश्लेषण","पॉडकास्ट ट्रांसक्रिप्शन","टीम मीटिंग नोट्स और action items"],"hinglish":["Business meetings record aur transcribe karna","Journalists ke liye interview transcription","Students ke liye lecture recording","Sales call recording aur analysis","Podcast transcription","Team meeting notes aur action items"]}',
  alternatives = ARRAY['fireflies-ai','circleback','notion-ai'],
  hindi_summary = 'Otter.ai मीटिंग को AI से transcribe करता है और summary देता है। Zoom या Google Meet पर OtterPilot खुद join करके notes लेता है — मीटिंग के बाद तुरंत summary और action items।'
WHERE slug IN ('otter-ai','otterai');

-- ── Fireflies.ai ──────────────────────────────────────────────
UPDATE public.ai_tools SET
  features = '{"en":["AI meeting recorder and transcriber","Smart search across all meeting transcripts","AskFred: AI chatbot for meeting content","CRM integration (Salesforce, HubSpot)","Meeting intelligence and coaching","Automated action item tracking","Supports 69 languages"],"hi":["AI मीटिंग रिकॉर्डर और ट्रांसक्राइबर","सभी मीटिंग ट्रांसक्रिप्ट में Smart search","AskFred: मीटिंग कंटेंट के लिए AI chatbot","CRM इंटीग्रेशन (Salesforce, HubSpot)","मीटिंग intelligence और coaching","स्वचालित action item ट्रैकिंग","69 भाषाओं का समर्थन"],"hinglish":["AI meeting recorder aur transcriber","Sabhi meeting transcripts mein smart search","AskFred: meeting content ke liye AI chatbot","CRM integration (Salesforce, HubSpot)","Meeting intelligence aur coaching","Automated action item tracking","69 languages support"]}',
  pros = '{"en":["CRM integration is best-in-class","AskFred AI assistant adds great value","Smart search across all past meetings","Good sales call intelligence features","Free tier with unlimited transcription"],"hi":["CRM इंटीग्रेशन सर्वश्रेष्ठ है","AskFred AI असिस्टेंट बेहतरीन value जोड़ता है","सभी पिछली मीटिंग में Smart search","अच्छे sales call intelligence फीचर्स","असीमित ट्रांसक्रिप्शन के साथ मुफ्त टियर"],"hinglish":["CRM integration best-in-class hai","AskFred AI assistant great value add karta hai","Sabhi past meetings mein smart search","Achhe sales call intelligence features","Unlimited transcription ke saath free tier"]}',
  cons = '{"en":["Hindi accuracy still needs improvement","AskFred requires paid plan","Storage limits on free plan","Some users report privacy concerns"],"hi":["हिंदी सटीकता में अभी सुधार जरूरी","AskFred के लिए paid प्लान जरूरी","मुफ्त प्लान पर storage सीमाएं","कुछ users गोपनीयता चिंताएं रिपोर्ट करते हैं"],"hinglish":["Hindi accuracy mein abhi improvement zaroori","AskFred ke liye paid plan zaroori","Free plan pe storage limits","Kuch users privacy concerns report karte hain"]}',
  use_cases = '{"en":["Sales team call recording and CRM sync","Remote team meeting transcription","Customer interview recording","Investor meeting notes","Podcast production workflow","HR interview documentation"],"hi":["सेल्स टीम कॉल रिकॉर्डिंग और CRM sync","रिमोट टीम मीटिंग ट्रांसक्रिप्शन","कस्टमर इंटरव्यू रिकॉर्डिंग","Investor मीटिंग नोट्स","पॉडकास्ट प्रोडक्शन वर्कफ्लो","HR इंटरव्यू दस्तावेज़ीकरण"],"hinglish":["Sales team call recording aur CRM sync","Remote team meeting transcription","Customer interview recording","Investor meeting notes","Podcast production workflow","HR interview documentation"]}',
  alternatives = ARRAY['otter-ai','circleback','notion-ai'],
  hindi_summary = 'Fireflies.ai मीटिंग record करके transcript और summary देता है — Salesforce/HubSpot CRM के साथ sync। Sales teams के लिए AskFred AI assistant meeting insights देता है।'
WHERE slug = 'fireflies-ai';

-- ── Circleback ────────────────────────────────────────────────
UPDATE public.ai_tools SET
  features = '{"en":["AI meeting notes and summaries","Action item extraction with owner assignment","Integrates with Zoom, Meet, Teams, Slack","CRM and project tool sync","Meeting search across history","Follow-up email drafting","Clean minimal interface"],"hi":["AI मीटिंग नोट्स और सारांश","Owner assignment के साथ Action item extraction","Zoom, Meet, Teams, Slack के साथ एकीकृत","CRM और project टूल sync","मीटिंग इतिहास में search","Follow-up ईमेल ड्राफ्टिंग","साफ minimal इंटरफेस"],"hinglish":["AI meeting notes aur summaries","Owner assignment ke saath action item extraction","Zoom, Meet, Teams, Slack ke saath integrated","CRM aur project tool sync","Meeting history mein search","Follow-up email drafting","Clean minimal interface"]}',
  pros = '{"en":["Very clean and minimal interface","Good action item tracking with ownership","Integrates well with productivity tools","AI summary quality is high","Good for small teams"],"hi":["बहुत साफ और minimal इंटरफेस","Ownership के साथ अच्छा action item ट्रैकिंग","Productivity टूल के साथ अच्छा इंटीग्रेट","AI summary गुणवत्ता अच्छी है","छोटी टीमों के लिए अच्छा"],"hinglish":["Bahut clean aur minimal interface","Ownership ke saath achha action item tracking","Productivity tools ke saath achha integrate","AI summary quality achhi hai","Chhoti teams ke liye achha"]}',
  cons = '{"en":["Less known and smaller community","Limited free tier","Hindi transcription not supported well","Fewer integrations than Fireflies"],"hi":["कम जाना-पहचाना और छोटा समुदाय","सीमित मुफ्त टियर","हिंदी ट्रांसक्रिप्शन अच्छे से समर्थित नहीं","Fireflies से कम integrations"],"hinglish":["Kam popular aur chhoti community","Limited free tier","Hindi transcription achhe se supported nahi","Fireflies se kam integrations"]}',
  use_cases = '{"en":["Team meeting action tracking","Client call documentation","Project kickoff meeting notes","Investor call summaries","Cross-team sync meeting notes","Customer success call documentation"],"hi":["टीम मीटिंग action ट्रैकिंग","क्लाइंट कॉल दस्तावेज़ीकरण","Project kickoff मीटिंग नोट्स","Investor कॉल सारांश","Cross-team sync मीटिंग नोट्स","Customer success कॉल दस्तावेज़ीकरण"],"hinglish":["Team meeting action tracking","Client call documentation","Project kickoff meeting notes","Investor call summaries","Cross-team sync meeting notes","Customer success call documentation"]}',
  alternatives = ARRAY['otter-ai','fireflies-ai','notion-ai'],
  hindi_summary = 'Circleback मीटिंग के action items AI से track करता है और सही व्यक्ति को assign करता है। Clean interface और Slack/Notion integration के साथ छोटी teams के लिए perfect।'
WHERE slug = 'circleback';

-- ── Reclaim.ai ────────────────────────────────────────────────
UPDATE public.ai_tools SET
  features = '{"en":["AI scheduling and calendar optimization","Automatically finds best meeting times","Protects focus time from meetings","Habits: schedule recurring personal tasks","Smart 1:1 meeting scheduling","Buffer time between meetings","Integrates with Google Calendar"],"hi":["AI scheduling और calendar ऑप्टिमाइज़ेशन","मीटिंग के लिए सबसे अच्छा समय स्वचालित रूप से ढूंढता है","मीटिंग से focus time की रक्षा करता है","Habits: आवर्ती personal tasks schedule करना","Smart 1:1 मीटिंग scheduling","मीटिंग के बीच Buffer time","Google Calendar के साथ एकीकृत"],"hinglish":["AI scheduling aur calendar optimization","Meetings ke liye best time automatically dhundhta hai","Meetings se focus time protect karta hai","Habits: recurring personal tasks schedule karna","Smart 1:1 meeting scheduling","Meetings ke beech buffer time","Google Calendar ke saath integrated"]}',
  pros = '{"en":["Best AI calendar and scheduling tool","Protects focus blocks automatically","Habit scheduling is unique and valuable","Reduces back-and-forth for meeting scheduling","Free tier available"],"hi":["सबसे अच्छा AI calendar और scheduling टूल","Focus blocks स्वचालित रूप से protect करता है","Habit scheduling अनूठा और मूल्यवान है","मीटिंग scheduling के लिए back-and-forth कम करता है","मुफ्त टियर उपलब्ध"],"hinglish":["Best AI calendar aur scheduling tool","Focus blocks automatically protect karta hai","Habit scheduling unique aur valuable hai","Meeting scheduling ke liye back-and-forth kam karta hai","Free tier available"]}',
  cons = '{"en":["Only works with Google Calendar currently","Complex setup for full benefits","Team features require paid plan","No support for Indian regional work patterns"],"hi":["वर्तमान में केवल Google Calendar के साथ काम करता है","पूर्ण लाभों के लिए जटिल सेटअप","टीम फीचर्स के लिए paid प्लान जरूरी","भारतीय क्षेत्रीय काम पैटर्न के लिए कोई समर्थन नहीं"],"hinglish":["Abhi sirf Google Calendar ke saath kaam karta hai","Full benefits ke liye complex setup","Team features ke liye paid plan zaroori","Indian regional work patterns ke liye koi support nahi"]}',
  use_cases = '{"en":["Protecting deep work and focus time","Scheduling team meetings without conflicts","Automating recurring 1:1 meetings","Work-life balance calendar management","Remote team scheduling across time zones","Startup founder calendar optimization"],"hi":["Deep work और focus time की रक्षा करना","बिना conflicts के टीम मीटिंग scheduling","आवर्ती 1:1 मीटिंग स्वचालित करना","Work-life balance calendar management","समय क्षेत्रों में रिमोट टीम scheduling","Startup founder calendar ऑप्टिमाइज़ेशन"],"hinglish":["Deep work aur focus time protect karna","Bina conflicts ke team meetings schedule karna","Recurring 1:1 meetings automate karna","Work-life balance calendar management","Time zones mein remote team scheduling","Startup founder calendar optimization"]}',
  alternatives = ARRAY['motion-ai','notion-ai','taskade'],
  hindi_summary = 'Reclaim.ai आपकी Google Calendar को AI से manage करता है — focus time protect करना, meeting conflicts avoid करना, और अच्छी habits को schedule में बनाए रखना।'
WHERE slug = 'reclaim-ai';

-- ── Motion ────────────────────────────────────────────────────
UPDATE public.ai_tools SET
  features = '{"en":["AI automatically plans your day from tasks","Calendar, tasks and projects in one app","Auto-reschedules when plans change","Meeting scheduling with smart availability","Project management with AI prioritization","Deadline tracking with automatic rebalancing","Integrates with Google and Outlook Calendar"],"hi":["AI स्वचालित रूप से tasks से आपका दिन plan करता है","Calendar, tasks और projects एक ऐप में","Plan बदलने पर Auto-reschedule करता है","Smart availability के साथ मीटिंग scheduling","AI प्राथमिकता के साथ Project management","Automatic rebalancing के साथ Deadline ट्रैकिंग","Google और Outlook Calendar के साथ एकीकृत"],"hinglish":["AI automatically tasks se aapka din plan karta hai","Calendar, tasks aur projects ek app mein","Plans change hone pe auto-reschedule karta hai","Smart availability ke saath meeting scheduling","AI prioritization ke saath project management","Automatic rebalancing ke saath deadline tracking","Google aur Outlook Calendar ke saath integrated"]}',
  pros = '{"en":["Most advanced AI scheduling tool","Auto-rescheduling when priorities change is magical","All-in-one calendar + tasks + projects","Reduces daily planning overhead significantly","Great for busy professionals and founders"],"hi":["सबसे उन्नत AI scheduling टूल","प्राथमिकताएं बदलने पर Auto-rescheduling जादुई है","ऑल-इन-वन calendar + tasks + projects","दैनिक planning overhead को महत्वपूर्ण रूप से कम करता है","व्यस्त professionals और founders के लिए बेहतरीन"],"hinglish":["Sabse advanced AI scheduling tool","Priorities change hone pe auto-rescheduling magical hai","All-in-one calendar + tasks + projects","Daily planning overhead significantly kam karta hai","Busy professionals aur founders ke liye great"]}',
  cons = '{"en":["Expensive — $34/month","Steep learning curve","AI decisions can sometimes conflict with preferences","No free tier — only 7-day trial"],"hi":["महंगा — $34/माह","सीखने की कठिनाई","AI निर्णय कभी-कभी प्राथमिकताओं से टकरा सकते हैं","कोई मुफ्त टियर नहीं — केवल 7-दिन का trial"],"hinglish":["Mehanga — $34/month","Steep learning curve","AI decisions kabhi kabhi preferences se conflict kar sakte hain","Koi free tier nahi — sirf 7-din ka trial"]}',
  use_cases = '{"en":["Startup founders managing many priorities","Project managers with multiple deadlines","Freelancers juggling many clients","Remote workers with heavy meeting load","Anyone suffering from calendar chaos","High-output professionals who value focus"],"hi":["कई प्राथमिकताएं manage करने वाले Startup founders","कई deadlines वाले Project managers","कई clients juggle करने वाले Freelancers","भारी मीटिंग load वाले Remote workers","Calendar chaos से पीड़ित कोई भी","Focus को महत्व देने वाले High-output professionals"],"hinglish":["Kai priorities manage karne wale startup founders","Kai deadlines wale project managers","Kai clients juggle karne wale freelancers","Heavy meeting load wale remote workers","Calendar chaos se pareshaan koi bhi","Focus ko value karne wale high-output professionals"]}',
  alternatives = ARRAY['reclaim-ai','notion-ai','taskade','clickup-ai'],
  hindi_summary = 'Motion AI से आपकी पूरी दिनचर्या plan करता है — tasks, meetings, deadlines सब automatically organize। Busy founders और professionals के लिए time management का AI solution।'
WHERE slug IN ('motion-ai','motion');

-- ── Zapier ────────────────────────────────────────────────────
UPDATE public.ai_tools SET
  features = '{"en":["Connect 6000+ apps without coding","AI-powered Zap creation from natural language","Multi-step workflows (Zaps)","AI by Zapier: use ChatGPT in any workflow","Conditional logic and filters","Webhooks and custom integrations","Free tier with 100 tasks/month"],"hi":["बिना कोडिंग के 6000+ ऐप connect करें","प्राकृतिक भाषा से AI-पावर्ड Zap क्रिएशन","Multi-step workflows (Zaps)","AI by Zapier: किसी भी workflow में ChatGPT उपयोग करें","Conditional logic और filters","Webhooks और custom integrations","100 tasks/माह के साथ मुफ्त टियर"],"hinglish":["Bina coding ke 6000+ apps connect karo","Natural language se AI-powered Zap creation","Multi-step workflows (Zaps)","AI by Zapier: kisi bhi workflow mein ChatGPT use karo","Conditional logic aur filters","Webhooks aur custom integrations","100 tasks/month ke saath free tier"]}',
  pros = '{"en":["Largest app integration library (6000+)","Most reliable and well-established platform","AI Zap creation makes setup faster","Excellent documentation and community","Best choice for non-technical users"],"hi":["सबसे बड़ी ऐप integration लाइब्रेरी (6000+)","सबसे विश्वसनीय और स्थापित प्लेटफॉर्म","AI Zap क्रिएशन सेटअप तेज़ बनाता है","उत्कृष्ट दस्तावेज़ीकरण और समुदाय","गैर-तकनीकी users के लिए सबसे अच्छा विकल्प"],"hinglish":["Sabse badi app integration library (6000+)","Sabse reliable aur well-established platform","AI Zap creation setup faster banata hai","Excellent documentation aur community","Non-technical users ke liye best choice"]}',
  cons = '{"en":["Expensive for high task volumes","Free tier very limited (100 tasks/month)","Multi-step zaps require paid plan","Complex workflows better handled by n8n"],"hi":["उच्च task volumes के लिए महंगा","मुफ्त टियर बहुत सीमित (100 tasks/माह)","Multi-step zaps के लिए paid प्लान जरूरी","जटिल workflows n8n से बेहतर handle होते हैं"],"hinglish":["High task volumes ke liye mehanga","Free tier bahut limited (100 tasks/month)","Multi-step zaps ke liye paid plan zaroori","Complex workflows n8n se better handle hote hain"]}',
  use_cases = '{"en":["Connecting CRM to email marketing tools","Automating lead capture and follow-up","Social media post scheduling from spreadsheets","Customer support ticket creation","E-commerce order notification automation","HR onboarding task automation"],"hi":["CRM को ईमेल मार्केटिंग टूल से connect करना","Lead capture और follow-up automation","Spreadsheets से सोशल मीडिया पोस्ट scheduling","कस्टमर सपोर्ट ticket क्रिएशन","E-commerce ऑर्डर notification automation","HR onboarding task automation"],"hinglish":["CRM ko email marketing tools se connect karna","Lead capture aur follow-up automation","Spreadsheets se social media post scheduling","Customer support ticket creation","E-commerce order notification automation","HR onboarding task automation"]}',
  alternatives = ARRAY['make-com','n8n'],
  hindi_summary = 'Zapier 6000+ ऐप को बिना coding के connect करता है — जब भी कुछ हो, दूसरे ऐप में automatically action हो। भारतीय businesses के लिए CRM, ईमेल, और social media automation का सबसे आसान तरीका।'
WHERE slug = 'zapier';

-- ── Make.com ──────────────────────────────────────────────────
UPDATE public.ai_tools SET
  features = '{"en":["Visual workflow automation with 1500+ apps","More powerful than Zapier for complex workflows","HTTP/Webhooks for custom integrations","Data transformation and routing","Error handling and retry logic","Free tier with 1000 operations/month","AI modules for OpenAI and other LLMs"],"hi":["1500+ ऐप के साथ Visual workflow automation","जटिल workflows के लिए Zapier से अधिक शक्तिशाली","Custom integrations के लिए HTTP/Webhooks","Data transformation और routing","Error handling और retry logic","1000 operations/माह के साथ मुफ्त टियर","OpenAI और अन्य LLMs के लिए AI modules"],"hinglish":["1500+ apps ke saath visual workflow automation","Complex workflows ke liye Zapier se zyada powerful","Custom integrations ke liye HTTP/Webhooks","Data transformation aur routing","Error handling aur retry logic","1000 operations/month ke saath free tier","OpenAI aur other LLMs ke liye AI modules"]}',
  pros = '{"en":["More powerful than Zapier for complex logic","Better free tier than Zapier","Visual interface is excellent for complex flows","Data transformation capabilities are superior","More affordable for high-volume automations"],"hi":["जटिल logic के लिए Zapier से अधिक शक्तिशाली","Zapier से बेहतर मुफ्त टियर","जटिल flows के लिए Visual interface उत्कृष्ट है","Data transformation क्षमताएं बेहतर हैं","उच्च-volume automations के लिए अधिक किफायती"],"hinglish":["Complex logic ke liye Zapier se zyada powerful","Zapier se better free tier","Complex flows ke liye visual interface excellent hai","Data transformation capabilities superior hain","High-volume automations ke liye zyada affordable"]}',
  cons = '{"en":["Steeper learning curve than Zapier","Fewer apps than Zapier (1500 vs 6000)","Documentation less comprehensive than Zapier","Can be complex for simple use cases"],"hi":["Zapier से अधिक सीखने की कठिनाई","Zapier से कम ऐप (1500 vs 6000)","Zapier से कम व्यापक दस्तावेज़ीकरण","सरल use cases के लिए जटिल हो सकता है"],"hinglish":["Zapier se zyada learning curve","Zapier se kam apps (1500 vs 6000)","Zapier se kam comprehensive documentation","Simple use cases ke liye complex ho sakta hai"]}',
  use_cases = '{"en":["Complex multi-step business automations","Data processing pipelines","E-commerce order management automation","Marketing automation with conditional logic","API integration without coding","Lead scoring and routing workflows"],"hi":["जटिल multi-step business automations","Data processing pipelines","E-commerce ऑर्डर management automation","Conditional logic के साथ Marketing automation","बिना coding के API integration","Lead scoring और routing workflows"],"hinglish":["Complex multi-step business automations","Data processing pipelines","E-commerce order management automation","Conditional logic ke saath marketing automation","Bina coding ke API integration","Lead scoring aur routing workflows"]}',
  alternatives = ARRAY['zapier','n8n'],
  hindi_summary = 'Make.com Zapier का अधिक powerful विकल्प है — जटिल automations और बेहतर free tier। Visual flow builder से देखो कि data कैसे flow करता है। Developers और advanced users के लिए।'
WHERE slug = 'make-com';

-- ── Suno AI ────────────────────────────────────────────────────
UPDATE public.ai_tools SET
  features = '{"en":["Generate full songs from text prompts","Vocals, instruments and mixing — all AI-generated","Custom lyrics or auto-generated lyrics","Multiple music genres and styles","Hindi and Indian music style support","Free tier with 50 credits/day","Song extending and remixing features"],"hi":["टेक्स्ट प्रॉम्प्ट से पूरे गाने जनरेट करें","वोकल, इंस्ट्रूमेंट और mixing — सब AI-जनरेटेड","Custom lyrics या ऑटो-जनरेटेड lyrics","कई म्यूज़िक genres और styles","हिंदी और भारतीय म्यूज़िक style समर्थन","50 credits/दिन के साथ मुफ्त टियर","Song extending और remixing फीचर्स"],"hinglish":["Text prompts se poore gaane generate karo","Vocals, instruments aur mixing — sab AI-generated","Custom lyrics ya auto-generated lyrics","Multiple music genres aur styles","Hindi aur Indian music style support","50 credits/din ke saath free tier","Song extending aur remixing features"]}',
  pros = '{"en":["Best AI music generation tool available","Actually produces listenable, enjoyable songs","Free tier is very generous","Huge variety of genres and styles","Hindi and Bollywood style possible"],"hi":["उपलब्ध सबसे अच्छा AI म्यूज़िक जनरेशन टूल","वास्तव में सुनने योग्य, आनंददायक गाने बनाता है","मुफ्त टियर बहुत उदार है","Genres और styles की विशाल विविधता","हिंदी और बॉलीवुड स्टाइल संभव"],"hinglish":["Available best AI music generation tool","Actually sunne layak, enjoyable songs banata hai","Free tier bahut generous hai","Genres aur styles ki badi variety","Hindi aur Bollywood style possible"]}',
  cons = '{"en":["Commercial use requires paid plan","Generated songs cannot always be published commercially","AI cannot yet match professional music production","Some vocal styles sound unnatural"],"hi":["Commercial उपयोग के लिए paid प्लान जरूरी","जनरेटेड गाने हमेशा व्यावसायिक रूप से प्रकाशित नहीं किए जा सकते","AI अभी professional म्यूज़िक प्रोडक्शन से मेल नहीं खा सकता","कुछ vocal styles अप्राकृतिक लगते हैं"],"hinglish":["Commercial use ke liye paid plan zaroori","Generated songs hamesha commercially publish nahi kiye ja sakte","AI abhi professional music production se match nahi kar sakta","Kuch vocal styles unnatural lagte hain"]}',
  use_cases = '{"en":["Creating background music for videos","Making jingles for small business ads","Exploring music composition ideas","Personal entertainment and fun","Podcast and YouTube intro music","Learning about music genres"],"hi":["वीडियो के लिए बैकग्राउंड म्यूज़िक बनाना","छोटे व्यापार विज्ञापनों के लिए jingles बनाना","म्यूज़िक कंपोज़िशन ideas explore करना","व्यक्तिगत मनोरंजन और मज़ा","पॉडकास्ट और YouTube इंट्रो म्यूज़िक","म्यूज़िक genres के बारे में सीखना"],"hinglish":["Videos ke liye background music banana","Chhote business ads ke liye jingles banana","Music composition ideas explore karna","Personal entertainment aur fun","Podcast aur YouTube intro music","Music genres ke baare mein seekhna"]}',
  alternatives = ARRAY['udio','mubert','aiva','elevenlabs'],
  hindi_summary = 'Suno AI टेक्स्ट से पूरे गाने बनाता है — vocals, music, lyrics सब AI से। हिंदी और Bollywood स्टाइल में भी। YouTube videos के लिए background music बनाने का सबसे मज़ेदार तरीका।'
WHERE slug = 'suno-ai';

-- ── Udio ──────────────────────────────────────────────────────
UPDATE public.ai_tools SET
  features = '{"en":["High-quality AI music generation","Exceptional audio quality compared to competitors","Custom lyrics with multiple vocal styles","Genre and mood-based music creation","Song extension and variation","Remix existing tracks","Free tier with monthly credits"],"hi":["उच्च-गुणवत्ता AI म्यूज़िक जनरेशन","प्रतिस्पर्धियों की तुलना में असाधारण audio गुणवत्ता","कई vocal styles के साथ Custom lyrics","Genre और mood-based म्यूज़िक क्रिएशन","Song extension और variation","मौजूदा tracks remix करें","Monthly credits के साथ मुफ्त टियर"],"hinglish":["High-quality AI music generation","Competitors ke comparison mein exceptional audio quality","Multiple vocal styles ke saath custom lyrics","Genre aur mood-based music creation","Song extension aur variation","Existing tracks remix karo","Monthly credits ke saath free tier"]}',
  pros = '{"en":["Audio quality often better than Suno","Strong vocal clarity","Good variety of musical styles","Free tier available","Extension feature enables longer songs"],"hi":["Audio गुणवत्ता अक्सर Suno से बेहतर","मजबूत vocal clarity","संगीत शैलियों की अच्छी विविधता","मुफ्त टियर उपलब्ध","Extension फीचर लंबे गाने सक्षम करता है"],"hinglish":["Audio quality aksar Suno se better","Strong vocal clarity","Musical styles ki achhi variety","Free tier available","Extension feature lambe songs enable karta hai"]}',
  cons = '{"en":["Slightly less generous free tier than Suno","Smaller community and fewer tutorials","Commercial rights need paid plan","Hindi/Indian music styles less refined"],"hi":["Suno से थोड़ा कम उदार मुफ्त टियर","छोटा समुदाय और कम ट्यूटोरियल","Commercial rights के लिए paid प्लान जरूरी","हिंदी/भारतीय म्यूज़िक styles कम refined"],"hinglish":["Suno se thoda kam generous free tier","Chhoti community aur kam tutorials","Commercial rights ke liye paid plan zaroori","Hindi/Indian music styles kam refined"]}',
  use_cases = '{"en":["High-quality background music creation","Producing demo tracks for music ideas","Creating theme songs for podcasts","Social media video soundtracks","Music exploration and experimentation","Jingle creation for ads"],"hi":["उच्च-गुणवत्ता बैकग्राउंड म्यूज़िक क्रिएशन","म्यूज़िक ideas के लिए demo tracks बनाना","Podcasts के लिए theme songs बनाना","सोशल मीडिया वीडियो soundtracks","म्यूज़िक exploration और प्रयोग","विज्ञापनों के लिए Jingle क्रिएशन"],"hinglish":["High-quality background music creation","Music ideas ke liye demo tracks banana","Podcasts ke liye theme songs banana","Social media video soundtracks","Music exploration aur experimentation","Ads ke liye jingle creation"]}',
  alternatives = ARRAY['suno-ai','mubert','aiva'],
  hindi_summary = 'Udio Suno AI का एक मजबूत प्रतिद्वंद्वी है — audio quality कई बार बेहतर। Text से professional-sounding songs बनाने के लिए दोनों को try करके compare करें।'
WHERE slug = 'udio';

-- ── Soundraw ──────────────────────────────────────────────────
UPDATE public.ai_tools SET
  features = '{"en":["AI music generation for content creators","Customizable tempo, mood, instruments, length","Royalty-free for commercial use","Genre selection from 20+ categories","Beat and melody customization","Download in MP3 and WAV","YouTube and social media safe"],"hi":["कंटेंट क्रिएटर के लिए AI म्यूज़िक जनरेशन","Customizable tempo, mood, instruments, length","Commercial उपयोग के लिए Royalty-free","20+ categories से Genre selection","Beat और melody कस्टमाइज़ेशन","MP3 और WAV में Download","YouTube और सोशल मीडिया safe"],"hinglish":["Content creators ke liye AI music generation","Customizable tempo, mood, instruments, length","Commercial use ke liye royalty-free","20+ categories se genre selection","Beat aur melody customization","MP3 aur WAV mein download","YouTube aur social media safe"]}',
  pros = '{"en":["Royalty-free commercial use license","Good customization controls","Consistent output quality","Good for YouTubers and video creators","No copyright issues for commercial content"],"hi":["Royalty-free commercial उपयोग लाइसेंस","अच्छे customization controls","सुसंगत आउटपुट गुणवत्ता","YouTubers और वीडियो क्रिएटर के लिए अच्छा","Commercial कंटेंट के लिए कोई copyright समस्या नहीं"],"hinglish":["Royalty-free commercial use license","Achhe customization controls","Consistent output quality","YouTubers aur video creators ke liye achha","Commercial content ke liye koi copyright issues nahi"]}',
  cons = '{"en":["Subscription required for downloads","Less creative than Suno for unique songs","Limited vocal music generation","Interface less intuitive than Suno"],"hi":["Downloads के लिए सब्सक्रिप्शन जरूरी","अनूठे गानों के लिए Suno से कम creative","सीमित vocal म्यूज़िक जनरेशन","Suno से कम सहज इंटरफेस"],"hinglish":["Downloads ke liye subscription zaroori","Unique songs ke liye Suno se kam creative","Limited vocal music generation","Suno se kam intuitive interface"]}',
  use_cases = '{"en":["YouTube video background music","Podcast intro and outro music","Instagram Reels and TikTok soundtracks","Corporate presentation music","Advertising and commercial music","Game and app background music"],"hi":["YouTube वीडियो बैकग्राउंड म्यूज़िक","पॉडकास्ट इंट्रो और आउट्रो म्यूज़िक","Instagram Reels और TikTok soundtracks","Corporate presentation म्यूज़िक","विज्ञापन और commercial म्यूज़िक","Game और app बैकग्राउंड म्यूज़िक"],"hinglish":["YouTube video background music","Podcast intro aur outro music","Instagram Reels aur TikTok soundtracks","Corporate presentation music","Advertising aur commercial music","Game aur app background music"]}',
  alternatives = ARRAY['suno-ai','udio','mubert','aiva'],
  hindi_summary = 'Soundraw YouTube creators के लिए royalty-free background music बनाने का AI tool है। Commercial use के लिए copyright-safe music — हर mood और genre में।'
WHERE slug = 'soundraw';

-- ── AIVA ─────────────────────────────────────────────────────
UPDATE public.ai_tools SET
  features = '{"en":["AI music composition for film and games","Classical, jazz, electronic and cinematic styles","MIDI export for further editing in DAW","Pre-composed score templates","Create custom composition profiles","Royalty-free for most use cases","Free tier with 3 downloads/month"],"hi":["फिल्म और games के लिए AI म्यूज़िक कंपोज़िशन","Classical, jazz, electronic और cinematic styles","DAW में आगे editing के लिए MIDI export","Pre-composed score templates","Custom composition profiles बनाएं","अधिकांश use cases के लिए Royalty-free","3 downloads/माह के साथ मुफ्त टियर"],"hinglish":["Film aur games ke liye AI music composition","Classical, jazz, electronic aur cinematic styles","DAW mein further editing ke liye MIDI export","Pre-composed score templates","Custom composition profiles banao","Zyaadatar use cases ke liye royalty-free","3 downloads/month ke saath free tier"]}',
  pros = '{"en":["MIDI export enables professional post-editing","Good for film, game and background scores","Established and trusted platform","Royalty-free for standard use","Good range of orchestral styles"],"hi":["MIDI export professional post-editing सक्षम करता है","फिल्म, game और बैकग्राउंड scores के लिए अच्छा","स्थापित और भरोसेमंद प्लेटफॉर्म","Standard उपयोग के लिए Royalty-free","Orchestral styles की अच्छी range"],"hinglish":["MIDI export professional post-editing enable karta hai","Film, game aur background scores ke liye achha","Established aur trusted platform","Standard use ke liye royalty-free","Orchestral styles ki achhi range"]}',
  cons = '{"en":["Less creative than Suno for pop/vocal music","Requires music knowledge for MIDI workflow","Free tier very limited","Less suitable for Hindi film music styles"],"hi":["Pop/vocal म्यूज़िक के लिए Suno से कम creative","MIDI वर्कफ्लो के लिए म्यूज़िक ज्ञान जरूरी","मुफ्त टियर बहुत सीमित","हिंदी फिल्म म्यूज़िक styles के लिए कम उपयुक्त"],"hinglish":["Pop/vocal music ke liye Suno se kam creative","MIDI workflow ke liye music knowledge zaroori","Free tier bahut limited","Hindi film music styles ke liye kam suitable"]}',
  use_cases = '{"en":["Film score and background music composition","Video game music creation","Orchestral compositions for productions","Meditation and ambient music","Corporate video soundtracks","Music students learning composition"],"hi":["फिल्म score और बैकग्राउंड म्यूज़िक कंपोज़िशन","Video game म्यूज़िक क्रिएशन","Productions के लिए Orchestral compositions","Meditation और ambient म्यूज़िक","Corporate वीडियो soundtracks","कंपोज़िशन सीखने वाले म्यूज़िक छात्र"],"hinglish":["Film score aur background music composition","Video game music creation","Productions ke liye orchestral compositions","Meditation aur ambient music","Corporate video soundtracks","Composition sikhne wale music students"]}',
  alternatives = ARRAY['suno-ai','soundraw','mubert'],
  hindi_summary = 'AIVA AI से cinematic और orchestral music compose करता है — film, game, और documentary के लिए। MIDI export से professional DAW में और edit कर सकते हैं।'
WHERE slug = 'aiva';

-- ── Mubert ────────────────────────────────────────────────────
UPDATE public.ai_tools SET
  features = '{"en":["AI streaming and generated music for creators","Royalty-free tracks for YouTube and social","Music by mood, activity and duration","API for real-time music generation","Render: generate tracks for specific content","Mubert Studio for custom music","Free tier available"],"hi":["क्रिएटर के लिए AI streaming और generated म्यूज़िक","YouTube और social के लिए Royalty-free tracks","Mood, activity और duration से म्यूज़िक","रियल-टाइम म्यूज़िक जनरेशन के लिए API","Render: विशिष्ट कंटेंट के लिए tracks जनरेट","Custom म्यूज़िक के लिए Mubert Studio","मुफ्त टियर उपलब्ध"],"hinglish":["Creators ke liye AI streaming aur generated music","YouTube aur social ke liye royalty-free tracks","Mood, activity aur duration se music","Real-time music generation ke liye API","Render: specific content ke liye tracks generate","Custom music ke liye Mubert Studio","Free tier available"]}',
  pros = '{"en":["Royalty-free commercial use","Good API for developers building apps","Mood-based generation is intuitive","Streaming mode for continuous background music","Affordable pricing"],"hi":["Royalty-free commercial उपयोग","ऐप बनाने वाले developers के लिए अच्छा API","Mood-based generation सहज है","निरंतर बैकग्राउंड म्यूज़िक के लिए Streaming mode","किफायती कीमत"],"hinglish":["Royalty-free commercial use","Apps bana rahe developers ke liye achha API","Mood-based generation intuitive hai","Continuous background music ke liye streaming mode","Affordable pricing"]}',
  cons = '{"en":["Less musical variety than Suno","Generated music can feel generic","Not for vocal/lyrical content","Limited creativity in outputs"],"hi":["Suno से कम musical विविधता","जनरेटेड म्यूज़िक generic लग सकता है","Vocal/lyrical कंटेंट के लिए नहीं","आउटपुट में सीमित creativity"],"hinglish":["Suno se kam musical variety","Generated music generic lag sakta hai","Vocal/lyrical content ke liye nahi","Outputs mein limited creativity"]}',
  use_cases = '{"en":["Background music for YouTube videos","App and game background audio","Podcast background tracks","Gym and workout playlist music","Meditation app music streams","Retail and café ambient music"],"hi":["YouTube वीडियो के लिए बैकग्राउंड म्यूज़िक","App और game बैकग्राउंड audio","पॉडकास्ट बैकग्राउंड tracks","Gym और workout playlist म्यूज़िक","Meditation app म्यूज़िक streams","Retail और café ambient म्यूज़िक"],"hinglish":["YouTube videos ke liye background music","Apps aur games ke liye background audio","Podcast background tracks","Gym aur workout playlist music","Meditation app music streams","Retail aur café ambient music"]}',
  alternatives = ARRAY['suno-ai','soundraw','aiva'],
  hindi_summary = 'Mubert AI से royalty-free background music generate करता है। YouTube, podcast, app — सभी के लिए mood और duration के हिसाब से perfect music।'
WHERE slug = 'mubert';

-- ── Adobe Podcast ─────────────────────────────────────────────
UPDATE public.ai_tools SET
  features = '{"en":["AI audio enhancement — remove background noise","Mic Check: test audio quality before recording","Record with studio-quality AI processing","Transcription and editing via text","Remove filler words from recordings","Multi-track podcast recording","Free to use with Adobe account"],"hi":["AI audio enhancement — बैकग्राउंड नॉइज़ हटाएं","Mic Check: रिकॉर्ड करने से पहले audio गुणवत्ता test करें","Studio-quality AI processing के साथ रिकॉर्ड करें","टेक्स्ट के ज़रिए Transcription और editing","रिकॉर्डिंग से filler words हटाएं","Multi-track पॉडकास्ट रिकॉर्डिंग","Adobe अकाउंट से मुफ्त उपयोग"],"hinglish":["AI audio enhancement — background noise hatao","Mic Check: record karne se pehle audio quality test karo","Studio-quality AI processing ke saath record karo","Text ke zariye transcription aur editing","Recordings se filler words hatao","Multi-track podcast recording","Adobe account se free use"]}',
  pros = '{"en":["Speech enhancement is remarkably good — turns mediocre audio into studio quality","Completely free with Adobe account","Easy to use for non-technical users","Mic Check helps avoid bad recordings","Adobe integration for Creative Cloud users"],"hi":["Speech enhancement उल्लेखनीय रूप से अच्छा है — साधारण audio को studio quality में बदलता है","Adobe अकाउंट से बिल्कुल मुफ्त","गैर-तकनीकी users के लिए उपयोग में आसान","Mic Check खराब रिकॉर्डिंग से बचाता है","Creative Cloud users के लिए Adobe integration"],"hinglish":["Speech enhancement remarkably achha hai — mediocre audio ko studio quality mein badalta hai","Adobe account se bilkul free","Non-technical users ke liye use mein easy","Mic Check kharab recordings se bachata hai","Creative Cloud users ke liye Adobe integration"]}',
  cons = '{"en":["Processing can take time for long recordings","Limited editing features compared to Descript","Hindi audio enhancement needs improvement","Web-only — no desktop app"],"hi":["लंबी रिकॉर्डिंग के लिए processing में समय लग सकता है","Descript की तुलना में सीमित editing फीचर्स","हिंदी audio enhancement में सुधार जरूरी","केवल Web — कोई desktop ऐप नहीं"],"hinglish":["Lambi recordings ke liye processing mein time lag sakta hai","Descript ke comparison mein limited editing features","Hindi audio enhancement mein improvement zaroori","Web-only — koi desktop app nahi"]}',
  use_cases = '{"en":["Podcast audio quality enhancement","Improving interview recordings made on phone","YouTube video voiceover cleanup","Online meeting audio improvement","Educational video narration cleanup","Removing background noise from home recordings"],"hi":["पॉडकास्ट audio गुणवत्ता enhancement","फोन पर बनाई गई इंटरव्यू रिकॉर्डिंग में सुधार","YouTube वीडियो voiceover cleanup","ऑनलाइन मीटिंग audio सुधार","शैक्षिक वीडियो narration cleanup","घर की रिकॉर्डिंग से बैकग्राउंड नॉइज़ हटाना"],"hinglish":["Podcast audio quality enhancement","Phone pe bani interview recordings improve karna","YouTube video voiceover cleanup","Online meeting audio improve karna","Educational video narration cleanup","Ghar ki recordings se background noise hatana"]}',
  alternatives = ARRAY['descript','elevenlabs','murf-ai'],
  hindi_summary = 'Adobe Podcast AI से आपकी voice recording को studio-quality में बदलता है — बिल्कुल मुफ्त। घर पर record किया हुआ audio professional podcast जैसा बन जाता है।'
WHERE slug = 'adobe-podcast';

-- ── Tidio ─────────────────────────────────────────────────────
UPDATE public.ai_tools SET
  features = '{"en":["AI chatbot for website customer support","Lyro AI: handles 70% of queries automatically","Live chat and chatbot in one platform","Shopify and WooCommerce integration","Visitor tracking and proactive messaging","Email and Messenger integration","Free tier for small businesses"],"hi":["वेबसाइट कस्टमर सपोर्ट के लिए AI chatbot","Lyro AI: 70% queries स्वचालित रूप से handle करता है","एक प्लेटफॉर्म में Live chat और chatbot","Shopify और WooCommerce integration","Visitor tracking और proactive messaging","Email और Messenger integration","छोटे व्यवसायों के लिए मुफ्त टियर"],"hinglish":["Website customer support ke liye AI chatbot","Lyro AI: 70% queries automatically handle karta hai","Ek platform mein live chat aur chatbot","Shopify aur WooCommerce integration","Visitor tracking aur proactive messaging","Email aur Messenger integration","Chhote businesses ke liye free tier"]}',
  pros = '{"en":["Best AI chatbot for e-commerce businesses","Lyro handles common questions automatically","Great Shopify integration for Indian sellers","Affordable compared to Intercom","Easy setup without coding"],"hi":["E-commerce व्यवसायों के लिए सबसे अच्छा AI chatbot","Lyro सामान्य सवाल स्वचालित रूप से handle करता है","भारतीय विक्रेताओं के लिए बेहतरीन Shopify integration","Intercom की तुलना में किफायती","बिना coding के आसान सेटअप"],"hinglish":["E-commerce businesses ke liye best AI chatbot","Lyro common questions automatically handle karta hai","Indian sellers ke liye great Shopify integration","Intercom ke comparison mein affordable","Bina coding ke easy setup"]}',
  cons = '{"en":["Lyro AI requires paid plan for full use","Hindi language chatbot support limited","Free tier limited to 50 conversations/month","Less enterprise features than Intercom"],"hi":["Lyro AI के पूर्ण उपयोग के लिए paid प्लान जरूरी","हिंदी भाषा chatbot समर्थन सीमित","मुफ्त टियर 50 conversations/माह तक सीमित","Intercom से कम एंटरप्राइज़ फीचर्स"],"hinglish":["Lyro AI ke full use ke liye paid plan zaroori","Hindi language chatbot support limited","Free tier 50 conversations/month tak limited","Intercom se kam enterprise features"]}',
  use_cases = '{"en":["E-commerce website customer support","Shopify store order and shipping queries","Lead capture on business websites","Small business 24/7 customer service","Product recommendation chatbot","Returning customer support automation"],"hi":["E-commerce वेबसाइट कस्टमर सपोर्ट","Shopify स्टोर ऑर्डर और शिपिंग queries","व्यापार वेबसाइट पर Lead capture","छोटे व्यापार 24/7 कस्टमर सर्विस","प्रोडक्ट recommendation chatbot","वापसी कस्टमर सपोर्ट automation"],"hinglish":["E-commerce website customer support","Shopify store order aur shipping queries","Business websites pe lead capture","Chhote businesses ke liye 24/7 customer service","Product recommendation chatbot","Returning customer support automation"]}',
  alternatives = ARRAY['intercom','hubspot-ai','zoho-zia'],
  hindi_summary = 'Tidio छोटे e-commerce businesses के लिए AI chatbot है। Shopify के साथ integrate करो, Lyro AI 70% customer queries खुद handle करेगा — 24/7 without any staff।'
WHERE slug = 'tidio';

-- ── Vyapar ────────────────────────────────────────────────────
UPDATE public.ai_tools SET
  features = '{"en":["GST billing and accounting for Indian businesses","AI-powered insights and reports","Inventory management with low stock alerts","Mobile app for on-the-go billing","WhatsApp invoice sharing","Bank statement reconciliation","Hindi and English interface"],"hi":["भारतीय व्यवसायों के लिए GST billing और accounting","AI-पावर्ड insights और रिपोर्ट","Low stock alerts के साथ Inventory management","चलते-फिरते billing के लिए Mobile app","WhatsApp invoice sharing","Bank statement reconciliation","हिंदी और अंग्रेजी इंटरफेस"],"hinglish":["Indian businesses ke liye GST billing aur accounting","AI-powered insights aur reports","Low stock alerts ke saath inventory management","On-the-go billing ke liye mobile app","WhatsApp invoice sharing","Bank statement reconciliation","Hindi aur English interface"]}',
  pros = '{"en":["Made for India — GST-compliant from day one","Hindi interface makes it accessible to all","WhatsApp invoice sharing is very practical","Affordable for small and medium businesses","Works offline — no constant internet needed"],"hi":["भारत के लिए बना — पहले दिन से GST-compliant","हिंदी इंटरफेस इसे सभी के लिए accessible बनाता है","WhatsApp invoice sharing बहुत practical है","छोटे और मध्यम व्यवसायों के लिए किफायती","Offline काम करता है — निरंतर इंटरनेट की जरूरत नहीं"],"hinglish":["India ke liye banaya — day one se GST-compliant","Hindi interface ise sabke liye accessible banata hai","WhatsApp invoice sharing bahut practical hai","Chhote aur medium businesses ke liye affordable","Offline kaam karta hai — constant internet ki zaroorat nahi"]}',
  cons = '{"en":["AI features less advanced than international tools","Limited integrations with other software","Customer support can be slow","Less suitable for large enterprises"],"hi":["AI फीचर्स अंतर्राष्ट्रीय टूल से कम उन्नत","अन्य सॉफ्टवेयर के साथ सीमित integrations","ग्राहक समर्थन धीमा हो सकता है","बड़े enterprises के लिए कम उपयुक्त"],"hinglish":["AI features international tools se kam advanced","Dusre software ke saath limited integrations","Customer support slow ho sakta hai","Bade enterprises ke liye kam suitable"]}',
  use_cases = '{"en":["GST billing for Indian retail shops","Kirana store inventory management","Freelancer and service provider invoicing","Wholesale trading business accounting","Restaurant and food business billing","Small manufacturer production tracking"],"hi":["भारतीय retail दुकानों के लिए GST billing","किराना स्टोर inventory management","Freelancer और service provider invoicing","थोक व्यापार accounting","रेस्तरां और food business billing","छोटे manufacturer प्रोडक्शन ट्रैकिंग"],"hinglish":["Indian retail shops ke liye GST billing","Kirana stores ke liye inventory management","Freelancers aur service providers ke liye invoicing","Wholesale trading accounting","Restaurants aur food businesses ke liye billing","Chhote manufacturers ke liye production tracking"]}',
  alternatives = ARRAY['zoho-zia','hubspot-ai'],
  hindi_summary = 'Vyapar भारत के छोटे व्यापारियों के लिए GST billing और accounting ऐप है। हिंदी में, WhatsApp से invoice भेजो, offline भी काम करे — किराना से लेकर manufacturing तक सबके लिए।'
WHERE slug = 'vyapar';

-- ── Predis.ai ─────────────────────────────────────────────────
UPDATE public.ai_tools SET
  features = '{"en":["AI social media content creation","Generate posts, carousels and videos from text","Competitor analysis and benchmarking","Content calendar and scheduling","Brand kit with colors and fonts","Multi-platform: Instagram, Facebook, LinkedIn, Twitter","Hindi content generation support"],"hi":["AI सोशल मीडिया कंटेंट क्रिएशन","टेक्स्ट से posts, carousels और videos जनरेट करें","Competitor analysis और benchmarking","कंटेंट calendar और scheduling","रंग और फ़ॉन्ट के साथ Brand kit","Multi-platform: Instagram, Facebook, LinkedIn, Twitter","हिंदी कंटेंट जनरेशन समर्थन"],"hinglish":["AI social media content creation","Text se posts, carousels aur videos generate karo","Competitor analysis aur benchmarking","Content calendar aur scheduling","Colors aur fonts ke saath brand kit","Multi-platform: Instagram, Facebook, LinkedIn, Twitter","Hindi content generation support"]}',
  pros = '{"en":["Made in India — good Hindi support","All-in-one social media creation and scheduling","Competitor tracking is a unique feature","Affordable compared to Buffer/Hootsuite","Good for small business social media management"],"hi":["Made in India — अच्छा हिंदी समर्थन","All-in-one सोशल मीडिया क्रिएशन और scheduling","Competitor tracking एक अनूठा फीचर है","Buffer/Hootsuite की तुलना में किफायती","छोटे व्यापार सोशल मीडिया management के लिए अच्छा"],"hinglish":["Made in India — achha Hindi support","All-in-one social media creation aur scheduling","Competitor tracking ek unique feature hai","Buffer/Hootsuite ke comparison mein affordable","Chhote business social media management ke liye achha"]}',
  cons = '{"en":["AI content quality needs improvement for Hindi","Limited template variety","Free tier very restricted","Less powerful than dedicated tools like Canva for design"],"hi":["हिंदी के लिए AI कंटेंट गुणवत्ता में सुधार जरूरी","सीमित template विविधता","मुफ्त टियर बहुत प्रतिबंधित","डिज़ाइन के लिए Canva जैसे dedicated टूल से कम शक्तिशाली"],"hinglish":["Hindi ke liye AI content quality mein improvement zaroori","Limited template variety","Free tier bahut restricted","Design ke liye Canva jaise dedicated tools se kam powerful"]}',
  use_cases = '{"en":["Small business social media management","Instagram and Facebook post creation in Hindi","Competitor social media monitoring","Scheduled content for brand consistency","Restaurant and retail social media","Startup brand building on social media"],"hi":["छोटे व्यापार सोशल मीडिया management","हिंदी में Instagram और Facebook पोस्ट क्रिएशन","Competitor सोशल मीडिया monitoring","ब्रांड consistency के लिए Scheduled कंटेंट","रेस्तरां और retail सोशल मीडिया","सोशल मीडिया पर Startup ब्रांड building"],"hinglish":["Chhote businesses ke liye social media management","Hindi mein Instagram aur Facebook post creation","Competitor social media monitoring","Brand consistency ke liye scheduled content","Restaurants aur retail ke liye social media","Social media pe startup brand building"]}',
  alternatives = ARRAY['canva-ai-magic-studio','buffer','hootsuite-owlywriter-ai'],
  hindi_summary = 'Predis.ai एक भारतीय AI social media tool है जो Hindi में social media posts, carousels और videos बनाता है। छोटे businesses के लिए social media को AI से manage करने का देसी solution।'
WHERE slug = 'predis-ai';

-- ── Khan Academy (Khanmigo) ───────────────────────────────────
UPDATE public.ai_tools SET
  features = '{"en":["AI tutoring across all school subjects","Socratic method — asks questions instead of giving answers","Personalized learning pace","Available on Khan Academy platform","Writing coach and essay feedback","SAT prep with AI guidance","Free with Khan Academy account"],"hi":["सभी स्कूल विषयों में AI tutoring","Socratic method — जवाब देने की बजाय सवाल पूछता है","व्यक्तिगत सीखने की गति","Khan Academy प्लेटफॉर्म पर उपलब्ध","Writing coach और essay feedback","AI guidance के साथ SAT prep","Khan Academy अकाउंट से मुफ्त"],"hinglish":["Sabhi school subjects mein AI tutoring","Socratic method — answers dene ki bajay sawaal poochta hai","Personalized learning pace","Khan Academy platform pe available","Writing coach aur essay feedback","AI guidance ke saath SAT prep","Khan Academy account se free"]}',
  pros = '{"en":["Free and accessible to all students","Socratic teaching method builds deep understanding","Trusted educational platform","Covers all major school subjects","No commercial agenda — educational mission"],"hi":["सभी छात्रों के लिए मुफ्त और accessible","Socratic शिक्षण method गहरी समझ बनाता है","भरोसेमंद शैक्षणिक प्लेटफॉर्म","सभी प्रमुख स्कूल विषयों को cover करता है","कोई commercial agenda नहीं — शैक्षिक मिशन"],"hinglish":["Sabhi students ke liye free aur accessible","Socratic teaching method deep understanding banata hai","Trusted educational platform","Sabhi major school subjects cover karta hai","Koi commercial agenda nahi — educational mission"]}',
  cons = '{"en":["Limited to curriculum content — not general AI","Hindi medium curriculum not fully covered","Khanmigo specific AI has limited access","Less suitable for competitive exam prep (JEE, NEET)"],"hi":["Curriculum कंटेंट तक सीमित — general AI नहीं","हिंदी माध्यम curriculum पूरी तरह cover नहीं","Khanmigo specific AI की सीमित पहुंच","Competitive exam prep के लिए कम उपयुक्त (JEE, NEET)"],"hinglish":["Curriculum content tak limited — general AI nahi","Hindi medium curriculum fully covered nahi","Khanmigo specific AI ki limited access","Competitive exams ke liye kam suitable (JEE, NEET)"]}',
  use_cases = '{"en":["School math and science tutoring","Essay writing improvement","SAT and competitive exam preparation","Self-paced learning for students","Homework help and concept explanation","Teachers getting AI teaching assistance"],"hi":["स्कूल math और science tutoring","Essay लेखन सुधार","SAT और competitive exam preparation","छात्रों के लिए self-paced सीखना","Homework help और concept explanation","AI शिक्षण सहायता प्राप्त करने वाले शिक्षक"],"hinglish":["School math aur science tutoring","Essay writing improvement","SAT aur competitive exam preparation","Students ke liye self-paced learning","Homework help aur concept explanation","AI teaching assistance paane wale teachers"]}',
  alternatives = ARRAY['chatgpt','photomath','wolfram-alpha','socratic'],
  hindi_summary = 'Khanmigo Khan Academy का AI tutor है जो Socratic method से पढ़ाता है — जवाब नहीं देता, सोचना सिखाता है। स्कूल के सभी विषयों के लिए मुफ्त AI शिक्षक।'
WHERE slug = 'khanmigo';

-- ── Photomath ─────────────────────────────────────────────────
UPDATE public.ai_tools SET
  features = '{"en":["Scan and solve math problems with camera","Step-by-step solution explanations","Covers arithmetic to calculus","Graph plotting and visualization","Word problem solving","Scientific calculator features","Free with optional subscription for detailed steps"],"hi":["कैमरे से math problems scan करके solve करें","Step-by-step solution explanations","Arithmetic से calculus तक cover करता है","Graph plotting और visualization","Word problem solving","Scientific calculator फीचर्स","Detailed steps के लिए optional subscription के साथ मुफ्त"],"hinglish":["Camera se math problems scan karke solve karo","Step-by-step solution explanations","Arithmetic se calculus tak cover karta hai","Graph plotting aur visualization","Word problem solving","Scientific calculator features","Detailed steps ke liye optional subscription ke saath free"]}',
  pros = '{"en":["Best math solving app for students worldwide","Camera scanning is incredibly convenient","Step-by-step explanations help learning","Covers all school and college math","Free for basic use"],"hi":["दुनिया भर के छात्रों के लिए सबसे अच्छा math solving app","Camera scanning अविश्वसनीय रूप से सुविधाजनक है","Step-by-step explanations सीखने में मदद करती हैं","सभी स्कूल और कॉलेज math cover करता है","Basic उपयोग के लिए मुफ्त"],"hinglish":["Duniya bhar ke students ke liye best math solving app","Camera scanning incredibly convenient hai","Step-by-step explanations seekhne mein madad karti hain","Sabhi school aur college math cover karta hai","Basic use ke liye free"]}',
  cons = '{"en":["Can enable cheating without learning","Detailed steps require paid subscription","Handwritten problem recognition not always accurate","Hindi language explanations limited"],"hi":["सीखे बिना cheating सक्षम कर सकता है","Detailed steps के लिए paid सब्सक्रिप्शन जरूरी","हस्तलिखित problem पहचान हमेशा सटीक नहीं","हिंदी भाषा explanations सीमित"],"hinglish":["Seekhe bina cheating enable kar sakta hai","Detailed steps ke liye paid subscription zaroori","Handwritten problem recognition hamesha accurate nahi","Hindi language explanations limited"]}',
  use_cases = '{"en":["School and college math homework","Understanding step-by-step solutions","Exam preparation and practice","Parent helping child with math","Self-study for weak math students","Quick calculation verification"],"hi":["स्कूल और कॉलेज math homework","Step-by-step solutions समझना","परीक्षा तैयारी और अभ्यास","बच्चे की math में मदद करने वाले माता-पिता","कमज़ोर math छात्रों के लिए self-study","त्वरित calculation सत्यापन"],"hinglish":["School aur college math homework","Step-by-step solutions samajhna","Exam preparation aur practice","Bachche ki math mein madad karne wale parents","Weak math students ke liye self-study","Quick calculation verification"]}',
  alternatives = ARRAY['wolfram-alpha','chatgpt','socratic','khanmigo'],
  hindi_summary = 'Photomath भारत में सबसे पॉपुलर math solving app है। कैमरे से photo लो, AI step-by-step solution देगा। Class 6 से JEE तक — सब cover।'
WHERE slug = 'photomath';

-- ── Wolfram Alpha ─────────────────────────────────────────────
UPDATE public.ai_tools SET
  features = '{"en":["Computational knowledge engine","Solves complex math, physics, chemistry problems","Wolfram|Alpha Pro for step-by-step solutions","Data analysis and visualization","Natural language query input","Integration with ChatGPT Plus","Science, engineering, finance calculations"],"hi":["Computational knowledge engine","जटिल math, physics, chemistry problems solve करता है","Step-by-step solutions के लिए Wolfram|Alpha Pro","Data analysis और visualization","Natural language query input","ChatGPT Plus के साथ integration","Science, engineering, finance calculations"],"hinglish":["Computational knowledge engine","Complex math, physics, chemistry problems solve karta hai","Step-by-step solutions ke liye Wolfram|Alpha Pro","Data analysis aur visualization","Natural language query input","ChatGPT Plus ke saath integration","Science, engineering, finance calculations"]}',
  pros = '{"en":["Unmatched accuracy for math and science","30+ years of curated knowledge","Trusted by researchers and academics worldwide","ChatGPT Plus integration extends its reach","Covers topics other AIs cannot handle accurately"],"hi":["Math और science के लिए बेमिसाल सटीकता","30+ वर्षों का curated ज्ञान","दुनिया भर के शोधकर्ताओं और शिक्षाविदों द्वारा भरोसेमंद","ChatGPT Plus integration इसकी पहुंच बढ़ाती है","वो विषय cover करता है जो अन्य AIs सटीकता से नहीं कर सकते"],"hinglish":["Math aur science ke liye beemisaal accuracy","30+ saalon ka curated knowledge","Duniya bhar ke researchers aur academics dwara trusted","ChatGPT Plus integration iske reach badhati hai","Wo topics cover karta hai jo other AIs accurately nahi kar sakte"]}',
  cons = '{"en":["Not conversational — strict query format needed","Free version has limited detail","Pro subscription can be expensive for students","Not useful for non-scientific queries"],"hi":["Conversational नहीं — सख्त query format जरूरी","मुफ्त संस्करण में सीमित detail","Pro सब्सक्रिप्शन छात्रों के लिए महंगी हो सकती है","गैर-वैज्ञानिक queries के लिए उपयोगी नहीं"],"hinglish":["Conversational nahi — strict query format zaroori","Free version mein limited detail","Pro subscription students ke liye mehanga ho sakta hai","Non-scientific queries ke liye useful nahi"]}',
  use_cases = '{"en":["Engineering and science calculations","JEE and NEET exam problem solving","Data analysis and statistics","Finance and investment calculations","Research and academic work","Verifying mathematical solutions"],"hi":["Engineering और science calculations","JEE और NEET परीक्षा problem solving","Data analysis और statistics","Finance और investment calculations","रिसर्च और अकादमिक काम","Mathematical solutions सत्यापित करना"],"hinglish":["Engineering aur science calculations","JEE aur NEET exam problem solving","Data analysis aur statistics","Finance aur investment calculations","Research aur academic work","Mathematical solutions verify karna"]}',
  alternatives = ARRAY['chatgpt','photomath','khanmigo'],
  hindi_summary = 'Wolfram Alpha math, science, और engineering के लिए सबसे accurate computational tool है। JEE और NEET की तैयारी में complex problems solve करने के लिए indispensable।'
WHERE slug = 'wolfram-alpha';

-- ── Socratic by Google ─────────────────────────────────────────
UPDATE public.ai_tools SET
  features = '{"en":["Take a photo of a question — get instant AI explanation","Covers all school subjects","Step-by-step explanations with visual aids","YouTube video recommendations for topics","Free — built by Google","iOS and Android apps","Supports homework from Class 5 to college"],"hi":["सवाल की फोटो लो — तत्काल AI explanation पाओ","सभी स्कूल विषयों को cover करता है","Visual aids के साथ Step-by-step explanations","विषयों के लिए YouTube वीडियो सिफारिशें","मुफ्त — Google द्वारा बना","iOS और Android apps","Class 5 से कॉलेज तक homework समर्थन"],"hinglish":["Question ki photo lo — instant AI explanation pao","Sabhi school subjects cover karta hai","Visual aids ke saath step-by-step explanations","Topics ke liye YouTube video recommendations","Free — Google ne banaya","iOS aur Android apps","Class 5 se college tak homework support"]}',
  pros = '{"en":["Completely free — no subscription","Google''s trusted technology","Great visual explanations","Covers all school subjects","YouTube integration helps deeper learning"],"hi":["बिल्कुल मुफ्त — कोई सब्सक्रिप्शन नहीं","Google की भरोसेमंद technology","बेहतरीन visual explanations","सभी स्कूल विषयों को cover करता है","YouTube integration गहरी learning में मदद करता है"],"hinglish":["Bilkul free — koi subscription nahi","Google ki trusted technology","Great visual explanations","Sabhi school subjects cover karta hai","YouTube integration deeper learning mein madad karta hai"]}',
  cons = '{"en":["Hindi medium questions not well supported","Less detailed than Photomath for pure math","No AI conversation or follow-up questions","Works best for standard textbook problems"],"hi":["हिंदी माध्यम के सवाल अच्छे से supported नहीं","Pure math के लिए Photomath से कम detailed","कोई AI conversation या follow-up सवाल नहीं","Standard textbook problems के लिए सबसे अच्छा काम करता है"],"hinglish":["Hindi medium questions achhe se supported nahi","Pure math ke liye Photomath se kam detailed","Koi AI conversation ya follow-up questions nahi","Standard textbook problems ke liye best kaam karta hai"]}',
  use_cases = '{"en":["School homework help across subjects","Quick concept explanations","Science and history question lookup","Formula and equation understanding","Parent helping child with homework","Students without access to tutors"],"hi":["सभी विषयों में स्कूल homework help","त्वरित concept explanations","Science और history सवाल lookup","Formula और equation समझना","बच्चे की homework में मदद करने वाले माता-पिता","Tutors तक पहुंच के बिना छात्र"],"hinglish":["Sabhi subjects mein school homework help","Quick concept explanations","Science aur history questions lookup","Formula aur equations samajhna","Bachche ki homework mein madad karne wale parents","Tutors ke bina students"]}',
  alternatives = ARRAY['photomath','khanmigo','chatgpt','wolfram-alpha'],
  hindi_summary = 'Socratic Google का मुफ्त homework helper app है। फोटो खींचो, AI तुरंत visual explanation देगा। Class 5 से College तक — math, science, history सब।'
WHERE slug = 'socratic';

-- ── Consensus ─────────────────────────────────────────────────
UPDATE public.ai_tools SET
  features = '{"en":["AI-powered academic paper search engine","Answers backed by peer-reviewed research","Consensus Meter: shows agreement among studies","GPT-4 powered summaries","Filter by journal, year, study type","Best for science, health and social research","Free tier available"],"hi":["AI-पावर्ड अकादमिक पेपर सर्च इंजन","Peer-reviewed research द्वारा समर्थित जवाब","Consensus Meter: studies के बीच agreement दिखाता है","GPT-4 powered summaries","Journal, year, study type से filter करें","Science, health और social research के लिए सबसे अच्छा","मुफ्त टियर उपलब्ध"],"hinglish":["AI-powered academic paper search engine","Peer-reviewed research se backed answers","Consensus Meter: studies ke beech agreement dikhata hai","GPT-4 powered summaries","Journal, year, study type se filter karo","Science, health aur social research ke liye best","Free tier available"]}',
  pros = '{"en":["Answers grounded in scientific literature","Consensus Meter is a unique and valuable feature","Great for medical, health and research questions","Reduces misinformation by citing peer-reviewed sources","Free tier is quite useful"],"hi":["वैज्ञानिक साहित्य में आधारित जवाब","Consensus Meter अनूठा और मूल्यवान फीचर है","Medical, health और research सवालों के लिए बेहतरीन","Peer-reviewed sources cite करके misinformation कम करता है","मुफ्त टियर काफी उपयोगी है"],"hinglish":["Scientific literature mein grounded answers","Consensus Meter unique aur valuable feature hai","Medical, health aur research questions ke liye great","Peer-reviewed sources cite karke misinformation kam karta hai","Free tier kaafi useful hai"]}',
  cons = '{"en":["Primarily covers English-language research","Paid subscription for full access","Less useful for non-scientific topics","Hindi/Indian research poorly represented"],"hi":["मुख्य रूप से अंग्रेजी-भाषा research cover करता है","पूर्ण पहुंच के लिए paid सब्सक्रिप्शन","गैर-वैज्ञानिक विषयों के लिए कम उपयोगी","हिंदी/भारतीय research कम represent"],"hinglish":["Mainly English-language research cover karta hai","Full access ke liye paid subscription","Non-scientific topics ke liye kam useful","Hindi/Indian research poorly represented"]}',
  use_cases = '{"en":["Medical and health research questions","Academic literature review","Evidence-based decision making","Science journalism and fact-checking","PhD and Masters research","Debunking health myths with evidence"],"hi":["Medical और health research सवाल","अकादमिक literature review","Evidence-based decision making","Science journalism और fact-checking","PhD और Masters research","Evidence के साथ health myths debunk करना"],"hinglish":["Medical aur health research questions","Academic literature review","Evidence-based decision making","Science journalism aur fact-checking","PhD aur Masters research","Evidence ke saath health myths debunk karna"]}',
  alternatives = ARRAY['perplexity-ai','elicit','notebooklm','chatgpt'],
  hindi_summary = 'Consensus AI से scientific research papers को search करता है और evidence-backed answers देता है। Medical, health, और science questions के लिए — सिर्फ peer-reviewed research पर based।'
WHERE slug = 'consensus';

-- ── Elicit ────────────────────────────────────────────────────
UPDATE public.ai_tools SET
  features = '{"en":["AI research assistant for academic papers","Extract data from multiple papers at once","Summarize research findings","Literature review automation","Find papers related to a thesis","Identify research gaps","Free tier with limited papers/month"],"hi":["अकादमिक पेपर के लिए AI research असिस्टेंट","एक साथ कई papers से data extract करें","Research findings का सारांश","Literature review automation","Thesis से संबंधित papers ढूंढें","Research gaps पहचानें","Limited papers/माह के साथ मुफ्त टियर"],"hinglish":["Academic papers ke liye AI research assistant","Ek saath multiple papers se data extract karo","Research findings summarize karo","Literature review automation","Thesis se related papers dhundho","Research gaps identify karo","Limited papers/month ke saath free tier"]}',
  pros = '{"en":["Purpose-built for research literature review","Data extraction across multiple papers is powerful","Saves weeks of manual literature review time","Good for PhD students and researchers","Scientific precision in summaries"],"hi":["Research literature review के लिए खास बना","कई papers में data extraction शक्तिशाली है","मैन्युअल literature review में हफ्तों बचाता है","PhD छात्रों और शोधकर्ताओं के लिए अच्छा","Summaries में वैज्ञानिक सटीकता"],"hinglish":["Research literature review ke liye specially banaya","Multiple papers mein data extraction powerful hai","Manual literature review mein hafton bachata hai","PhD students aur researchers ke liye achha","Summaries mein scientific precision"]}',
  cons = '{"en":["Only useful for academic research context","Free tier limits number of papers","Hindi/Indian academic papers not well indexed","Requires familiarity with research methodology"],"hi":["केवल अकादमिक research context के लिए उपयोगी","मुफ्त टियर papers की संख्या सीमित करता है","हिंदी/भारतीय अकादमिक papers अच्छे से indexed नहीं","Research methodology की परिचितता जरूरी"],"hinglish":["Sirf academic research context ke liye useful","Free tier papers ki sankhya limit karta hai","Hindi/Indian academic papers achhe se indexed nahi","Research methodology ki familiarity zaroori"]}',
  use_cases = '{"en":["PhD literature review","Systematic review and meta-analysis","Grant proposal background research","Research paper writing support","Competitive intelligence in R&D","Science policy research"],"hi":["PhD literature review","Systematic review और meta-analysis","Grant proposal background research","Research paper writing support","R&D में competitive intelligence","Science policy research"],"hinglish":["PhD literature review","Systematic review aur meta-analysis","Grant proposal background research","Research paper writing support","R&D mein competitive intelligence","Science policy research"]}',
  alternatives = ARRAY['consensus','perplexity-ai','notebooklm','jenni-ai'],
  hindi_summary = 'Elicit PhD और research students के लिए AI literature review assistant है। कई research papers से एक साथ data निकालो और synthesize करो — हफ्तों का काम घंटों में।'
WHERE slug = 'elicit';

-- ── Julius AI ─────────────────────────────────────────────────
UPDATE public.ai_tools SET
  features = '{"en":["AI data analyst — chat with your data","Upload CSV, Excel and connect databases","Auto-generates charts and visualizations","Python and R code execution","Statistical analysis and modeling","Export reports and charts","Free tier available"],"hi":["AI data analyst — अपने data से चैट करें","CSV, Excel अपलोड करें और databases connect करें","Charts और visualizations स्वचालित रूप से जनरेट करें","Python और R code execution","Statistical analysis और modeling","Reports और charts export करें","मुफ्त टियर उपलब्ध"],"hinglish":["AI data analyst — apne data se chat karo","CSV, Excel upload karo aur databases connect karo","Charts aur visualizations automatically generate karo","Python aur R code execution","Statistical analysis aur modeling","Reports aur charts export karo","Free tier available"]}',
  pros = '{"en":["No coding needed for data analysis","Auto-generates visualizations from data","Runs Python/R code in background","Great for business analysts and students","Faster than writing pandas/matplotlib manually"],"hi":["Data analysis के लिए coding की जरूरत नहीं","Data से visualizations स्वचालित रूप से जनरेट करता है","Background में Python/R कोड run करता है","Business analysts और छात्रों के लिए बेहतरीन","मैन्युअल pandas/matplotlib लिखने से तेज़"],"hinglish":["Data analysis ke liye coding ki zaroorat nahi","Data se visualizations automatically generate karta hai","Background mein Python/R code run karta hai","Business analysts aur students ke liye great","Manual pandas/matplotlib likhne se fast"]}',
  cons = '{"en":["Free tier has limited uploads","Complex statistical analysis may need verification","Less powerful than dedicated BI tools for enterprise","Privacy concerns for sensitive business data"],"hi":["मुफ्त टियर में सीमित uploads","जटिल statistical analysis को सत्यापन की जरूरत हो सकती है","एंटरप्राइज़ के लिए dedicated BI टूल से कम शक्तिशाली","Sensitive business data के लिए गोपनीयता चिंताएं"],"hinglish":["Free tier mein limited uploads","Complex statistical analysis ko verification ki zaroorat ho sakti hai","Enterprise ke liye dedicated BI tools se kam powerful","Sensitive business data ke liye privacy concerns"]}',
  use_cases = '{"en":["Business sales data analysis","Student data science projects","Market research data exploration","Financial data visualization","Survey response analysis","E-commerce sales trend analysis"],"hi":["Business sales data analysis","छात्र data science projects","Market research data exploration","Financial data visualization","Survey response analysis","E-commerce sales trend analysis"],"hinglish":["Business sales data analysis","Student data science projects","Market research data exploration","Financial data visualization","Survey response analysis","E-commerce sales trend analysis"]}',
  alternatives = ARRAY['chatgpt','rows-ai','polymer'],
  hindi_summary = 'Julius AI आपके CSV या Excel data से सवाल पूछने देता है — बिना coding के charts, analysis, insights मिलते हैं। Business analysts और data science students के लिए।'
WHERE slug = 'julius-ai';
"""

with open(path, 'a', encoding='utf-8') as f:
    f.write(sql)

print("Productivity + music + business + education + data tools appended.")
