# -*- coding: utf-8 -*-
"""Appends coding tools to 0011 migration."""

path = r'c:\p\p\Project\AITools\aihkya\supabase\migrations\0011_tool_content_seed_remaining.sql'

sql = """
-- ── Cursor ────────────────────────────────────────────────────
UPDATE public.ai_tools SET
  features = '{"en":["AI code editor built on VS Code","Tab: AI auto-completes entire functions","Chat with your codebase context","Multi-file edits with one instruction","Composer: autonomous code generation agent","Supports all languages and frameworks","Works with your existing VS Code extensions"],"hi":["VS Code पर बना AI कोड एडिटर","Tab: AI पूरे फंक्शन ऑटो-कम्पलीट करता है","अपने codebase context के साथ चैट","एक निर्देश से multi-file edits","Composer: स्वायत्त कोड जनरेशन एजेंट","सभी भाषाओं और फ्रेमवर्क के साथ काम करता है","आपके मौजूदा VS Code extensions के साथ काम करता है"],"hinglish":["VS Code pe banaya AI code editor","Tab: AI poore functions auto-complete karta hai","Apne codebase context ke saath chat","Ek instruction se multi-file edits","Composer: autonomous code generation agent","Sabhi languages aur frameworks ke saath kaam karta hai","Aapke existing VS Code extensions ke saath kaam karta hai"]}',
  pros = '{"en":["Best AI coding experience available today","Understands your entire codebase context","Multi-file edits are a massive productivity boost","Composer agent can build features autonomously","Free tier is usable for individual developers"],"hi":["आज उपलब्ध सबसे अच्छा AI कोडिंग अनुभव","आपके पूरे codebase context को समझता है","Multi-file edits एक बड़ी उत्पादकता बूस्ट है","Composer एजेंट स्वायत्त रूप से फीचर बना सकता है","Individual developers के लिए मुफ्त टियर उपयोगी है"],"hinglish":["Aaj available best AI coding experience","Aapke poore codebase context ko samajhta hai","Multi-file edits ek badi productivity boost hai","Composer agent autonomously features bana sakta hai","Individual developers ke liye free tier usable hai"]}',
  cons = '{"en":["Subscription required for full power ($20/month)","Can suggest incorrect code confidently","Privacy concerns for proprietary codebases","Requires good internet connection"],"hi":["पूर्ण शक्ति के लिए सब्सक्रिप्शन जरूरी ($20/माह)","आत्मविश्वास से गलत कोड सुझा सकता है","मालिकाना codebases के लिए गोपनीयता चिंताएं","अच्छे इंटरनेट कनेक्शन की जरूरत"],"hinglish":["Full power ke liye subscription zaroori ($20/month)","Confidently galat code suggest kar sakta hai","Proprietary codebases ke liye privacy concerns","Achhe internet connection ki zaroorat"]}',
  use_cases = '{"en":["Full-stack web development","Refactoring large codebases","Building features from natural language descriptions","Code review and debugging assistance","Learning new frameworks and languages","Rapid prototyping for startups"],"hi":["Full-stack वेब डेवलपमेंट","बड़े codebases को refactor करना","प्राकृतिक भाषा विवरण से फीचर बनाना","कोड समीक्षा और debugging सहायता","नए फ्रेमवर्क और भाषाएं सीखना","स्टार्टअप के लिए रैपिड प्रोटोटाइपिंग"],"hinglish":["Full-stack web development","Bade codebases ko refactor karna","Natural language descriptions se features banana","Code review aur debugging assistance","Naye frameworks aur languages seekhna","Startups ke liye rapid prototyping"]}',
  alternatives = ARRAY['github-copilot','windsurf','codeium','tabnine'],
  hindi_summary = 'Cursor सबसे अच्छा AI कोड एडिटर है जो पूरे codebase को समझता है। एक निर्देश से कई फाइलें बदलना, फीचर बनाना — developers की productivity कई गुना बढ़ जाती है।'
WHERE slug = 'cursor';

-- ── Tabnine ───────────────────────────────────────────────────
UPDATE public.ai_tools SET
  features = '{"en":["AI code completion in all major IDEs","Privacy mode — code never leaves your machine","On-premise deployment for enterprises","Team learning from your codebase patterns","Supports 80+ programming languages","Personalized suggestions from team code","Free tier available"],"hi":["सभी प्रमुख IDEs में AI कोड कम्पलीशन","Privacy mode — कोड कभी आपकी मशीन नहीं छोड़ता","एंटरप्राइज़ के लिए On-premise deployment","आपके codebase पैटर्न से टीम लर्निंग","80+ प्रोग्रामिंग भाषाओं का समर्थन","टीम कोड से व्यक्तिगत सुझाव","मुफ्त टियर उपलब्ध"],"hinglish":["Sabhi major IDEs mein AI code completion","Privacy mode — code kabhi aapki machine nahi chodta","Enterprises ke liye on-premise deployment","Aapke codebase patterns se team learning","80+ programming languages support","Team code se personalized suggestions","Free tier available"]}',
  pros = '{"en":["Best privacy-focused AI coding assistant","On-premise option for enterprises","Works in all popular IDEs","Team-level code learning improves suggestions","Good free tier for individuals"],"hi":["सबसे अच्छा privacy-focused AI कोडिंग असिस्टेंट","एंटरप्राइज़ के लिए On-premise विकल्प","सभी लोकप्रिय IDEs में काम करता है","टीम-स्तर कोड लर्निंग सुझाव सुधारती है","व्यक्तियों के लिए अच्छा मुफ्त टियर"],"hinglish":["Best privacy-focused AI coding assistant","Enterprises ke liye on-premise option","Sabhi popular IDEs mein kaam karta hai","Team-level code learning suggestions improve karti hai","Individuals ke liye achha free tier"]}',
  cons = '{"en":["Less impressive than Cursor or GitHub Copilot for chat","Older AI models compared to competitors","Enterprise pricing can be high","Less context-aware than newer tools"],"hi":["चैट के लिए Cursor या GitHub Copilot से कम प्रभावशाली","प्रतिस्पर्धियों की तुलना में पुराने AI मॉडल","एंटरप्राइज़ कीमत अधिक हो सकती है","नए टूल्स से कम context-aware"],"hinglish":["Chat ke liye Cursor ya GitHub Copilot se kam impressive","Competitors ke comparison mein purane AI models","Enterprise pricing zyada ho sakti hai","Naye tools se kam context-aware"]}',
  use_cases = '{"en":["Enterprise development teams with strict privacy","Banking and financial software development","Healthcare application coding","Government projects needing on-premise AI","Teams that want AI to learn their codebase style","Individual developers preferring privacy"],"hi":["सख्त गोपनीयता वाली एंटरप्राइज़ डेवलपमेंट टीमें","बैंकिंग और वित्तीय सॉफ्टवेयर डेवलपमेंट","स्वास्थ्य सेवा एप्लीकेशन कोडिंग","On-premise AI चाहने वाले सरकारी प्रोजेक्ट","AI से अपने codebase स्टाइल सीखने वाली टीमें","गोपनीयता पसंद करने वाले Individual developers"],"hinglish":["Strict privacy wali enterprise development teams","Banking aur financial software development","Healthcare application coding","On-premise AI chahne wale government projects","AI se apna codebase style sikhane wali teams","Privacy prefer karne wale individual developers"]}',
  alternatives = ARRAY['github-copilot','cursor','codeium','windsurf'],
  hindi_summary = 'Tabnine privacy-first AI coding assistant है — आपका कोड कभी cloud पर नहीं जाता। बैंकिंग, हेल्थकेयर, और government जैसे sensitive projects के लिए सबसे सुरक्षित विकल्प।'
WHERE slug = 'tabnine';

-- ── Codeium ───────────────────────────────────────────────────
UPDATE public.ai_tools SET
  features = '{"en":["Free AI code completion for all developers","Chat interface for code questions","Context-aware autocomplete","Supports 70+ languages","Works in VS Code, JetBrains, Vim and more","Windsurf integration for agentic coding","Enterprise on-premise deployment available"],"hi":["सभी developers के लिए मुफ्त AI कोड कम्पलीशन","कोड सवालों के लिए चैट इंटरफेस","Context-aware autocomplete","70+ भाषाओं का समर्थन","VS Code, JetBrains, Vim और अधिक में काम करता है","Agentic कोडिंग के लिए Windsurf इंटीग्रेशन","एंटरप्राइज़ on-premise deployment उपलब्ध"],"hinglish":["Sabhi developers ke liye free AI code completion","Code questions ke liye chat interface","Context-aware autocomplete","70+ languages support","VS Code, JetBrains, Vim aur zyada mein kaam karta hai","Agentic coding ke liye Windsurf integration","Enterprise on-premise deployment available"]}',
  pros = '{"en":["Completely free for individual developers","Very fast autocomplete","Works in almost every IDE and editor","Good quality completions","No usage limits on free plan"],"hi":["Individual developers के लिए बिल्कुल मुफ्त","बहुत तेज़ autocomplete","लगभग हर IDE और editor में काम करता है","अच्छी गुणवत्ता completions","मुफ्त प्लान पर कोई उपयोग सीमा नहीं"],"hinglish":["Individual developers ke liye bilkul free","Bahut fast autocomplete","Almost har IDE aur editor mein kaam karta hai","Achhi quality completions","Free plan pe koi usage limits nahi"]}',
  cons = '{"en":["Less powerful than Cursor for complex tasks","Chat features less capable than GitHub Copilot Chat","Less context window than Cursor","Company may monetize in the future"],"hi":["जटिल कार्यों के लिए Cursor से कम शक्तिशाली","GitHub Copilot Chat से कम सक्षम चैट फीचर्स","Cursor से कम context window","कंपनी भविष्य में monetize कर सकती है"],"hinglish":["Complex tasks ke liye Cursor se kam powerful","GitHub Copilot Chat se kam capable chat features","Cursor se kam context window","Company future mein monetize kar sakti hai"]}',
  use_cases = '{"en":["Students learning programming","Individual developers on a budget","Open source project contributors","Freelancers who need free AI coding help","Quick prototyping and scripting","Teams evaluating AI coding tools before paying"],"hi":["प्रोग्रामिंग सीखने वाले छात्र","बजट पर Individual developers","ओपन सोर्स प्रोजेक्ट contributors","मुफ्त AI कोडिंग सहायता चाहने वाले फ्रीलांसर","त्वरित प्रोटोटाइपिंग और scripting","भुगतान से पहले AI कोडिंग टूल evaluate करने वाली टीमें"],"hinglish":["Programming sikhne wale students","Budget pe individual developers","Open source project contributors","Free AI coding help chahne wale freelancers","Quick prototyping aur scripting","Pay karne se pehle AI coding tools evaluate karne wali teams"]}',
  alternatives = ARRAY['github-copilot','cursor','tabnine','windsurf'],
  hindi_summary = 'Codeium बिल्कुल मुफ्त AI code completion है — बिना किसी सीमा के। छात्रों और बजट-conscious developers के लिए GitHub Copilot का सबसे अच्छा फ्री विकल्प।'
WHERE slug = 'codeium';

-- ── Replit ────────────────────────────────────────────────────
UPDATE public.ai_tools SET
  features = '{"en":["Browser-based IDE — no setup required","Replit AI Agent: build apps from description","50+ programming languages supported","Instant deployment and hosting","Collaborative real-time coding","Ghost Writer AI code suggestions","Free tier with always-on repls"],"hi":["ब्राउज़र-आधारित IDE — कोई सेटअप नहीं","Replit AI Agent: विवरण से ऐप बनाएं","50+ प्रोग्रामिंग भाषाओं का समर्थन","तत्काल deployment और hosting","सहयोगी रियल-टाइम कोडिंग","Ghost Writer AI कोड सुझाव","always-on repls के साथ मुफ्त टियर"],"hinglish":["Browser-based IDE — koi setup nahi","Replit AI Agent: description se apps banao","50+ programming languages support","Instant deployment aur hosting","Collaborative real-time coding","Ghost Writer AI code suggestions","Always-on repls ke saath free tier"]}',
  pros = '{"en":["Zero setup — code in browser immediately","Great for beginners and students","AI Agent can build full apps from scratch","Free hosting included","Real-time collaboration is smooth"],"hi":["Zero setup — तुरंत ब्राउज़र में कोड करें","शुरुआती और छात्रों के लिए बेहतरीन","AI Agent स्क्रैच से पूरे ऐप बना सकता है","मुफ्त hosting शामिल","रियल-टाइम सहयोग सुचारू है"],"hinglish":["Zero setup — immediately browser mein code karo","Beginners aur students ke liye great","AI Agent scratch se poore apps bana sakta hai","Free hosting included","Real-time collaboration smooth hai"]}',
  cons = '{"en":["Free repls can be slow to start","Limited compute on free tier","Not ideal for large professional projects","Privacy concerns — code stored on Replit servers"],"hi":["मुफ्त repls शुरू होने में धीमे हो सकते हैं","मुफ्त टियर पर सीमित compute","बड़े प्रोफेशनल प्रोजेक्ट के लिए आदर्श नहीं","गोपनीयता चिंताएं — कोड Replit servers पर stored"],"hinglish":["Free repls start hone mein slow ho sakte hain","Free tier pe limited compute","Bade professional projects ke liye ideal nahi","Privacy concerns — code Replit servers pe stored"]}',
  use_cases = '{"en":["Students learning to code without laptop setup","Coding bootcamp and school projects","Quick prototypes to share with clients","Building and hosting simple web apps","Competitive programming practice","Teaching programming in classrooms"],"hi":["बिना लैपटॉप सेटअप के कोड सीखने वाले छात्र","कोडिंग bootcamp और स्कूल प्रोजेक्ट","क्लाइंट के साथ शेयर करने के लिए त्वरित प्रोटोटाइप","सरल वेब ऐप बनाना और host करना","Competitive programming अभ्यास","कक्षाओं में प्रोग्रामिंग शिक्षण"],"hinglish":["Bina laptop setup ke code sikhne wale students","Coding bootcamp aur school projects","Clients ke saath share karne ke liye quick prototypes","Simple web apps banana aur host karna","Competitive programming practice","Classrooms mein programming teaching"]}',
  alternatives = ARRAY['cursor','bolt-new','lovable','v0-dev'],
  hindi_summary = 'Replit ब्राउज़र में कोड करने का सबसे आसान तरीका है — कोई installation नहीं। AI Agent से बस बोलो और ऐप बन जाएगा। छात्रों और शुरुआती developers के लिए परफेक्ट।'
WHERE slug = 'replit';

-- ── V0 by Vercel ──────────────────────────────────────────────
UPDATE public.ai_tools SET
  features = '{"en":["Generate React UI components from text prompts","Shadcn/UI and Tailwind CSS based output","Iterative refinement through chat","Deploy directly to Vercel","Copy-paste ready component code","Multiple design variations per prompt","Free tier with generous credits"],"hi":["टेक्स्ट प्रॉम्प्ट से React UI components जनरेट करें","Shadcn/UI और Tailwind CSS आधारित आउटपुट","चैट के ज़रिए iterative refinement","Vercel पर सीधे deploy करें","Copy-paste ready component कोड","प्रति प्रॉम्प्ट कई design variations","उदार क्रेडिट के साथ मुफ्त टियर"],"hinglish":["Text prompts se React UI components generate karo","Shadcn/UI aur Tailwind CSS based output","Chat ke zariye iterative refinement","Vercel pe directly deploy karo","Copy-paste ready component code","Per prompt multiple design variations","Generous credits ke saath free tier"]}',
  pros = '{"en":["Best for generating clean React/Next.js UI","Output is production-ready code","Iterative refinement is excellent","Direct Vercel deployment is a huge bonus","Free tier is very usable"],"hi":["क्लीन React/Next.js UI जनरेट करने के लिए सबसे अच्छा","आउटपुट production-ready कोड है","Iterative refinement उत्कृष्ट है","सीधे Vercel deployment एक बड़ा बोनस है","मुफ्त टियर बहुत उपयोगी है"],"hinglish":["Clean React/Next.js UI generate karne ke liye best","Output production-ready code hai","Iterative refinement excellent hai","Direct Vercel deployment ek bada bonus hai","Free tier bahut usable hai"]}',
  cons = '{"en":["React/Next.js only — no Vue, Angular etc.","Best with Vercel stack — less useful otherwise","Credits run out for complex projects","Learning curve for non-React developers"],"hi":["केवल React/Next.js — Vue, Angular आदि नहीं","Vercel stack के साथ सबसे अच्छा — अन्यथा कम उपयोगी","जटिल प्रोजेक्ट के लिए क्रेडिट खत्म हो जाते हैं","गैर-React developers के लिए सीखने की कठिनाई"],"hinglish":["Sirf React/Next.js — Vue, Angular aadi nahi","Vercel stack ke saath best — otherwise kam useful","Complex projects ke liye credits khatam ho jaate hain","Non-React developers ke liye learning curve"]}',
  use_cases = '{"en":["Rapidly prototyping React UI components","Building landing pages and dashboards","Generating form and table components","Design-to-code workflow for React developers","Startup MVP frontend development","Learning React component patterns"],"hi":["React UI components तेज़ी से प्रोटोटाइप करना","Landing pages और dashboards बनाना","Form और table components जनरेट करना","React developers के लिए design-to-code वर्कफ्लो","स्टार्टअप MVP frontend डेवलपमेंट","React component पैटर्न सीखना"],"hinglish":["React UI components rapidly prototype karna","Landing pages aur dashboards banana","Form aur table components generate karna","React developers ke liye design-to-code workflow","Startup MVP frontend development","React component patterns seekhna"]}',
  alternatives = ARRAY['bolt-new','lovable','cursor','framer'],
  hindi_summary = 'V0 by Vercel टेक्स्ट से React UI components बनाता है — production-ready code के साथ। Next.js developers के लिए UI को जल्दी prototype करने का सबसे तेज़ तरीका।'
WHERE slug IN ('v0-dev','v0-by-vercel');

-- ── Bolt.new ──────────────────────────────────────────────────
UPDATE public.ai_tools SET
  features = '{"en":["Build full-stack web apps from text prompts","Runs in browser — StackBlitz powered","Instant deployment to production","Edit code through chat or directly","npm package installation in browser","React, Vue, Next.js and more supported","Free tier available"],"hi":["टेक्स्ट प्रॉम्प्ट से full-stack वेब ऐप बनाएं","ब्राउज़र में चलता है — StackBlitz powered","production में तत्काल deployment","चैट या सीधे कोड एडिट करें","ब्राउज़र में npm package installation","React, Vue, Next.js और अधिक समर्थित","मुफ्त टियर उपलब्ध"],"hinglish":["Text prompts se full-stack web apps banao","Browser mein chalta hai — StackBlitz powered","Production mein instant deployment","Chat ya directly code edit karo","Browser mein npm package installation","React, Vue, Next.js aur zyada supported","Free tier available"]}',
  pros = '{"en":["Most capable text-to-app tool available","Handles both frontend and backend","No setup — runs entirely in browser","StackBlitz integration enables real code execution","Great for prototyping complete apps quickly"],"hi":["उपलब्ध सबसे सक्षम text-to-app टूल","Frontend और backend दोनों संभालता है","कोई सेटअप नहीं — पूरी तरह ब्राउज़र में चलता है","StackBlitz इंटीग्रेशन रियल कोड execution सक्षम करता है","पूरे ऐप तेज़ी से प्रोटोटाइप करने के लिए बेहतरीन"],"hinglish":["Available sabse capable text-to-app tool","Frontend aur backend dono handle karta hai","Koi setup nahi — poori tarah browser mein chalta hai","StackBlitz integration real code execution enable karta hai","Poore apps quickly prototype karne ke liye great"]}',
  cons = '{"en":["Free credits limited for complex apps","Browser environment has compute limits","Not for large-scale production apps","Debugging complex issues can be hard in chat"],"hi":["जटिल ऐप के लिए मुफ्त क्रेडिट सीमित","ब्राउज़र एनवायरनमेंट में compute सीमाएं","बड़े पैमाने के production ऐप के लिए नहीं","चैट में जटिल समस्याओं को debug करना मुश्किल हो सकता है"],"hinglish":["Complex apps ke liye free credits limited","Browser environment mein compute limits","Large-scale production apps ke liye nahi","Chat mein complex issues debug karna mushkil ho sakta hai"]}',
  use_cases = '{"en":["Building MVP apps without coding expertise","Rapid client prototype demonstrations","Hackathon project development","Non-technical founders building demos","Learning full-stack development interactively","Quick internal tools and dashboards"],"hi":["कोडिंग विशेषज्ञता के बिना MVP ऐप बनाना","त्वरित क्लाइंट प्रोटोटाइप प्रदर्शन","Hackathon प्रोजेक्ट डेवलपमेंट","डेमो बनाने वाले गैर-तकनीकी founders","Interactive रूप से full-stack डेवलपमेंट सीखना","त्वरित internal टूल और dashboards"],"hinglish":["Coding expertise ke bina MVP apps banana","Quick client prototype demonstrations","Hackathon project development","Demos banana wale non-technical founders","Interactively full-stack development seekhna","Quick internal tools aur dashboards"]}',
  alternatives = ARRAY['lovable','replit','cursor','v0-dev'],
  hindi_summary = 'Bolt.new ब्राउज़र में full-stack ऐप बनाने का सबसे powerful tool है। बस बताओ क्या चाहिए — frontend, backend, database सब बन जाता है। Non-technical founders के लिए क्रांतिकारी।'
WHERE slug IN ('bolt-new','boltnew');

-- ── Lovable ────────────────────────────────────────────────────
UPDATE public.ai_tools SET
  features = '{"en":["Build full web apps from natural language","React + Supabase stack generated","Integrated GitHub sync","Live preview as you build","Deploy to production instantly","Edit through chat or visual editor","Team collaboration support"],"hi":["प्राकृतिक भाषा से पूर्ण वेब ऐप बनाएं","React + Supabase stack जनरेट","एकीकृत GitHub sync","बनाते समय Live preview","तुरंत production में deploy करें","चैट या visual editor से edit करें","टीम सहयोग समर्थन"],"hinglish":["Natural language se poore web apps banao","React + Supabase stack generated","Integrated GitHub sync","Banate samay live preview","Instantly production mein deploy karo","Chat ya visual editor se edit karo","Team collaboration support"]}',
  pros = '{"en":["Best for building complete React + Supabase apps","GitHub sync keeps code in your control","Visual editor alongside chat is great","Production deployment is seamless","Strong for SaaS and internal tools"],"hi":["Complete React + Supabase ऐप बनाने के लिए सबसे अच्छा","GitHub sync कोड को आपके नियंत्रण में रखता है","चैट के साथ Visual editor बेहतरीन है","production deployment निर्बाध है","SaaS और internal टूल के लिए मजबूत"],"hinglish":["Complete React + Supabase apps banane ke liye best","GitHub sync code ko aapke control mein rakhta hai","Chat ke saath visual editor great hai","Production deployment seamless hai","SaaS aur internal tools ke liye strong"]}',
  cons = '{"en":["Credits consumed quickly for complex apps","Primarily React + Supabase — limited stack flexibility","Bugs can be hard to fix through chat","Premium credits required for heavy use"],"hi":["जटिल ऐप के लिए क्रेडिट जल्दी खर्च होते हैं","मुख्य रूप से React + Supabase — सीमित stack flexibility","चैट के ज़रिए bugs fix करना मुश्किल हो सकता है","भारी उपयोग के लिए Premium क्रेडिट जरूरी"],"hinglish":["Complex apps ke liye credits jaldi kharach hote hain","Mainly React + Supabase — limited stack flexibility","Chat ke zariye bugs fix karna mushkil ho sakta hai","Heavy use ke liye premium credits zaroori"]}',
  use_cases = '{"en":["SaaS product prototyping","Internal business tool development","Startup MVP with auth and database","Solo developer building side projects","Non-technical founders validating ideas","Client demo apps with real functionality"],"hi":["SaaS प्रोडक्ट प्रोटोटाइपिंग","Internal business टूल डेवलपमेंट","Auth और database के साथ Startup MVP","साइड प्रोजेक्ट बनाने वाले Solo developer","आइडिया validate करने वाले गैर-तकनीकी founders","रियल functionality के साथ Client demo ऐप"],"hinglish":["SaaS product prototyping","Internal business tool development","Auth aur database ke saath startup MVP","Side projects banana wale solo developers","Ideas validate karne wale non-technical founders","Real functionality ke saath client demo apps"]}',
  alternatives = ARRAY['bolt-new','replit','cursor','v0-dev'],
  hindi_summary = 'Lovable AI से पूरा React + Supabase ऐप बनाता है — database, authentication सब सहित। SaaS idea को तेज़ी से MVP में बदलने के लिए सबसे अच्छा tool।'
WHERE slug = 'lovable';

-- ── Windsurf ──────────────────────────────────────────────────
UPDATE public.ai_tools SET
  features = '{"en":["Cascade: agentic AI that takes actions autonomously","Multi-file context awareness","Built on VS Code — familiar environment","Flows: end-to-end task completion","Real-time codebase understanding","Supports all major languages","Free tier available"],"hi":["Cascade: स्वायत्त रूप से actions लेने वाला agentic AI","Multi-file context awareness","VS Code पर बना — परिचित एनवायरनमेंट","Flows: end-to-end task completion","रियल-टाइम codebase समझ","सभी प्रमुख भाषाओं का समर्थन","मुफ्त टियर उपलब्ध"],"hinglish":["Cascade: autonomously actions lene wala agentic AI","Multi-file context awareness","VS Code pe banaya — familiar environment","Flows: end-to-end task completion","Real-time codebase understanding","Sabhi major languages support","Free tier available"]}',
  pros = '{"en":["Cascade agent is genuinely impressive for autonomous tasks","Free tier is more generous than Cursor","Strong multi-file understanding","VS Code familiar environment reduces learning curve","Good at explaining what it is doing"],"hi":["Cascade एजेंट स्वायत्त कार्यों के लिए वास्तव में प्रभावशाली है","मुफ्त टियर Cursor से अधिक उदार है","मजबूत multi-file समझ","VS Code परिचित एनवायरनमेंट सीखने की कठिनाई कम करता है","यह क्या कर रहा है इसे समझाने में अच्छा है"],"hinglish":["Cascade agent autonomous tasks ke liye genuinely impressive hai","Free tier Cursor se zyada generous hai","Strong multi-file understanding","VS Code familiar environment learning curve kam karta hai","Kya kar raha hai ye explain karne mein achha hai"]}',
  cons = '{"en":["Newer and less mature than Cursor","Occasional hallucinations in complex codebases","Community and resources smaller than Cursor","Extension ecosystem smaller than vanilla VS Code"],"hi":["Cursor से नया और कम परिपक्व","जटिल codebases में कभी-कभी hallucinations","Cursor से छोटा समुदाय और संसाधन","Vanilla VS Code से छोटा extension इकोसिस्टम"],"hinglish":["Cursor se naya aur kam mature","Complex codebases mein kabhi kabhi hallucinations","Cursor se chhoti community aur resources","Vanilla VS Code se chhota extension ecosystem"]}',
  use_cases = '{"en":["Full-stack development with autonomous assistance","Refactoring and modernizing codebases","Building features with minimal manual coding","Developer teams evaluating Cursor alternatives","Open source project maintenance","Rapid feature prototyping"],"hi":["स्वायत्त सहायता के साथ Full-stack डेवलपमेंट","Codebases को refactor और modernize करना","न्यूनतम मैन्युअल कोडिंग से फीचर बनाना","Cursor alternatives evaluate करने वाली developer टीमें","ओपन सोर्स प्रोजेक्ट maintenance","रैपिड फीचर प्रोटोटाइपिंग"],"hinglish":["Autonomous assistance ke saath full-stack development","Codebases ko refactor aur modernize karna","Minimal manual coding se features banana","Cursor alternatives evaluate karne wali developer teams","Open source project maintenance","Rapid feature prototyping"]}',
  alternatives = ARRAY['cursor','github-copilot','codeium','tabnine'],
  hindi_summary = 'Windsurf Cursor का एक मजबूत प्रतिद्वंद्वी है — Cascade AI agent से autonomous coding। Cursor से ज़्यादा generous free tier। Full-stack developers के लिए।'
WHERE slug = 'windsurf';

-- ── Devin ─────────────────────────────────────────────────────
UPDATE public.ai_tools SET
  features = '{"en":["World''s first autonomous AI software engineer","Completes multi-step engineering tasks end-to-end","Reads documentation and learns as it works","Runs code, debugs and tests autonomously","Browses the web for solutions","Works in a persistent development environment","Integrates with GitHub, Slack and Jira"],"hi":["दुनिया का पहला autonomous AI सॉफ्टवेयर इंजीनियर","end-to-end multi-step इंजीनियरिंग कार्य पूरे करता है","दस्तावेज़ पढ़ता है और काम करते हुए सीखता है","स्वायत्त रूप से कोड run, debug और test करता है","समाधान के लिए वेब browse करता है","Persistent development environment में काम करता है","GitHub, Slack और Jira के साथ एकीकृत"],"hinglish":["Duniya ka pehla autonomous AI software engineer","End-to-end multi-step engineering tasks complete karta hai","Documentation padhta hai aur kaam karte hue seekhta hai","Autonomously code run, debug aur test karta hai","Solutions ke liye web browse karta hai","Persistent development environment mein kaam karta hai","GitHub, Slack aur Jira ke saath integrated"]}',
  pros = '{"en":["Truly autonomous — can complete tasks without hand-holding","Can handle weeks-long engineering tasks","Learns and adapts during the task","Impressive benchmark performance","Good for complex, multi-step projects"],"hi":["वास्तव में स्वायत्त — बिना hand-holding के कार्य पूरे कर सकता है","सप्ताहों लंबे इंजीनियरिंग कार्य संभाल सकता है","कार्य के दौरान सीखता और अनुकूलित होता है","प्रभावशाली benchmark प्रदर्शन","जटिल, multi-step प्रोजेक्ट के लिए अच्छा"],"hinglish":["Truly autonomous — bina hand-holding ke tasks complete kar sakta hai","Weeks-long engineering tasks handle kar sakta hai","Task ke dauran seekhta aur adapt karta hai","Impressive benchmark performance","Complex, multi-step projects ke liye achha"]}',
  cons = '{"en":["Very expensive — enterprise pricing","Still makes mistakes on complex tasks","Not yet a replacement for human engineers","Access limited — waitlist or enterprise only","Results require review before production use"],"hi":["बहुत महंगा — एंटरप्राइज़ कीमत","जटिल कार्यों में अभी भी गलतियां करता है","अभी मानव इंजीनियरों का प्रतिस्थापन नहीं","सीमित पहुंच — waitlist या केवल एंटरप्राइज़","production उपयोग से पहले परिणाम समीक्षा जरूरी"],"hinglish":["Bahut mehanga — enterprise pricing","Complex tasks mein abhi bhi galtiyan karta hai","Abhi human engineers ka replacement nahi","Access limited — waitlist ya enterprise only","Production use se pehle results review zaroori"]}',
  use_cases = '{"en":["Automating repetitive engineering tasks","Bug fixing across large codebases","Writing and running test suites","Migrating code between frameworks","API integration and boilerplate creation","Research and documentation tasks"],"hi":["दोहराए जाने वाले इंजीनियरिंग कार्य स्वचालित करना","बड़े codebases में Bug fixing","Test suite लिखना और run करना","Framework के बीच कोड migrate करना","API integration और boilerplate क्रिएशन","रिसर्च और दस्तावेज़ीकरण कार्य"],"hinglish":["Repetitive engineering tasks automate karna","Bade codebases mein bug fixing","Test suites likhna aur run karna","Frameworks ke beech code migrate karna","API integration aur boilerplate creation","Research aur documentation tasks"]}',
  alternatives = ARRAY['cursor','windsurf','github-copilot','claude-code'],
  hindi_summary = 'Devin दुनिया का पहला AI software engineer है जो खुद से कोडिंग tasks पूरे करता है। अभी enterprise-level टूल है, लेकिन software development का भविष्य यही है।'
WHERE slug = 'devin';

-- ── Cline ─────────────────────────────────────────────────────
UPDATE public.ai_tools SET
  features = '{"en":["Open-source AI coding agent for VS Code","Autonomous task completion with approval steps","Supports Claude, GPT-4, Gemini and local models","File creation, editing and terminal commands","Browser automation capabilities","Context-aware codebase understanding","Free — pay only for API tokens used"],"hi":["VS Code के लिए ओपन-सोर्स AI कोडिंग एजेंट","approval steps के साथ Autonomous task completion","Claude, GPT-4, Gemini और local models समर्थन","फाइल क्रिएशन, एडिटिंग और terminal commands","ब्राउज़र automation क्षमताएं","Context-aware codebase समझ","मुफ्त — केवल उपयोग किए API tokens का भुगतान करें"],"hinglish":["VS Code ke liye open-source AI coding agent","Approval steps ke saath autonomous task completion","Claude, GPT-4, Gemini aur local models support","File creation, editing aur terminal commands","Browser automation capabilities","Context-aware codebase understanding","Free — sirf use kiye API tokens ka payment karo"]}',
  pros = '{"en":["Free and open-source — no subscription","Works with any AI model via API","Transparent — shows every step before executing","GitHub-synced open source community","Highly customizable for power users"],"hi":["मुफ्त और ओपन-सोर्स — कोई सब्सक्रिप्शन नहीं","API के ज़रिए किसी भी AI model के साथ काम करता है","Transparent — execute करने से पहले हर step दिखाता है","GitHub-synced ओपन सोर्स समुदाय","Power users के लिए अत्यधिक customizable"],"hinglish":["Free aur open-source — koi subscription nahi","API ke zariye kisi bhi AI model ke saath kaam karta hai","Transparent — execute karne se pehle har step dikhata hai","GitHub-synced open source community","Power users ke liye highly customizable"]}',
  cons = '{"en":["More complex setup than Cursor","API costs can add up for heavy use","Less polished UX than commercial tools","Requires understanding of AI APIs"],"hi":["Cursor से अधिक जटिल सेटअप","भारी उपयोग के लिए API लागत बढ़ सकती है","वाणिज्यिक टूल से कम पॉलिश्ड UX","AI APIs की समझ जरूरी"],"hinglish":["Cursor se zyada complex setup","Heavy use ke liye API costs badh sakte hain","Commercial tools se kam polished UX","AI APIs ki understanding zaroori"]}',
  use_cases = '{"en":["Developers who want full control over AI models","Privacy-conscious developers using local models","Building automation scripts and agents","Open source contributors","Developers who want to avoid subscriptions","Advanced users experimenting with AI coding"],"hi":["AI models पर पूरा नियंत्रण चाहने वाले Developers","Local models उपयोग करने वाले privacy-conscious developers","Automation scripts और agents बनाना","ओपन सोर्स contributors","Subscriptions से बचने वाले Developers","AI कोडिंग के साथ प्रयोग करने वाले Advanced users"],"hinglish":["AI models pe full control chahne wale developers","Local models use karne wale privacy-conscious developers","Automation scripts aur agents banana","Open source contributors","Subscriptions se bachne wale developers","AI coding ke saath experiment karne wale advanced users"]}',
  alternatives = ARRAY['cursor','windsurf','github-copilot','devin'],
  hindi_summary = 'Cline VS Code के लिए मुफ्त और ओपन-सोर्स AI coding agent है। अपना API key लगाओ और Claude या GPT-4 से autonomous coding करो — कोई subscription नहीं।'
WHERE slug = 'cline';

-- ── Claude Code ────────────────────────────────────────────────
UPDATE public.ai_tools SET
  features = '{"en":["Terminal-based AI coding agent by Anthropic","Deep codebase understanding via file reading","Runs shell commands and tests autonomously","Git-aware: reads commits, diffs and blame","Works with any language and framework","Integrates with VS Code and JetBrains","Powered by Claude Sonnet and Opus models"],"hi":["Anthropic का Terminal-based AI coding एजेंट","फाइल पढ़कर Deep codebase समझ","Shell commands और tests स्वायत्त रूप से run करता है","Git-aware: commits, diffs और blame पढ़ता है","किसी भी भाषा और framework के साथ काम करता है","VS Code और JetBrains के साथ एकीकृत","Claude Sonnet और Opus models से powered"],"hinglish":["Anthropic ka terminal-based AI coding agent","Files padhkar deep codebase understanding","Shell commands aur tests autonomously run karta hai","Git-aware: commits, diffs aur blame padhta hai","Kisi bhi language aur framework ke saath kaam karta hai","VS Code aur JetBrains ke saath integrated","Claude Sonnet aur Opus models se powered"]}',
  pros = '{"en":["Deepest codebase understanding of any tool","Terminal-native fits experienced developer workflow","Transparent — you see exactly what it does","Excellent for complex refactoring and debugging","Anthropic''s safety-focused approach"],"hi":["किसी भी टूल की सबसे गहरी codebase समझ","Terminal-native अनुभवी developer workflow में फिट","Transparent — आप देखते हैं यह क्या करता है","जटिल refactoring और debugging के लिए उत्कृष्ट","Anthropic का safety-focused दृष्टिकोण"],"hinglish":["Kisi bhi tool ki sabse deep codebase understanding","Terminal-native experienced developer workflow mein fit","Transparent — aap dekhte hain ye kya karta hai","Complex refactoring aur debugging ke liye excellent","Anthropic ka safety-focused approach"]}',
  cons = '{"en":["Terminal-only — no visual editor","Requires Claude API key (costs money)","Steeper learning curve than Cursor","Less beginner-friendly UI"],"hi":["केवल Terminal — कोई visual editor नहीं","Claude API key जरूरी (पैसे लगते हैं)","Cursor से अधिक सीखने की कठिनाई","कम beginner-friendly UI"],"hinglish":["Terminal-only — koi visual editor nahi","Claude API key zaroori (paise lagte hain)","Cursor se zyada learning curve","Kam beginner-friendly UI"]}',
  use_cases = '{"en":["Experienced developers doing complex refactoring","Large codebase analysis and navigation","Autonomous bug fixing and testing","CI/CD pipeline automation","Code review and documentation","Backend and systems programming"],"hi":["जटिल refactoring करने वाले अनुभवी developers","बड़े codebase विश्लेषण और navigation","Autonomous bug fixing और testing","CI/CD pipeline automation","कोड समीक्षा और दस्तावेज़ीकरण","Backend और systems programming"],"hinglish":["Complex refactoring karne wale experienced developers","Bade codebase analysis aur navigation","Autonomous bug fixing aur testing","CI/CD pipeline automation","Code review aur documentation","Backend aur systems programming"]}',
  alternatives = ARRAY['cursor','windsurf','cline','devin'],
  hindi_summary = 'Claude Code Anthropic का terminal-based AI coding agent है जो आपके codebase को सबसे गहराई से समझता है। Experienced developers के लिए complex projects में सबसे reliable AI assistant।'
WHERE slug = 'claude-code';

-- ── Framer ─────────────────────────────────────────────────────
UPDATE public.ai_tools SET
  features = '{"en":["AI website builder from text description","Visual design and CMS in one","Publish without coding knowledge","Framer AI: generate sections and pages","SEO-optimized output","Custom domain support","Component library with animations"],"hi":["टेक्स्ट विवरण से AI वेबसाइट बिल्डर","एक में Visual design और CMS","कोडिंग ज्ञान के बिना publish करें","Framer AI: sections और pages जनरेट करें","SEO-ऑप्टिमाइज़्ड आउटपुट","Custom domain समर्थन","animations के साथ Component library"],"hinglish":["Text description se AI website builder","Ek mein visual design aur CMS","Coding knowledge ke bina publish karo","Framer AI: sections aur pages generate karo","SEO-optimized output","Custom domain support","Animations ke saath component library"]}',
  pros = '{"en":["Best no-code website builder with design quality","AI generates beautiful sections instantly","Animations and interactions built-in","Great for portfolios, landing pages and startups","No developer needed for polished results"],"hi":["डिज़ाइन गुणवत्ता के साथ सबसे अच्छा no-code वेबसाइट बिल्डर","AI तुरंत सुंदर sections जनरेट करता है","बिल्ट-इन animations और interactions","Portfolios, landing pages और startups के लिए बेहतरीन","Polished results के लिए developer की जरूरत नहीं"],"hinglish":["Design quality ke saath best no-code website builder","AI instantly beautiful sections generate karta hai","Built-in animations aur interactions","Portfolios, landing pages aur startups ke liye great","Polished results ke liye developer ki zaroorat nahi"]}',
  cons = '{"en":["Subscription needed for custom domain","Less suitable for e-commerce or complex apps","Learning curve for advanced features","More expensive than Webflow or WordPress"],"hi":["Custom domain के लिए सब्सक्रिप्शन जरूरी","E-commerce या जटिल ऐप के लिए कम उपयुक्त","Advanced फीचर्स के लिए सीखने की कठिनाई","Webflow या WordPress से अधिक महंगा"],"hinglish":["Custom domain ke liye subscription zaroori","E-commerce ya complex apps ke liye kam suitable","Advanced features ke liye learning curve","Webflow ya WordPress se zyada mehanga"]}',
  use_cases = '{"en":["Portfolio websites for designers and freelancers","Startup landing pages","Marketing campaign microsites","Product launch pages","Agency client websites","Personal brand websites"],"hi":["Designers और freelancers के लिए Portfolio वेबसाइट","Startup landing pages","मार्केटिंग campaign microsites","प्रोडक्ट launch pages","Agency client वेबसाइट","Personal brand वेबसाइट"],"hinglish":["Designers aur freelancers ke liye portfolio websites","Startup landing pages","Marketing campaign microsites","Product launch pages","Agency client websites","Personal brand websites"]}',
  alternatives = ARRAY['v0-dev','lovable','canva-ai-magic-studio','bolt-new'],
  hindi_summary = 'Framer AI से सुंदर वेबसाइट बनाने का सबसे अच्छा no-code tool है। Portfolio, landing page, startup website — बिना coding के professional results।'
WHERE slug = 'framer';

-- ── Supabase ──────────────────────────────────────────────────
UPDATE public.ai_tools SET
  features = '{"en":["Open-source Firebase alternative with AI features","Postgres database with vector embeddings (pgvector)","Supabase AI: SQL generation from natural language","Authentication, storage and edge functions","Real-time database subscriptions","Auto-generated REST and GraphQL APIs","Free tier with generous limits"],"hi":["AI फीचर्स के साथ ओपन-सोर्स Firebase विकल्प","vector embeddings के साथ Postgres database (pgvector)","Supabase AI: प्राकृतिक भाषा से SQL जनरेशन","Authentication, storage और edge functions","रियल-टाइम database subscriptions","Auto-generated REST और GraphQL APIs","उदार सीमाओं के साथ मुफ्त टियर"],"hinglish":["AI features ke saath open-source Firebase alternative","Vector embeddings ke saath Postgres database (pgvector)","Supabase AI: natural language se SQL generation","Authentication, storage aur edge functions","Real-time database subscriptions","Auto-generated REST aur GraphQL APIs","Generous limits ke saath free tier"]}',
  pros = '{"en":["Open-source — no vendor lock-in","Excellent free tier for startups","pgvector enables powerful AI features","Auto-generated APIs save development time","Strong developer community and documentation"],"hi":["ओपन-सोर्स — कोई vendor lock-in नहीं","स्टार्टअप के लिए उत्कृष्ट मुफ्त टियर","pgvector शक्तिशाली AI फीचर्स सक्षम करता है","Auto-generated APIs डेवलपमेंट समय बचाते हैं","मजबूत developer समुदाय और दस्तावेज़ीकरण"],"hinglish":["Open-source — koi vendor lock-in nahi","Startups ke liye excellent free tier","pgvector powerful AI features enable karta hai","Auto-generated APIs development time bachate hain","Strong developer community aur documentation"]}',
  cons = '{"en":["Postgres knowledge needed for advanced use","Free tier has row limits","Self-hosting complex for beginners","Some features less mature than Firebase"],"hi":["Advanced उपयोग के लिए Postgres ज्ञान जरूरी","मुफ्त टियर में row सीमाएं","शुरुआती लोगों के लिए Self-hosting जटिल","कुछ फीचर्स Firebase से कम परिपक्व"],"hinglish":["Advanced use ke liye Postgres knowledge zaroori","Free tier mein row limits","Beginners ke liye self-hosting complex","Kuch features Firebase se kam mature"]}',
  use_cases = '{"en":["Building AI applications with vector search","SaaS backend with auth and database","Real-time collaborative apps","Next.js and React app backends","Startup MVPs needing quick backend setup","Building RAG (retrieval-augmented generation) systems"],"hi":["Vector search के साथ AI applications बनाना","Auth और database के साथ SaaS backend","रियल-टाइम collaborative ऐप","Next.js और React ऐप backends","त्वरित backend setup चाहने वाले Startup MVPs","RAG (retrieval-augmented generation) systems बनाना"],"hinglish":["Vector search ke saath AI applications banana","Auth aur database ke saath SaaS backend","Real-time collaborative apps","Next.js aur React app backends","Quick backend setup chahne wale startup MVPs","RAG systems banana"]}',
  alternatives = ARRAY['replit','bolt-new','lovable','railway'],
  hindi_summary = 'Supabase open-source backend platform है — database, authentication, storage सब एक जगह। AI ऐप बनाने के लिए vector search built-in। स्टार्टअप और developers के लिए बेहतरीन।'
WHERE slug = 'supabase';

-- ── Railway ────────────────────────────────────────────────────
UPDATE public.ai_tools SET
  features = '{"en":["Simple cloud deployment platform","One-click deploy from GitHub","Support for all major languages and frameworks","Database provisioning (Postgres, MySQL, Redis)","Environment variables management","Auto-scaling and custom domains","Generous free tier for small projects"],"hi":["सरल क्लाउड deployment प्लेटफॉर्म","GitHub से one-click deploy","सभी प्रमुख भाषाओं और frameworks का समर्थन","Database provisioning (Postgres, MySQL, Redis)","Environment variables management","Auto-scaling और custom domains","छोटे प्रोजेक्ट के लिए उदार मुफ्त टियर"],"hinglish":["Simple cloud deployment platform","GitHub se one-click deploy","Sabhi major languages aur frameworks support","Database provisioning (Postgres, MySQL, Redis)","Environment variables management","Auto-scaling aur custom domains","Chhote projects ke liye generous free tier"]}',
  pros = '{"en":["Simplest deployment experience available","GitHub integration is seamless","Database setup takes seconds","Great for students and solo developers","Free tier is usable for small projects"],"hi":["उपलब्ध सबसे सरल deployment अनुभव","GitHub इंटीग्रेशन निर्बाध है","Database setup सेकंडों में होता है","छात्रों और solo developers के लिए बेहतरीन","मुफ्त टियर छोटे प्रोजेक्ट के लिए उपयोगी"],"hinglish":["Available sabse simple deployment experience","GitHub integration seamless hai","Database setup seconds mein hota hai","Students aur solo developers ke liye great","Free tier chhote projects ke liye usable"]}',
  cons = '{"en":["Less powerful than AWS/GCP for large apps","Free tier has usage limits","Less enterprise features than Render or Fly.io","Pricing can increase unexpectedly with traffic"],"hi":["बड़े ऐप के लिए AWS/GCP से कम शक्तिशाली","मुफ्त टियर में उपयोग सीमाएं","Render या Fly.io से कम एंटरप्राइज़ फीचर्स","Traffic के साथ कीमत अप्रत्याशित रूप से बढ़ सकती है"],"hinglish":["Bade apps ke liye AWS/GCP se kam powerful","Free tier mein usage limits","Render ya Fly.io se kam enterprise features","Traffic ke saath pricing unexpectedly badh sakti hai"]}',
  use_cases = '{"en":["Deploying side projects and prototypes","Student project hosting","Small startup backend deployment","API and microservice hosting","Bot and automation script deployment","Database for personal projects"],"hi":["साइड प्रोजेक्ट और प्रोटोटाइप deploy करना","छात्र प्रोजेक्ट hosting","छोटे startup backend deployment","API और microservice hosting","Bot और automation script deployment","व्यक्तिगत प्रोजेक्ट के लिए Database"],"hinglish":["Side projects aur prototypes deploy karna","Student project hosting","Chhote startup backend deployment","API aur microservice hosting","Bot aur automation scripts deploy karna","Personal projects ke liye database"]}',
  alternatives = ARRAY['supabase','replit','bolt-new','lovable'],
  hindi_summary = 'Railway cloud पर app deploy करने का सबसे आसान तरीका है। GitHub से connect करो, deploy हो जाएगा। Students और solo developers के side projects के लिए परफेक्ट।'
WHERE slug = 'railway';

-- ── n8n ────────────────────────────────────────────────────────
UPDATE public.ai_tools SET
  features = '{"en":["Open-source workflow automation platform","Visual node-based workflow builder","400+ integrations with apps and APIs","AI Agent nodes with LLM support","Self-hostable for full data control","Code node for custom JavaScript/Python","Free community edition available"],"hi":["ओपन-सोर्स वर्कफ्लो automation प्लेटफॉर्म","Visual node-based वर्कफ्लो बिल्डर","ऐप और APIs के साथ 400+ integrations","LLM समर्थन के साथ AI Agent nodes","पूर्ण डेटा नियंत्रण के लिए Self-hostable","कस्टम JavaScript/Python के लिए Code node","मुफ्त community edition उपलब्ध"],"hinglish":["Open-source workflow automation platform","Visual node-based workflow builder","Apps aur APIs ke saath 400+ integrations","LLM support ke saath AI Agent nodes","Full data control ke liye self-hostable","Custom JavaScript/Python ke liye code node","Free community edition available"]}',
  pros = '{"en":["Open-source and self-hostable — full data privacy","More powerful than Zapier for complex workflows","AI Agent nodes enable AI automation","Free community edition with no limits","Strong developer community"],"hi":["ओपन-सोर्स और self-hostable — पूर्ण डेटा गोपनीयता","जटिल workflows के लिए Zapier से अधिक शक्तिशाली","AI Agent nodes AI automation सक्षम करते हैं","कोई सीमा नहीं के साथ मुफ्त community edition","मजबूत developer समुदाय"],"hinglish":["Open-source aur self-hostable — full data privacy","Complex workflows ke liye Zapier se zyada powerful","AI Agent nodes AI automation enable karte hain","Koi limits nahi ke saath free community edition","Strong developer community"]}',
  cons = '{"en":["Complex setup for self-hosting","Steeper learning curve than Zapier/Make","Requires technical knowledge for advanced use","Cloud version more expensive than alternatives"],"hi":["Self-hosting के लिए जटिल सेटअप","Zapier/Make से अधिक सीखने की कठिनाई","Advanced उपयोग के लिए तकनीकी ज्ञान जरूरी","Cloud संस्करण alternatives से अधिक महंगा"],"hinglish":["Self-hosting ke liye complex setup","Zapier/Make se zyada learning curve","Advanced use ke liye technical knowledge zaroori","Cloud version alternatives se zyada mehanga"]}',
  use_cases = '{"en":["AI-powered business process automation","Connecting multiple SaaS apps without code","Building custom chatbots with LLM integration","Data pipeline automation","Social media and email automation","Developer workflow and CI/CD integration"],"hi":["AI-पावर्ड business process automation","बिना कोड के कई SaaS ऐप connect करना","LLM इंटीग्रेशन के साथ कस्टम chatbots बनाना","Data pipeline automation","सोशल मीडिया और ईमेल automation","Developer workflow और CI/CD integration"],"hinglish":["AI-powered business process automation","Bina code ke multiple SaaS apps connect karna","LLM integration ke saath custom chatbots banana","Data pipeline automation","Social media aur email automation","Developer workflow aur CI/CD integration"]}',
  alternatives = ARRAY['zapier','make-com'],
  hindi_summary = 'n8n workflow automation का open-source विकल्प है — Zapier जैसा लेकिन self-hosted और मुफ्त। AI एजेंट nodes से AI-powered automations बनाएं। Developers के लिए परफेक्ट।'
WHERE slug = 'n8n';
"""

with open(path, 'a', encoding='utf-8') as f:
    f.write(sql)

print("Coding tools batch appended successfully.")
