# -*- coding: utf-8 -*-
"""Appends writing tools to 0011 migration."""

path = r'c:\p\p\Project\AITools\aihkya\supabase\migrations\0011_tool_content_seed_remaining.sql'

sql = """
-- ── Hemingway Editor ──────────────────────────────────────────
UPDATE public.ai_tools SET
  features = '{"en":["Readability score for your writing","Highlights complex and hard-to-read sentences","Identifies passive voice usage","Adverb and weak word detection","Bold, italic formatting toolbar","Free web version available","Desktop app for offline use"],"hi":["आपके लेखन के लिए पठनीयता स्कोर","जटिल और पढ़ने में कठिन वाक्यों को हाइलाइट करें","Passive voice उपयोग की पहचान करें","Adverb और कमज़ोर शब्द डिटेक्शन","Bold, italic फॉर्मेटिंग टूलबार","मुफ्त वेब संस्करण उपलब्ध","ऑफलाइन उपयोग के लिए डेस्कटॉप ऐप"],"hinglish":["Aapke writing ke liye readability score","Complex aur hard-to-read sentences highlight karo","Passive voice usage identify karo","Adverbs aur weak words detection","Bold, italic formatting toolbar","Free web version available","Offline use ke liye desktop app"]}',
  pros = '{"en":["Makes writing clearer and more direct","Free web version is very useful","Simple interface — no distractions","Excellent for blog posts and marketing copy","Helps non-native English writers improve"],"hi":["लेखन को स्पष्ट और प्रत्यक्ष बनाता है","मुफ्त वेब संस्करण बहुत उपयोगी है","सरल इंटरफेस — कोई विकर्षण नहीं","ब्लॉग पोस्ट और मार्केटिंग कॉपी के लिए उत्कृष्ट","गैर-मूल अंग्रेजी लेखकों को सुधारने में मदद करता है"],"hinglish":["Writing clearer aur more direct banata hai","Free web version bahut useful hai","Simple interface — koi distractions nahi","Blog posts aur marketing copy ke liye excellent","Non-native English writers ko improve karne mein madad karta hai"]}',
  cons = '{"en":["Only works for English","No AI generation — purely editing","Desktop app requires one-time purchase","Limited formatting options"],"hi":["केवल अंग्रेजी के लिए काम करता है","कोई AI जनरेशन नहीं — केवल एडिटिंग","डेस्कटॉप ऐप के लिए एकमुश्त खरीद जरूरी","सीमित फॉर्मेटिंग विकल्प"],"hinglish":["Sirf English ke liye kaam karta hai","Koi AI generation nahi — purely editing","Desktop app ke liye one-time purchase zaroori","Limited formatting options"]}',
  use_cases = '{"en":["Simplifying complex business emails","Improving blog post readability","Editing marketing and ad copy","Academic writing clarity check","Social media caption optimization","Non-native English content polishing"],"hi":["जटिल व्यापार ईमेल सरल बनाना","ब्लॉग पोस्ट पठनीयता में सुधार","मार्केटिंग और विज्ञापन कॉपी एडिटिंग","अकादमिक लेखन स्पष्टता जांच","सोशल मीडिया कैप्शन ऑप्टिमाइज़ेशन","गैर-मूल अंग्रेजी कंटेंट पॉलिशिंग"],"hinglish":["Complex business emails simplify karna","Blog post readability improve karna","Marketing aur ad copy editing","Academic writing clarity check","Social media captions optimize karna","Non-native English content polishing"]}',
  alternatives = ARRAY['grammarly','wordtune','quillbot'],
  hindi_summary = 'Hemingway Editor आपके अंग्रेज़ी लेखन को सरल और प्रभावशाली बनाता है। जटिल वाक्य, passive voice, और कमज़ोर शब्द highlight करता है। ब्लॉगर और मार्केटर्स के लिए बहुत काम का।'
WHERE slug = 'hemingway-editor';

-- ── Surfer SEO ────────────────────────────────────────────────
UPDATE public.ai_tools SET
  features = '{"en":["AI Content Editor with real-time SEO scoring","SERP Analyzer for top-ranking pages","Keyword Research with AI clustering","Content Planner with topical authority maps","AI-powered Outline Builder","Audit existing pages for SEO gaps","Integration with Google Docs and WordPress"],"hi":["रियल-टाइम SEO स्कोरिंग के साथ AI कंटेंट एडिटर","टॉप-रैंकिंग पेजों के लिए SERP Analyzer","AI क्लस्टरिंग के साथ कीवर्ड रिसर्च","टॉपिकल अथॉरिटी मैप के साथ कंटेंट प्लानर","AI-पावर्ड आउटलाइन बिल्डर","SEO गैप के लिए मौजूदा पेजों की ऑडिट","Google Docs और WordPress के साथ इंटीग्रेशन"],"hinglish":["Real-time SEO scoring ke saath AI Content Editor","Top-ranking pages ke liye SERP Analyzer","AI clustering ke saath Keyword Research","Topical authority maps ke saath Content Planner","AI-powered Outline Builder","SEO gaps ke liye existing pages audit","Google Docs aur WordPress ke saath integration"]}',
  pros = '{"en":["Best AI-assisted SEO content editor available","Data-driven recommendations from top-ranking pages","Reduces time to rank with optimized content","Great for content marketing teams","NLP-based recommendations are highly effective"],"hi":["उपलब्ध सबसे अच्छा AI-असिस्टेड SEO कंटेंट एडिटर","टॉप-रैंकिंग पेजों से डेटा-आधारित सिफारिशें","ऑप्टिमाइज़्ड कंटेंट के साथ रैंक करने का समय कम करता है","कंटेंट मार्केटिंग टीमों के लिए बेहतरीन","NLP-आधारित सिफारिशें अत्यधिक प्रभावी"],"hinglish":["Available sabse achha AI-assisted SEO content editor","Top-ranking pages se data-driven recommendations","Optimized content ke saath rank karne ka time kam karta hai","Content marketing teams ke liye great","NLP-based recommendations highly effective hain"]}',
  cons = '{"en":["Expensive — starts at $89/month","Primarily for English content — Hindi SEO limited","Requires SEO knowledge to use effectively","Some data can lag behind Google changes"],"hi":["महंगा — $89/माह से शुरू","मुख्य रूप से अंग्रेजी कंटेंट के लिए — हिंदी SEO सीमित","प्रभावी उपयोग के लिए SEO ज्ञान जरूरी","कुछ डेटा Google परिवर्तनों से पीछे रह सकता है"],"hinglish":["Mehanga — $89/month se shuru","Mainly English content ke liye — Hindi SEO limited","Effectively use karne ke liye SEO knowledge zaroori","Kuch data Google changes se peeche reh sakta hai"]}',
  use_cases = '{"en":["Creating SEO-optimized blog content","Content gap analysis for websites","Keyword research and clustering","Improving existing page rankings","Building topical authority in a niche","Content marketing strategy planning"],"hi":["SEO-ऑप्टिमाइज़्ड ब्लॉग कंटेंट बनाना","वेबसाइट के लिए कंटेंट गैप विश्लेषण","कीवर्ड रिसर्च और क्लस्टरिंग","मौजूदा पेज रैंकिंग में सुधार","एक niche में टॉपिकल अथॉरिटी बनाना","कंटेंट मार्केटिंग रणनीति प्लानिंग"],"hinglish":["SEO-optimized blog content banana","Websites ke liye content gap analysis","Keyword research aur clustering","Existing page rankings improve karna","Ek niche mein topical authority banana","Content marketing strategy planning"]}',
  alternatives = ARRAY['semrush','frase-io','ahrefs','jasper-ai'],
  hindi_summary = 'Surfer SEO ब्लॉग कंटेंट को Google पर rank करवाने के लिए सबसे अच्छा AI टूल है। यह बताता है कि टॉप रैंकिंग पेजों में क्या है और आपको क्या लिखना चाहिए।'
WHERE slug = 'surfer-seo';

-- ── Semrush ───────────────────────────────────────────────────
UPDATE public.ai_tools SET
  features = '{"en":["Comprehensive SEO and competitive intelligence","Keyword research with 20 billion keywords","Site audit and technical SEO tools","Backlink analysis and building","Social media tracking","Content marketing platform","Local SEO tools for Indian businesses"],"hi":["व्यापक SEO और प्रतिस्पर्धी इंटेलिजेंस","20 अरब कीवर्ड के साथ कीवर्ड रिसर्च","साइट ऑडिट और तकनीकी SEO टूल्स","Backlink विश्लेषण और निर्माण","सोशल मीडिया ट्रैकिंग","कंटेंट मार्केटिंग प्लेटफॉर्म","भारतीय व्यवसायों के लिए Local SEO टूल्स"],"hinglish":["Comprehensive SEO aur competitive intelligence","20 billion keywords ke saath keyword research","Site audit aur technical SEO tools","Backlink analysis aur building","Social media tracking","Content marketing platform","Indian businesses ke liye Local SEO tools"]}',
  pros = '{"en":["Most comprehensive SEO toolkit available","Excellent competitor research capabilities","Trusted by millions of SEO professionals worldwide","Good data for Indian domains","All-in-one marketing platform"],"hi":["उपलब्ध सबसे व्यापक SEO टूलकिट","उत्कृष्ट प्रतिस्पर्धी रिसर्च क्षमताएं","दुनिया भर में लाखों SEO पेशेवरों द्वारा भरोसेमंद","भारतीय डोमेन के लिए अच्छा डेटा","ऑल-इन-वन मार्केटिंग प्लेटफॉर्म"],"hinglish":["Available sabse comprehensive SEO toolkit","Excellent competitor research capabilities","Duniya bhar mein millions SEO professionals dwara trusted","Indian domains ke liye achha data","All-in-one marketing platform"]}',
  cons = '{"en":["Very expensive — $129+/month for basic plan","Steep learning curve for beginners","Data not always 100% accurate","Overkill for small Indian businesses"],"hi":["बहुत महंगा — बेसिक प्लान के लिए $129+/माह","शुरुआती लोगों के लिए सीखने की कठिनाई","डेटा हमेशा 100% सटीक नहीं","छोटे भारतीय व्यवसायों के लिए अत्यधिक"],"hinglish":["Bahut mehanga — basic plan ke liye $129+/month","Beginners ke liye steep learning curve","Data hamesha 100% accurate nahi","Chhote Indian businesses ke liye overkill"]}',
  use_cases = '{"en":["SEO agency client reporting","Competitor keyword and strategy analysis","Technical SEO audits","Link building campaigns","Content gap identification","PPC and paid search optimization"],"hi":["SEO एजेंसी क्लाइंट रिपोर्टिंग","प्रतिस्पर्धी कीवर्ड और रणनीति विश्लेषण","तकनीकी SEO ऑडिट","Link building अभियान","कंटेंट गैप पहचान","PPC और paid सर्च ऑप्टिमाइज़ेशन"],"hinglish":["SEO agency client reporting","Competitor keyword aur strategy analysis","Technical SEO audits","Link building campaigns","Content gap identification","PPC aur paid search optimization"]}',
  alternatives = ARRAY['ahrefs','surfer-seo','frase-io'],
  hindi_summary = 'Semrush दुनिया का सबसे पॉपुलर SEO टूल है। वेबसाइट की रैंकिंग बढ़ाना, competitors को analyze करना, backlinks बनाना — सब कुछ एक जगह। SEO professionals के लिए ज़रूरी।'
WHERE slug IN ('semrush-ai','semrush');

-- ── Frase.io ──────────────────────────────────────────────────
UPDATE public.ai_tools SET
  features = '{"en":["AI-powered SEO content brief generation","SERP research and competitor analysis","AI content writer with SEO optimization","Answer Engine Optimization for featured snippets","Content scoring against competitors","Keyword and question research","Team collaboration on content briefs"],"hi":["AI-पावर्ड SEO कंटेंट ब्रीफ जनरेशन","SERP रिसर्च और प्रतिस्पर्धी विश्लेषण","SEO ऑप्टिमाइज़ेशन के साथ AI कंटेंट राइटर","Featured snippets के लिए Answer Engine Optimization","प्रतिस्पर्धियों के खिलाफ कंटेंट स्कोरिंग","कीवर्ड और प्रश्न रिसर्च","कंटेंट ब्रीफ पर टीम सहयोग"],"hinglish":["AI-powered SEO content brief generation","SERP research aur competitor analysis","SEO optimization ke saath AI content writer","Featured snippets ke liye Answer Engine Optimization","Competitors ke against content scoring","Keyword aur question research","Content briefs pe team collaboration"]}',
  pros = '{"en":["More affordable than Surfer SEO","Excellent for creating detailed content briefs","Good AI writing integrated with SEO","Answer-based content optimization is unique","Simple and intuitive interface"],"hi":["Surfer SEO से अधिक किफायती","विस्तृत कंटेंट ब्रीफ बनाने के लिए उत्कृष्ट","SEO के साथ एकीकृत अच्छा AI लेखन","उत्तर-आधारित कंटेंट ऑप्टिमाइज़ेशन अनूठा है","सरल और सहज इंटरफेस"],"hinglish":["Surfer SEO se zyada affordable","Detailed content briefs banane ke liye excellent","SEO ke saath integrated AI writing","Answer-based content optimization unique hai","Simple aur intuitive interface"]}',
  cons = '{"en":["AI writing quality not as good as Jasper","Limited to content and SEO use case","Hindi content optimization very limited","Smaller user community than Semrush"],"hi":["AI लेखन गुणवत्ता Jasper जितनी अच्छी नहीं","कंटेंट और SEO use case तक सीमित","हिंदी कंटेंट ऑप्टिमाइज़ेशन बहुत सीमित","Semrush से छोटा यूज़र समुदाय"],"hinglish":["AI writing quality Jasper jitni achhi nahi","Content aur SEO use case tak limited","Hindi content optimization bahut limited","Semrush se chhota user community"]}',
  use_cases = '{"en":["Creating detailed SEO content briefs for writers","Optimizing blog posts for featured snippets","Competitive content research","Content strategy for new websites","Improving existing page rankings","Agency content workflow management"],"hi":["लेखकों के लिए विस्तृत SEO कंटेंट ब्रीफ बनाना","Featured snippets के लिए ब्लॉग पोस्ट ऑप्टिमाइज़ करना","प्रतिस्पर्धी कंटेंट रिसर्च","नई वेबसाइट के लिए कंटेंट रणनीति","मौजूदा पेज रैंकिंग में सुधार","एजेंसी कंटेंट वर्कफ्लो मैनेजमेंट"],"hinglish":["Writers ke liye detailed SEO content briefs banana","Featured snippets ke liye blog posts optimize karna","Competitive content research","Nai websites ke liye content strategy","Existing page rankings improve karna","Agency content workflow management"]}',
  alternatives = ARRAY['surfer-seo','semrush','jasper-ai'],
  hindi_summary = 'Frase.io SEO कंटेंट ब्रीफ बनाने और ब्लॉग पोस्ट को Google पर rank करवाने का किफायती AI टूल है। Surfer SEO का सस्ता विकल्प।'
WHERE slug = 'frase-io';

-- ── Wordtune ─────────────────────────────────────────────────
UPDATE public.ai_tools SET
  features = '{"en":["Rewrite sentences in multiple styles","Expand short text into full paragraphs","Shorten lengthy content","Tone adjustment (casual, formal, etc.)","Spices: add facts and statistics to writing","Chrome extension for anywhere writing","Summarizer for articles and documents"],"hi":["कई शैलियों में वाक्य फिर से लिखें","छोटे टेक्स्ट को पूरे पैराग्राफ में expand करें","लंबे कंटेंट को छोटा करें","टोन समायोजन (आकस्मिक, औपचारिक, आदि)","Spices: लेखन में तथ्य और आंकड़े जोड़ें","कहीं भी लिखने के लिए Chrome extension","लेखों और दस्तावेज़ों के लिए Summarizer"],"hinglish":["Multiple styles mein sentences rewrite karo","Short text ko full paragraphs mein expand karo","Lengthy content shorten karo","Tone adjustment (casual, formal, aadi)","Spices: writing mein facts aur statistics add karo","Kahin bhi likhne ke liye Chrome extension","Articles aur documents ke liye Summarizer"]}',
  pros = '{"en":["Multiple rewrite options in one click","Tone adjustment is very useful","Spices feature adds credibility","Free tier is quite usable","Works anywhere via Chrome extension"],"hi":["एक क्लिक में कई rewrite विकल्प","टोन समायोजन बहुत उपयोगी है","Spices फीचर विश्वसनीयता जोड़ता है","मुफ्त टियर काफी उपयोगी","Chrome extension से कहीं भी काम करता है"],"hinglish":["Ek click mein multiple rewrite options","Tone adjustment bahut useful hai","Spices feature credibility add karta hai","Free tier kaafi usable","Chrome extension se kahin bhi kaam karta hai"]}',
  cons = '{"en":["Works primarily for English","Free tier limited rewrites per day","Not as powerful for full article generation","Some rewrites can be grammatically awkward"],"hi":["मुख्य रूप से अंग्रेजी के लिए काम करता है","मुफ्त टियर प्रति दिन सीमित rewrites","पूर्ण लेख जनरेशन के लिए उतना शक्तिशाली नहीं","कुछ rewrites व्याकरणिक रूप से अजीब हो सकते हैं"],"hinglish":["Mainly English ke liye kaam karta hai","Free tier mein per day limited rewrites","Full article generation ke liye utna powerful nahi","Kuch rewrites grammatically awkward ho sakte hain"]}',
  use_cases = '{"en":["Rewriting emails for better tone","Paraphrasing academic text","Expanding bullet points into paragraphs","Shortening long corporate communications","Blog post revision and improvement","LinkedIn and social media post rewrites"],"hi":["बेहतर टोन के लिए ईमेल फिर से लिखना","अकादमिक टेक्स्ट paraphrasing","बुलेट पॉइंट को पैराग्राफ में expand करना","लंबे कॉर्पोरेट कम्युनिकेशन को छोटा करना","ब्लॉग पोस्ट संशोधन और सुधार","LinkedIn और सोशल मीडिया पोस्ट rewrites"],"hinglish":["Better tone ke liye emails rewrite karna","Academic text paraphrasing","Bullet points ko paragraphs mein expand karna","Lambe corporate communications shorten karna","Blog post revision aur improvement","LinkedIn aur social media posts rewrite karna"]}',
  alternatives = ARRAY['quillbot','grammarly','jasper-ai'],
  hindi_summary = 'Wordtune किसी भी अंग्रेज़ी टेक्स्ट को एक क्लिक में अलग-अलग style में rewrite करता है। ईमेल, ब्लॉग, सोशल मीडिया — सब को बेहतर बनाने के लिए।'
WHERE slug = 'wordtune';

-- ── Jasper AI ─────────────────────────────────────────────────
UPDATE public.ai_tools SET
  features = '{"en":["AI content generation for marketing teams","50+ templates for ads, blogs, emails, social","Brand Voice: maintains consistent tone","SEO mode with Surfer SEO integration","Campaign workflow with AI assistance","Long-form content writer","Team collaboration and campaigns"],"hi":["मार्केटिंग टीमों के लिए AI कंटेंट जनरेशन","विज्ञापन, ब्लॉग, ईमेल, सोशल के लिए 50+ टेम्पलेट","Brand Voice: सुसंगत टोन बनाए रखता है","Surfer SEO इंटीग्रेशन के साथ SEO मोड","AI सहायता के साथ Campaign वर्कफ्लो","Long-form कंटेंट राइटर","टीम सहयोग और अभियान"],"hinglish":["Marketing teams ke liye AI content generation","Ads, blogs, emails, social ke liye 50+ templates","Brand Voice: consistent tone maintain karta hai","Surfer SEO integration ke saath SEO mode","AI assistance ke saath Campaign workflow","Long-form content writer","Team collaboration aur campaigns"]}',
  pros = '{"en":["Built specifically for marketing teams","Brand Voice ensures consistent messaging","Strong template library for marketing content","Integrates with popular marketing tools","Good for scaling content production"],"hi":["विशेष रूप से मार्केटिंग टीमों के लिए बनाया गया","Brand Voice सुसंगत संदेश सुनिश्चित करता है","मार्केटिंग कंटेंट के लिए मजबूत टेम्पलेट लाइब्रेरी","लोकप्रिय मार्केटिंग टूल्स के साथ एकीकरण","कंटेंट प्रोडक्शन स्केल करने के लिए अच्छा"],"hinglish":["Especially marketing teams ke liye banaya gaya","Brand Voice consistent messaging ensure karta hai","Marketing content ke liye strong template library","Popular marketing tools ke saath integration","Content production scale karne ke liye achha"]}',
  cons = '{"en":["Expensive for individuals — starts at $49/month","Hindi content generation not great","ChatGPT has largely matched its capabilities","Steep learning curve for non-marketers"],"hi":["व्यक्तियों के लिए महंगा — $49/माह से शुरू","हिंदी कंटेंट जनरेशन अच्छी नहीं","ChatGPT ने काफी हद तक इसकी क्षमताओं से मेल खाया है","गैर-मार्केटर्स के लिए सीखने की कठिनाई"],"hinglish":["Individuals ke liye mehanga — $49/month se shuru","Hindi content generation achhi nahi","ChatGPT ne kaafi had tak iske capabilities match kar liye","Non-marketers ke liye steep learning curve"]}',
  use_cases = '{"en":["Marketing agency content production","Ad copy and email marketing campaigns","Blog post creation at scale","Product descriptions for e-commerce","Social media content calendar","Brand-consistent content across channels"],"hi":["मार्केटिंग एजेंसी कंटेंट प्रोडक्शन","विज्ञापन कॉपी और ईमेल मार्केटिंग अभियान","बड़े पैमाने पर ब्लॉग पोस्ट क्रिएशन","ई-कॉमर्स के लिए प्रोडक्ट विवरण","सोशल मीडिया कंटेंट कैलेंडर","चैनलों पर ब्रांड-सुसंगत कंटेंट"],"hinglish":["Marketing agency content production","Ad copy aur email marketing campaigns","Scale pe blog post creation","E-commerce ke liye product descriptions","Social media content calendar","Channels pe brand-consistent content"]}',
  alternatives = ARRAY['writesonic','copy-ai','chatgpt','notion-ai'],
  hindi_summary = 'Jasper AI मार्केटिंग टीमों के लिए बना AI कंटेंट राइटर है। ब्लॉग, विज्ञापन, ईमेल — 50+ टेम्पलेट से तेज़ी से कंटेंट बनाएं। Brand Voice से हर जगह एक जैसा टोन।'
WHERE slug IN ('jasper-ai','jasper');

-- ── Writesonic ────────────────────────────────────────────────
UPDATE public.ai_tools SET
  features = '{"en":["AI article and blog post writer","Chatsonic: ChatGPT alternative with web access","Botsonic: custom AI chatbot builder","100+ content templates","SEO optimization integration","Bulk content generation","API for developers"],"hi":["AI लेख और ब्लॉग पोस्ट राइटर","Chatsonic: वेब एक्सेस के साथ ChatGPT विकल्प","Botsonic: कस्टम AI चैटबॉट बिल्डर","100+ कंटेंट टेम्पलेट","SEO ऑप्टिमाइज़ेशन इंटीग्रेशन","बल्क कंटेंट जनरेशन","डेवलपर्स के लिए API"],"hinglish":["AI article aur blog post writer","Chatsonic: web access ke saath ChatGPT alternative","Botsonic: custom AI chatbot builder","100+ content templates","SEO optimization integration","Bulk content generation","Developers ke liye API"]}',
  pros = '{"en":["More affordable than Jasper","Chatsonic has real-time web access","Good template variety","API available for integration","Decent free tier"],"hi":["Jasper से अधिक किफायती","Chatsonic में रियल-टाइम वेब एक्सेस है","अच्छी टेम्पलेट विविधता","इंटीग्रेशन के लिए API उपलब्ध","ठीक-ठाक मुफ्त टियर"],"hinglish":["Jasper se zyada affordable","Chatsonic mein real-time web access hai","Achhi template variety","Integration ke liye API available","Decent free tier"]}',
  cons = '{"en":["Quality inconsistent across content types","Hindi content limited","Free tier very restricted","Customer support can be slow"],"hi":["कंटेंट प्रकारों में गुणवत्ता असंगत","हिंदी कंटेंट सीमित","मुफ्त टियर बहुत प्रतिबंधित","ग्राहक समर्थन धीमा हो सकता है"],"hinglish":["Content types mein quality inconsistent","Hindi content limited","Free tier bahut restricted","Customer support slow ho sakta hai"]}',
  use_cases = '{"en":["Blog post writing for businesses","Social media caption generation","Product descriptions at scale","Email marketing content","Landing page copy","Startup founders creating content on a budget"],"hi":["व्यवसायों के लिए ब्लॉग पोस्ट लेखन","सोशल मीडिया कैप्शन जनरेशन","बड़े पैमाने पर प्रोडक्ट विवरण","ईमेल मार्केटिंग कंटेंट","लैंडिंग पेज कॉपी","बजट में कंटेंट बना रहे स्टार्टअप फाउंडर"],"hinglish":["Businesses ke liye blog post writing","Social media captions generate karna","Scale pe product descriptions","Email marketing content","Landing page copy","Budget mein content bana rahe startup founders"]}',
  alternatives = ARRAY['jasper-ai','copy-ai','rytr','chatgpt'],
  hindi_summary = 'Writesonic ब्लॉग, विज्ञापन, ईमेल — सभी के लिए AI कंटेंट बनाता है। Jasper से किफायती और Chatsonic में रियल-टाइम वेब एक्सेस भी है।'
WHERE slug = 'writesonic';

-- ── Copy.ai ────────────────────────────────────────────────────
UPDATE public.ai_tools SET
  features = '{"en":["AI-powered marketing copy generation","90+ copywriting templates","Chat interface for content creation","Blog post wizard workflow","Social media captions and ads","Email sequences generator","Free tier with 2000 words/month"],"hi":["AI-पावर्ड मार्केटिंग कॉपी जनरेशन","90+ कॉपीराइटिंग टेम्पलेट","कंटेंट क्रिएशन के लिए चैट इंटरफेस","ब्लॉग पोस्ट विज़ार्ड वर्कफ्लो","सोशल मीडिया कैप्शन और विज्ञापन","ईमेल सीक्वेंस जनरेटर","2000 शब्द/माह के साथ मुफ्त टियर"],"hinglish":["AI-powered marketing copy generation","90+ copywriting templates","Content creation ke liye chat interface","Blog post wizard workflow","Social media captions aur ads","Email sequences generator","2000 words/month ke saath free tier"]}',
  pros = '{"en":["Great free tier — 2000 words/month","Easy to learn for beginners","Good for quick marketing copy","Multiple language support","Workflow automation features"],"hi":["बेहतरीन मुफ्त टियर — 2000 शब्द/माह","शुरुआती लोगों के लिए सीखना आसान","त्वरित मार्केटिंग कॉपी के लिए अच्छा","कई भाषा समर्थन","वर्कफ्लो ऑटोमेशन फीचर्स"],"hinglish":["Great free tier — 2000 words/month","Beginners ke liye seekhna easy","Quick marketing copy ke liye achha","Multiple language support","Workflow automation features"]}',
  cons = '{"en":["Output quality has declined compared to ChatGPT era","Limited long-form writing capability","Hindi output can be inaccurate","Pro plan required for heavy usage"],"hi":["ChatGPT युग की तुलना में आउटपुट गुणवत्ता घटी है","Long-form लेखन क्षमता सीमित","हिंदी आउटपुट अशुद्ध हो सकता है","भारी उपयोग के लिए Pro प्लान जरूरी"],"hinglish":["ChatGPT era ke comparison mein output quality giri hai","Long-form writing capability limited","Hindi output inaccurate ho sakta hai","Heavy usage ke liye Pro plan zaroori"]}',
  use_cases = '{"en":["Facebook and Google ad copy","Product descriptions for Shopify stores","Email subject lines and bodies","Social media posts","Landing page headlines","Small business marketing content"],"hi":["Facebook और Google विज्ञापन कॉपी","Shopify स्टोर के लिए प्रोडक्ट विवरण","ईमेल सब्जेक्ट लाइन और बॉडी","सोशल मीडिया पोस्ट","लैंडिंग पेज हेडलाइन","छोटे व्यापार मार्केटिंग कंटेंट"],"hinglish":["Facebook aur Google ad copy","Shopify stores ke liye product descriptions","Email subject lines aur bodies","Social media posts","Landing page headlines","Chhote business marketing content"]}',
  alternatives = ARRAY['jasper-ai','writesonic','rytr','chatgpt'],
  hindi_summary = 'Copy.ai मार्केटिंग कॉपी — विज्ञापन, ईमेल, सोशल पोस्ट — AI से बनाने का टूल है। मुफ्त में 2000 शब्द/माह मिलते हैं, शुरुआती के लिए बेहतरीन।'
WHERE slug IN ('copy-ai','copyai');

-- ── Rytr ──────────────────────────────────────────────────────
UPDATE public.ai_tools SET
  features = '{"en":["AI writing in 40+ use cases and 30+ languages","Budget-friendly pricing from $9/month","SEO meta titles and descriptions","Email and newsletter writing","Blog post outlines and paragraphs","Social media captions","Free tier with 10,000 characters/month"],"hi":["40+ use cases और 30+ भाषाओं में AI लेखन","$9/माह से बजट-अनुकूल कीमत","SEO मेटा टाइटल और विवरण","ईमेल और न्यूज़लेटर लेखन","ब्लॉग पोस्ट आउटलाइन और पैराग्राफ","सोशल मीडिया कैप्शन","10,000 वर्ण/माह के साथ मुफ्त टियर"],"hinglish":["40+ use cases aur 30+ languages mein AI writing","$9/month se budget-friendly pricing","SEO meta titles aur descriptions","Email aur newsletter writing","Blog post outlines aur paragraphs","Social media captions","10,000 characters/month ke saath free tier"]}',
  pros = '{"en":["Most affordable AI writing tool","Good free tier","30+ language support","Simple interface","Good for freelancers on a budget"],"hi":["सबसे किफायती AI लेखन टूल","अच्छा मुफ्त टियर","30+ भाषा समर्थन","सरल इंटरफेस","बजट पर फ्रीलांसर के लिए अच्छा"],"hinglish":["Sabse affordable AI writing tool","Achha free tier","30+ language support","Simple interface","Budget pe freelancers ke liye achha"]}',
  cons = '{"en":["Writing quality below Jasper and ChatGPT","Limited control over output style","Not suitable for long-form content","Hindi output needs improvement"],"hi":["लेखन गुणवत्ता Jasper और ChatGPT से कम","आउटपुट स्टाइल पर सीमित नियंत्रण","Long-form कंटेंट के लिए उपयुक्त नहीं","हिंदी आउटपुट में सुधार की जरूरत"],"hinglish":["Writing quality Jasper aur ChatGPT se below","Output style pe limited control","Long-form content ke liye suitable nahi","Hindi output mein improvement ki zaroorat"]}',
  use_cases = '{"en":["Short-form marketing copy on a budget","Freelance writers for quick drafts","Social media management for small businesses","Email marketing for startups","Blog topic outlines","Students and beginners learning AI writing"],"hi":["बजट में शॉर्ट-फॉर्म मार्केटिंग कॉपी","त्वरित ड्राफ्ट के लिए फ्रीलांस लेखक","छोटे व्यवसायों के लिए सोशल मीडिया मैनेजमेंट","स्टार्टअप के लिए ईमेल मार्केटिंग","ब्लॉग विषय आउटलाइन","AI लेखन सीखने वाले छात्र और शुरुआती"],"hinglish":["Budget mein short-form marketing copy","Quick drafts ke liye freelance writers","Small businesses ke liye social media management","Startups ke liye email marketing","Blog topic outlines","AI writing seekhne wale students aur beginners"]}',
  alternatives = ARRAY['copy-ai','writesonic','jasper-ai'],
  hindi_summary = 'Rytr सबसे सस्ता AI लेखन टूल है — सिर्फ $9/माह या मुफ्त में 10,000 वर्ण। फ्रीलांसर और छोटे व्यवसायों के लिए मार्केटिंग कंटेंट बनाने का किफायती तरीका।'
WHERE slug = 'rytr';

-- ── QuillBot ──────────────────────────────────────────────────
UPDATE public.ai_tools SET
  features = '{"en":["AI paraphrasing in 7 modes (Standard, Fluency, Formal, etc.)","Grammar checker and fixer","Summarizer for articles and documents","Citation generator (APA, MLA, Chicago)","AI writing detector","Plagiarism checker","Chrome extension for anywhere use"],"hi":["7 मोड में AI paraphrasing (Standard, Fluency, Formal, आदि)","व्याकरण जांचकर्ता और फिक्सर","लेखों और दस्तावेज़ों के लिए Summarizer","उद्धरण जनरेटर (APA, MLA, Chicago)","AI लेखन डिटेक्टर","साहित्यिक चोरी जांचकर्ता","कहीं भी उपयोग के लिए Chrome extension"],"hinglish":["7 modes mein AI paraphrasing (Standard, Fluency, Formal, aadi)","Grammar checker aur fixer","Articles aur documents ke liye Summarizer","Citation generator (APA, MLA, Chicago)","AI writing detector","Plagiarism checker","Kahin bhi use ke liye Chrome extension"]}',
  pros = '{"en":["Best paraphrasing tool available","Free tier very useful for students","Grammar checker integrated","Citation tool is a bonus for academics","Used by millions of students worldwide"],"hi":["उपलब्ध सबसे अच्छा paraphrasing टूल","छात्रों के लिए मुफ्त टियर बहुत उपयोगी","व्याकरण जांचकर्ता एकीकृत","उद्धरण टूल शिक्षाविदों के लिए बोनस है","दुनिया भर में लाखों छात्रों द्वारा उपयोग किया जाता है"],"hinglish":["Available best paraphrasing tool","Students ke liye free tier bahut useful","Grammar checker integrated","Citation tool academics ke liye bonus hai","Duniya bhar mein millions students dwara use kiya jata hai"]}',
  cons = '{"en":["Free version limits paraphrasing length","Not for generating original content","Hindi paraphrasing needs improvement","Some rewrites change meaning unintentionally"],"hi":["मुफ्त संस्करण paraphrasing लंबाई सीमित करता है","मूल कंटेंट जनरेट करने के लिए नहीं","हिंदी paraphrasing में सुधार की जरूरत","कुछ rewrites अनजाने में अर्थ बदलते हैं"],"hinglish":["Free version paraphrasing length limit karta hai","Original content generate karne ke liye nahi","Hindi paraphrasing mein improvement ki zaroorat","Kuch rewrites unintentionally meaning change karte hain"]}',
  use_cases = '{"en":["Student essay paraphrasing and rewriting","Research paper language improvement","Summarizing long academic articles","Avoiding plagiarism in academic writing","Email and document rewriting","Blog post tone adjustment"],"hi":["छात्र निबंध paraphrasing और पुनर्लेखन","शोध पत्र भाषा सुधार","लंबे अकादमिक लेखों का सारांश","अकादमिक लेखन में साहित्यिक चोरी से बचना","ईमेल और दस्तावेज़ पुनर्लेखन","ब्लॉग पोस्ट टोन समायोजन"],"hinglish":["Student essay paraphrasing aur rewriting","Research paper language improvement","Lambe academic articles summarize karna","Academic writing mein plagiarism se bachna","Email aur document rewriting","Blog post tone adjustment"]}',
  alternatives = ARRAY['grammarly','wordtune','hemingway-editor'],
  hindi_summary = 'QuillBot दुनिया का सबसे पॉपुलर paraphrasing AI टूल है। भारत में छात्रों के बीच बहुत लोकप्रिय — अंग्रेज़ी लेखन को बेहतर बनाने, plagiarism से बचने, और अकादमिक काम के लिए।'
WHERE slug = 'quillbot';

-- ── Napkin AI ─────────────────────────────────────────────────
UPDATE public.ai_tools SET
  features = '{"en":["Convert text into visual diagrams and infographics","Auto-generates visuals from pasted content","Multiple visual styles (flowcharts, mind maps, etc.)","Export to SVG, PNG and PDF","Edit visuals with drag-and-drop","Free to use","Perfect for presentations and documents"],"hi":["टेक्स्ट को विज़ुअल डायग्राम और इन्फोग्राफिक में बदलें","पेस्ट किए कंटेंट से स्वचालित विज़ुअल जनरेट करें","कई विज़ुअल स्टाइल (flowcharts, mind maps, आदि)","SVG, PNG और PDF में export","ड्रैग-एंड-ड्रॉप से विज़ुअल एडिट करें","उपयोग करने के लिए मुफ्त","प्रेज़ेंटेशन और दस्तावेज़ों के लिए परफेक्ट"],"hinglish":["Text ko visual diagrams aur infographics mein badlo","Pasted content se automatically visuals generate karo","Multiple visual styles (flowcharts, mind maps, aadi)","SVG, PNG aur PDF mein export","Drag-and-drop se visuals edit karo","Use karne ke liye free","Presentations aur documents ke liye perfect"]}',
  pros = '{"en":["Unique and impressive text-to-visual conversion","Completely free","Great for non-designers","Saves huge time in creating infographics","Works well for presentations and reports"],"hi":["अनूठा और प्रभावशाली टेक्स्ट-टू-विज़ुअल रूपांतरण","बिल्कुल मुफ्त","गैर-डिज़ाइनर के लिए बेहतरीन","इन्फोग्राफिक बनाने में बड़ा समय बचाता है","प्रेज़ेंटेशन और रिपोर्ट के लिए अच्छा काम करता है"],"hinglish":["Unique aur impressive text-to-visual conversion","Bilkul free","Non-designers ke liye great","Infographics banana mein bahut time bachata hai","Presentations aur reports ke liye achha kaam karta hai"]}',
  cons = '{"en":["Still in early stages — limited customization","Not for complex or technical diagrams","Limited template variety","Export options could be more comprehensive"],"hi":["अभी शुरुआती अवस्था में — सीमित कस्टमाइज़ेशन","जटिल या तकनीकी डायग्राम के लिए नहीं","सीमित टेम्पलेट विविधता","export विकल्प अधिक व्यापक हो सकते थे"],"hinglish":["Abhi early stages mein — limited customization","Complex ya technical diagrams ke liye nahi","Limited template variety","Export options zyada comprehensive ho sakte the"]}',
  use_cases = '{"en":["Creating infographics for blog posts","Visualizing processes and workflows","Presentation slide visuals","Explaining complex concepts simply","Social media educational content","Business report diagrams"],"hi":["ब्लॉग पोस्ट के लिए इन्फोग्राफिक बनाना","प्रक्रियाओं और वर्कफ्लो को विज़ुअलाइज़ करना","प्रेज़ेंटेशन स्लाइड विज़ुअल","जटिल अवधारणाओं को सरलता से समझाना","सोशल मीडिया शैक्षिक कंटेंट","बिज़नेस रिपोर्ट डायग्राम"],"hinglish":["Blog posts ke liye infographics banana","Processes aur workflows visualize karna","Presentation slide visuals","Complex concepts simply explain karna","Social media educational content","Business report diagrams"]}',
  alternatives = ARRAY['canva-ai-magic-studio','gamma-app','tome'],
  hindi_summary = 'Napkin AI टेक्स्ट को डायग्राम और इन्फोग्राफिक में बदलता है — बिल्कुल मुफ्त। ब्लॉग, प्रेज़ेंटेशन, और रिपोर्ट को विज़ुअल से समृद्ध बनाने का नया तरीका।'
WHERE slug = 'napkin-ai';

-- ── Gamma ─────────────────────────────────────────────────────
UPDATE public.ai_tools SET
  features = '{"en":["Generate full presentations from text prompts","AI-designed slides with professional layouts","Web-native presentations (not PowerPoint)","Easily embed media, charts and videos","One-click redesign of entire deck","Export to PDF and PowerPoint","Share as link with analytics"],"hi":["टेक्स्ट प्रॉम्प्ट से पूरी प्रेज़ेंटेशन जनरेट करें","प्रोफेशनल लेआउट के साथ AI-डिज़ाइन किए स्लाइड","वेब-नेटिव प्रेज़ेंटेशन (PowerPoint नहीं)","मीडिया, चार्ट और वीडियो आसानी से embed करें","पूरे डेक का एक-क्लिक redesign","PDF और PowerPoint में export","analytics के साथ लिंक के रूप में शेयर करें"],"hinglish":["Text prompts se full presentations generate karo","Professional layouts ke saath AI-designed slides","Web-native presentations (PowerPoint nahi)","Media, charts aur videos easily embed karo","Poore deck ka one-click redesign","PDF aur PowerPoint mein export","Analytics ke saath link ke roop mein share karo"]}',
  pros = '{"en":["Fastest way to create a presentation","AI generates entire deck from outline","Modern web-native format looks great online","Free tier is quite generous","Easy to share and collaborate"],"hi":["प्रेज़ेंटेशन बनाने का सबसे तेज़ तरीका","AI आउटलाइन से पूरा डेक बनाता है","आधुनिक वेब-नेटिव फॉर्मेट ऑनलाइन बेहतरीन दिखता है","मुफ्त टियर काफी उदार है","शेयर और सहयोग करना आसान"],"hinglish":["Presentations banana ka sabse fast tarika","AI outline se poora deck banata hai","Modern web-native format online great lagta hai","Free tier kaafi generous hai","Share aur collaborate karna easy"]}',
  cons = '{"en":["Less customization than PowerPoint","Export to PowerPoint loses some formatting","Requires internet connection","Not ideal for very data-heavy presentations"],"hi":["PowerPoint से कम कस्टमाइज़ेशन","PowerPoint में export कुछ फॉर्मेटिंग खोता है","इंटरनेट कनेक्शन जरूरी","बहुत डेटा-हैवी प्रेज़ेंटेशन के लिए आदर्श नहीं"],"hinglish":["PowerPoint se kam customization","PowerPoint mein export kuch formatting khota hai","Internet connection zaroori","Bahut data-heavy presentations ke liye ideal nahi"]}',
  use_cases = '{"en":["Quick pitch decks for startups","Team meeting presentations","Educational slides and lessons","Product launch and demo decks","Client proposals","Internal business updates"],"hi":["स्टार्टअप के लिए त्वरित पिच डेक","टीम मीटिंग प्रेज़ेंटेशन","शैक्षिक स्लाइड और पाठ","प्रोडक्ट लॉन्च और डेमो डेक","क्लाइंट प्रपोज़ल","आंतरिक बिज़नेस अपडेट"],"hinglish":["Startups ke liye quick pitch decks","Team meeting presentations","Educational slides aur lessons","Product launch aur demo decks","Client proposals","Internal business updates"]}',
  alternatives = ARRAY['beautiful-ai','tome','napkin-ai','canva-ai-magic-studio'],
  hindi_summary = 'Gamma AI से मिनटों में प्रोफेशनल प्रेज़ेंटेशन बनाता है। टेक्स्ट या आउटलाइन दो, AI पूरी slides बना देगा। स्टार्टअप pitch और टीम meetings के लिए परफेक्ट।'
WHERE slug IN ('gamma-app','gamma');

-- ── Tome ──────────────────────────────────────────────────────
UPDATE public.ai_tools SET
  features = '{"en":["AI-powered storytelling and presentation format","Generate presentations from text prompts","Embed live data, figma, videos and tweets","Page-by-page narrative format","Collaboration and commenting","Analytics on who viewed your presentation","Free to start"],"hi":["AI-पावर्ड स्टोरीटेलिंग और प्रेज़ेंटेशन फॉर्मेट","टेक्स्ट प्रॉम्प्ट से प्रेज़ेंटेशन जनरेट करें","लाइव डेटा, figma, वीडियो और tweets embed करें","पेज-बाय-पेज नैरेटिव फॉर्मेट","सहयोग और टिप्पणी","कौन आपकी प्रेज़ेंटेशन देखा इस पर analytics","शुरू करने के लिए मुफ्त"],"hinglish":["AI-powered storytelling aur presentation format","Text prompts se presentations generate karo","Live data, figma, videos aur tweets embed karo","Page-by-page narrative format","Collaboration aur commenting","Kaun aapki presentation dekha uske analytics","Shuru karne ke liye free"]}',
  pros = '{"en":["Great for narrative-style presentations","Embed live content keeps decks fresh","AI generation is fast and clean","Good for startup pitches and proposals","Free tier available"],"hi":["नैरेटिव-स्टाइल प्रेज़ेंटेशन के लिए बेहतरीन","लाइव कंटेंट embed डेक को ताज़ा रखता है","AI जनरेशन तेज़ और साफ है","स्टार्टअप पिच और प्रपोज़ल के लिए अच्छा","मुफ्त टियर उपलब्ध"],"hinglish":["Narrative-style presentations ke liye great","Live content embed decks fresh rakhta hai","AI generation fast aur clean hai","Startup pitches aur proposals ke liye achha","Free tier available"]}',
  cons = '{"en":["Less control over design than Gamma","Not ideal for data-heavy slides","Export options limited","Smaller user base than competitors"],"hi":["Gamma से डिज़ाइन पर कम नियंत्रण","डेटा-हैवी स्लाइड के लिए आदर्श नहीं","export विकल्प सीमित","प्रतिस्पर्धियों से छोटा यूज़र आधार"],"hinglish":["Gamma se design pe kam control","Data-heavy slides ke liye ideal nahi","Export options limited","Competitors se chhota user base"]}',
  use_cases = '{"en":["Investor pitch and fundraising decks","Startup product demos","Sales proposals with live data","Team update presentations","Thought leadership content","Brand storytelling"],"hi":["निवेशक पिच और fundraising डेक","स्टार्टअप प्रोडक्ट डेमो","लाइव डेटा के साथ सेल्स प्रपोज़ल","टीम अपडेट प्रेज़ेंटेशन","Thought leadership कंटेंट","ब्रांड स्टोरीटेलिंग"],"hinglish":["Investor pitch aur fundraising decks","Startup product demos","Live data ke saath sales proposals","Team update presentations","Thought leadership content","Brand storytelling"]}',
  alternatives = ARRAY['gamma-app','beautiful-ai','napkin-ai'],
  hindi_summary = 'Tome AI से स्टोरी-स्टाइल प्रेज़ेंटेशन बनाता है। स्टार्टअप इनवेस्टर पिच और सेल्स प्रपोज़ल के लिए — लाइव डेटा और वीडियो embed के साथ।'
WHERE slug IN ('tome-ai','tome');

-- ── Jenni AI ──────────────────────────────────────────────────
UPDATE public.ai_tools SET
  features = '{"en":["AI writing assistant for academic papers","Auto-complete and suggest text as you write","Cite with AI — auto-generate citations","Research from 200M+ academic papers","Paraphrasing and summarization","PDF import and chat","Supports APA, MLA, Chicago, Harvard citation styles"],"hi":["अकादमिक पेपर के लिए AI लेखन असिस्टेंट","लिखते समय टेक्स्ट ऑटो-कम्पलीट और सुझाव दें","Cite with AI — ऑटो-जनरेट citations","200M+ अकादमिक पेपर से रिसर्च","Paraphrasing और summarization","PDF import और चैट","APA, MLA, Chicago, Harvard citation styles समर्थन"],"hinglish":["Academic papers ke liye AI writing assistant","Likhte samay text auto-complete aur suggest karo","Cite with AI — auto-generate citations","200M+ academic papers se research","Paraphrasing aur summarization","PDF import aur chat","APA, MLA, Chicago, Harvard citation styles support"]}',
  pros = '{"en":["Purpose-built for academic writing — unmatched","Auto-citation saves hours of manual work","Access to millions of research papers","Great for PhD and research students","Reduces writer''s block in academic writing"],"hi":["अकादमिक लेखन के लिए खास बना — बेमिसाल","ऑटो-citation मैन्युअल काम में घंटों बचाता है","लाखों शोध पत्रों तक पहुंच","PhD और शोध छात्रों के लिए बेहतरीन","अकादमिक लेखन में writer''s block कम करता है"],"hinglish":["Academic writing ke liye specially banaya — beemisaal","Auto-citation manual work mein ghante bachata hai","Millions research papers ka access","PhD aur research students ke liye great","Academic writing mein writer''s block kam karta hai"]}',
  cons = '{"en":["Primarily for English academic writing","Paid subscription needed for full access","Not suitable for non-academic content","Some citation formatting needs verification"],"hi":["मुख्य रूप से अंग्रेजी अकादमिक लेखन के लिए","पूर्ण पहुंच के लिए paid सब्सक्रिप्शन जरूरी","गैर-अकादमिक कंटेंट के लिए उपयुक्त नहीं","कुछ citation फॉर्मेटिंग को सत्यापन की जरूरत"],"hinglish":["Mainly English academic writing ke liye","Full access ke liye paid subscription zaroori","Non-academic content ke liye suitable nahi","Kuch citation formatting ko verification ki zaroorat"]}',
  use_cases = '{"en":["PhD and Masters thesis writing","Research paper drafting","Literature review creation","Grant proposal writing","Academic blog and journal articles","University assignment writing"],"hi":["PhD और Masters thesis लेखन","शोध पत्र ड्राफ्टिंग","Literature review क्रिएशन","Grant प्रपोज़ल लेखन","अकादमिक ब्लॉग और जर्नल लेख","विश्वविद्यालय असाइनमेंट लेखन"],"hinglish":["PhD aur Masters thesis writing","Research paper drafting","Literature review creation","Grant proposal writing","Academic blog aur journal articles","University assignment writing"]}',
  alternatives = ARRAY['chatgpt','claude','quillbot','elicit'],
  hindi_summary = 'Jenni AI रिसर्च पेपर और थीसिस लिखने के लिए बना AI है। ऑटोमेटिक citations, 200M+ रिसर्च पेपर से रेफरेंस — PhD और रिसर्च स्टूडेंट्स के लिए बेहतरीन।'
WHERE slug = 'jenni-ai';
"""

with open(path, 'a', encoding='utf-8') as f:
    f.write(sql)

print("Writing tools batch appended successfully.")
