# -*- coding: utf-8 -*-
"""Appends remaining tool content to 0011 migration."""

import os

path = r'c:\p\p\Project\AITools\aihkya\supabase\migrations\0011_tool_content_seed_remaining.sql'

sql = """

-- ── Pika ──────────────────────────────────────────────────────
UPDATE public.ai_tools SET
  features = '{"en":["Text-to-video generation in seconds","Image-to-video animation","Video effects and transitions","Lip sync and voice-over tools","Camera motion controls","Extend and modify existing videos","Free tier available"],"hi":["सेकंड में टेक्स्ट-टू-वीडियो जनरेशन","इमेज-टू-वीडियो एनिमेशन","वीडियो इफेक्ट और ट्रांज़िशन","लिप सिंक और वॉइस-ओवर टूल्स","कैमरा मोशन कंट्रोल","मौजूदा वीडियो extend और modify करें","मुफ्त टियर उपलब्ध"],"hinglish":["Seconds mein text-to-video generation","Image-to-video animation","Video effects aur transitions","Lip sync aur voice-over tools","Camera motion controls","Existing videos extend aur modify karo","Free tier available"]}',
  pros = '{"en":["Easy-to-use interface for beginners","Good video quality for short clips","Creative effects and camera controls","Free tier lets you experiment","Fast generation"],"hi":["शुरुआती लोगों के लिए उपयोग में आसान इंटरफेस","छोटे क्लिप के लिए अच्छी वीडियो गुणवत्ता","क्रिएटिव इफेक्ट और कैमरा कंट्रोल","मुफ्त टियर प्रयोग करने देता है","तेज़ जनरेशन"],"hinglish":["Beginners ke liye easy-to-use interface","Short clips ke liye achhi video quality","Creative effects aur camera controls","Free tier experiment karne deta hai","Fast generation"]}',
  cons = '{"en":["Videos limited to short duration","AI artifacts in complex scenes","Watermark on free tier","Not for professional production"],"hi":["वीडियो छोटी अवधि तक सीमित","जटिल दृश्यों में AI artifacts","मुफ्त टियर पर वॉटरमार्क","प्रोफेशनल प्रोडक्शन के लिए नहीं"],"hinglish":["Videos short duration tak limited","Complex scenes mein AI artifacts","Free tier pe watermark","Professional production ke liye nahi"]}',
  use_cases = '{"en":["Social media short video content","Animating product images for ads","Reels and Shorts creation","Concept visualization","Turning photos into moving videos","Fun personal content"],"hi":["सोशल मीडिया शॉर्ट वीडियो कंटेंट","विज्ञापनों के लिए प्रोडक्ट इमेज एनिमेट करना","Reels और Shorts क्रिएशन","कॉन्सेप्ट विज़ुअलाइज़ेशन","फोटो को मूविंग वीडियो में बदलना","मज़ेदार व्यक्तिगत कंटेंट"],"hinglish":["Social media short video content","Ads ke liye product images animate karna","Reels aur Shorts creation","Concept visualization","Photos ko moving videos mein badalna","Fun personal content"]}',
  alternatives = ARRAY['runway-ml','sora','luma-ai','kling-ai'],
  hindi_summary = 'Pika AI से शॉर्ट वीडियो बनाने का एक आसान और मज़ेदार टूल है। इमेज को एनिमेट करो, टेक्स्ट से वीडियो बनाओ — Instagram Reels और YouTube Shorts के लिए परफेक्ट।'
WHERE slug = 'pika';

-- ── Sora ─────────────────────────────────────────────────────
UPDATE public.ai_tools SET
  features = '{"en":["High-quality text-to-video up to 1 minute","Cinematic quality with realistic physics","Storyboard: create scenes and edit timeline","Image-to-video animation","Remix existing videos","Loop and blend video clips","Available with ChatGPT Plus subscription"],"hi":["1 मिनट तक उच्च-गुणवत्ता टेक्स्ट-टू-वीडियो","यथार्थवादी भौतिकी के साथ सिनेमाई गुणवत्ता","Storyboard: दृश्य बनाएं और टाइमलाइन संपादित करें","इमेज-टू-वीडियो एनिमेशन","मौजूदा वीडियो रीमिक्स करें","वीडियो क्लिप Loop और blend करें","ChatGPT Plus सब्सक्रिप्शन के साथ उपलब्ध"],"hinglish":["1 minute tak high-quality text-to-video","Realistic physics ke saath cinematic quality","Storyboard: scenes banao aur timeline edit karo","Image-to-video animation","Existing videos remix karo","Video clips loop aur blend karo","ChatGPT Plus subscription ke saath available"]}',
  pros = '{"en":["Best video quality in any AI tool","Realistic motion and physics","Longer video duration than competitors","Integrated with ChatGPT","Storyboard enables narrative control"],"hi":["किसी भी AI टूल में सबसे अच्छी वीडियो गुणवत्ता","यथार्थवादी मोशन और भौतिकी","प्रतिस्पर्धियों से लंबी वीडियो अवधि","ChatGPT के साथ एकीकृत","Storyboard कथा नियंत्रण सक्षम करता है"],"hinglish":["Kisi bhi AI tool mein best video quality","Realistic motion aur physics","Competitors se lamba video duration","ChatGPT ke saath integrated","Storyboard narrative control enable karta hai"]}',
  cons = '{"en":["Requires ChatGPT Plus subscription","Not available in all countries","Limited generation time per month","Cannot yet create broadcast-quality content"],"hi":["ChatGPT Plus सब्सक्रिप्शन जरूरी","अभी सभी देशों में उपलब्ध नहीं","प्रति माह सीमित जनरेशन समय","अभी ब्रॉडकास्ट-क्वालिटी कंटेंट नहीं बना सकता"],"hinglish":["ChatGPT Plus subscription zaroori","Abhi sabhi countries mein available nahi","Per month limited generation time","Abhi broadcast-quality content nahi bana sakta"]}',
  use_cases = '{"en":["High-quality short film production","Marketing video creation","Music video concept visualization","Real estate visualization","Product showcase videos","Educational content"],"hi":["उच्च-गुणवत्ता शॉर्ट फिल्म प्रोडक्शन","मार्केटिंग वीडियो क्रिएशन","म्यूज़िक वीडियो कॉन्सेप्ट विज़ुअलाइज़ेशन","रियल एस्टेट विज़ुअलाइज़ेशन","प्रोडक्ट शोकेस वीडियो","शैक्षिक कंटेंट"],"hinglish":["High-quality short film production","Marketing video creation","Music video concept visualization","Real estate visualization","Product showcase videos","Educational content"]}',
  alternatives = ARRAY['runway-ml','pika','luma-ai','kling-ai'],
  hindi_summary = 'Sora OpenAI का AI वीडियो जनरेशन टूल है जो सबसे रियलिस्टिक AI वीडियो बनाता है। ChatGPT Plus के साथ उपलब्ध, टेक्स्ट से सिनेमाई क्वालिटी के वीडियो।'
WHERE slug = 'sora';

-- ── Luma AI ──────────────────────────────────────────────────
UPDATE public.ai_tools SET
  features = '{"en":["Dream Machine: high-quality text and image to video","Photorealistic and cinematic video generation","Camera motion controls","Fast generation speed","Extend video clips automatically","Free tier with daily credits","NeRF 3D captures from phone video"],"hi":["Dream Machine: उच्च-गुणवत्ता टेक्स्ट और इमेज टू वीडियो","फोटोरियलिस्टिक और सिनेमाई वीडियो जनरेशन","कैमरा मोशन कंट्रोल","तेज़ जनरेशन स्पीड","वीडियो क्लिप अपने आप extend करें","दैनिक क्रेडिट के साथ मुफ्त टियर","फोन वीडियो से NeRF 3D कैप्चर"],"hinglish":["Dream Machine: high-quality text aur image to video","Photorealistic aur cinematic video generation","Camera motion controls","Fast generation speed","Video clips automatically extend karo","Daily credits ke saath free tier","Phone video se NeRF 3D captures"]}',
  pros = '{"en":["Excellent photorealistic video quality","Fast generation speed","Free tier is very usable","Good camera motion presets","Strong for product and commercial videos"],"hi":["उत्कृष्ट फोटोरियलिस्टिक वीडियो गुणवत्ता","तेज़ जनरेशन स्पीड","मुफ्त टियर बहुत उपयोगी","अच्छे कैमरा मोशन प्रीसेट","प्रोडक्ट और कमर्शियल वीडियो के लिए मजबूत"],"hinglish":["Excellent photorealistic video quality","Fast generation speed","Free tier bahut usable","Achhe camera motion presets","Product aur commercial videos ke liye strong"]}',
  cons = '{"en":["Free credits run out quickly","Videos limited to short clips by default","Occasional character inconsistency across clips","No audio generation"],"hi":["मुफ्त क्रेडिट जल्दी खत्म","वीडियो डिफ़ॉल्ट रूप से 5 सेकंड तक सीमित","क्लिप के बीच पात्रों में कभी-कभी असंगति","कोई ऑडियो जनरेशन नहीं"],"hinglish":["Free credits jaldi khatam","Videos default mein short clips tak limited","Clips ke beech kabhi kabhi inconsistency","Koi audio generation nahi"]}',
  use_cases = '{"en":["Product advertisement videos","Real estate walkthroughs","Social media video content","Film pre-visualization","Animating still photography","Brand story videos"],"hi":["प्रोडक्ट विज्ञापन वीडियो","रियल एस्टेट वॉकथ्रू","सोशल मीडिया वीडियो कंटेंट","फिल्म प्री-विज़ुअलाइज़ेशन","स्थिर फोटोग्राफी एनिमेट करना","ब्रांड स्टोरी वीडियो"],"hinglish":["Product advertisement videos","Real estate walkthroughs","Social media video content","Film pre-visualization","Still photography animate karna","Brand story videos"]}',
  alternatives = ARRAY['runway-ml','pika','sora','kling-ai'],
  hindi_summary = 'Luma AI का Dream Machine फोटोरियलिस्टिक वीडियो बनाता है — प्रोडक्ट एड्स और ब्रांड वीडियो के लिए बेहतरीन। फ्री टियर में अच्छे क्रेडिट मिलते हैं।'
WHERE slug = 'luma-ai';

-- ── Kling AI ─────────────────────────────────────────────────
UPDATE public.ai_tools SET
  features = '{"en":["High-quality text-to-video up to 2 minutes","Realistic human motion and expressions","Image-to-video animation","Video extension up to 3 minutes","Camera control and motion presets","Lip sync and talking avatar","Competitive with Sora in quality"],"hi":["2 मिनट तक उच्च-गुणवत्ता टेक्स्ट-टू-वीडियो","यथार्थवादी मानव मोशन और अभिव्यक्तियां","इमेज-टू-वीडियो एनिमेशन","3 मिनट तक वीडियो extension","कैमरा कंट्रोल और मोशन प्रीसेट","लिप सिंक और talking avatar","गुणवत्ता में Sora से प्रतिस्पर्धी"],"hinglish":["2 minutes tak high-quality text-to-video","Realistic human motion aur expressions","Image-to-video animation","3 minutes tak video extension","Camera control aur motion presets","Lip sync aur talking avatar","Quality mein Sora se competitive"]}',
  pros = '{"en":["Longer video duration than most competitors","Excellent human motion rendering","Free tier available","Strong competitor to Sora","Good camera control options"],"hi":["अधिकांश प्रतिस्पर्धियों से लंबी वीडियो अवधि","उत्कृष्ट मानव मोशन रेंडरिंग","मुफ्त टियर उपलब्ध","Sora का मजबूत प्रतिस्पर्धी","अच्छे कैमरा कंट्रोल विकल्प"],"hinglish":["Adhiktar competitors se lamba video duration","Excellent human motion rendering","Free tier available","Sora ka strong competitor","Achhe camera control options"]}',
  cons = '{"en":["Developed by Kuaishou — data privacy concerns for some","Interface in Chinese by default","Slower than Pika","Limited English support documentation"],"hi":["Kuaishou (चीनी कंपनी) द्वारा विकसित — कुछ के लिए गोपनीयता चिंताएं","इंटरफेस डिफ़ॉल्ट रूप से चीनी में","Pika से धीमा","सीमित अंग्रेजी समर्थन"],"hinglish":["Kuaishou ne banaya — kuch ke liye privacy concerns","Interface default mein Chinese mein","Pika se slow","Limited English support"]}',
  use_cases = '{"en":["Short film and cinematic production","Social media video marketing","Product demonstration videos","Virtual influencer content","Music video production","Brand storytelling campaigns"],"hi":["शॉर्ट फिल्म और सिनेमाई वीडियो","सोशल मीडिया वीडियो मार्केटिंग","प्रोडक्ट डेमो वीडियो","वर्चुअल इन्फ्लुएंसर कंटेंट","म्यूज़िक वीडियो","ब्रांड स्टोरीटेलिंग"],"hinglish":["Short film aur cinematic production","Social media video marketing","Product demonstration videos","Virtual influencer content","Music video production","Brand storytelling campaigns"]}',
  alternatives = ARRAY['runway-ml','sora','pika','luma-ai'],
  hindi_summary = 'Kling AI Sora का एक मजबूत प्रतिद्वंद्वी है — 2 मिनट तक के AI वीडियो, इंसानों की हरकतें बहुत रियलिस्टिक। फ्री टियर में भी उपलब्ध।'
WHERE slug = 'kling-ai';

-- ── Descript ─────────────────────────────────────────────────
UPDATE public.ai_tools SET
  features = '{"en":["Edit video by editing the transcript text","Overdub: clone your voice with AI","Auto-transcription in 23+ languages","Remove filler words automatically","Screen recording with built-in editor","Podcast editing workflow","AI eye contact correction"],"hi":["ट्रांसक्रिप्ट टेक्स्ट संपादित करके वीडियो संपादन","Overdub: AI से अपनी आवाज़ क्लोन करें","23+ भाषाओं में ऑटो-ट्रांसक्रिप्शन","फिलर शब्द स्वचालित रूप से हटाएं","बिल्ट-इन एडिटर के साथ स्क्रीन रिकॉर्डिंग","पॉडकास्ट एडिटिंग वर्कफ्लो","AI आई कॉन्टैक्ट करेक्शन"],"hinglish":["Transcript text edit karke video editing","Overdub: AI se apni awaaz clone karo","23+ languages mein auto-transcription","Filler words automatically hatao","Built-in editor ke saath screen recording","Podcast editing workflow","AI eye contact correction"]}',
  pros = '{"en":["Revolutionary text-based video editing","Overdub is incredibly useful for corrections","Saves hours of re-recording","Great for YouTube creators and podcasters","AI removes awkward silences automatically"],"hi":["क्रांतिकारी टेक्स्ट-आधारित वीडियो संपादन","Overdub त्रुटियों के लिए अविश्वसनीय रूप से उपयोगी","पुनः रिकॉर्डिंग में घंटों बचाता है","YouTube क्रिएटर और पॉडकास्टर के लिए बेहतरीन","AI अजीब चुप्पी स्वचालित रूप से हटाता है"],"hinglish":["Revolutionary text-based video editing","Overdub corrections ke liye incredibly useful","Re-recording mein ghante bachata hai","YouTube creators aur podcasters ke liye great","AI awkward silences automatically hatata hai"]}',
  cons = '{"en":["Subscription can be expensive","Hindi transcription needs improvement","Complex projects can be slow","Voice cloning raises ethical concerns"],"hi":["सब्सक्रिप्शन महंगी हो सकती है","हिंदी ट्रांसक्रिप्शन में सुधार की जरूरत","जटिल प्रोजेक्ट धीमे हो सकते हैं","वॉइस क्लोनिंग नैतिक चिंताएं उठाती है"],"hinglish":["Subscription expensive ho sakti hai","Hindi transcription mein improvement ki zaroorat","Complex projects slow ho sakte hain","Voice cloning ethical concerns uthata hai"]}',
  use_cases = '{"en":["YouTube video editing and production","Podcast creation and editing","Online course creation","Corporate training videos","Webinar recording and cleanup","Removing mistakes without re-recording"],"hi":["YouTube वीडियो एडिटिंग","पॉडकास्ट क्रिएशन और एडिटिंग","ऑनलाइन कोर्स क्रिएशन","कॉर्पोरेट ट्रेनिंग वीडियो","वेबिनार रिकॉर्डिंग","पुनः रिकॉर्ड किए बिना गलतियां हटाना"],"hinglish":["YouTube video editing","Podcast creation aur editing","Online course creation","Corporate training videos","Webinar recording","Dubara record kiye bina mistakes hatana"]}',
  alternatives = ARRAY['capcut','opus-clip','invideo-ai','vidyo-ai'],
  hindi_summary = 'Descript वीडियो और पॉडकास्ट को टेक्स्ट की तरह एडिट करने देता है। YouTube और पॉडकास्ट creators के लिए गेम-चेंजर — जो हिस्सा हटाना हो, ट्रांसक्रिप्ट से डिलीट करो।'
WHERE slug = 'descript';

-- ── Opus Clip ────────────────────────────────────────────────
UPDATE public.ai_tools SET
  features = '{"en":["Auto-clip long videos into viral short clips","AI identifies most engaging moments","Auto-generates captions with 97% accuracy","Animated captions with multiple styles","Virality score prediction","Reframe for TikTok, Reels, Shorts","Batch processing multiple videos"],"hi":["लंबे वीडियो को वायरल शॉर्ट क्लिप में स्वचालित रूप से क्लिप करें","AI सबसे आकर्षक क्षण पहचानता है","97% सटीकता के साथ कैप्शन जनरेट करें","कई स्टाइल के साथ एनिमेटेड कैप्शन","Virality स्कोर भविष्यवाणी","TikTok, Reels, Shorts के लिए Reframe","कई वीडियो बैच प्रोसेसिंग"],"hinglish":["Long videos ko viral short clips mein auto-clip karo","AI sabse engaging moments identify karta hai","97% accuracy ke saath captions auto-generate karo","Multiple styles ke saath animated captions","Virality score prediction","TikTok, Reels, Shorts ke liye reframe","Multiple videos batch processing"]}',
  pros = '{"en":["Best tool for repurposing long-form content","Saves hours of manual editing","AI clipping is surprisingly accurate","Virality scoring helps prioritize clips","High-quality auto-captions"],"hi":["लंबे-फॉर्म कंटेंट reuse के लिए सबसे अच्छा","मैन्युअल एडिटिंग में घंटों बचाता है","AI क्लिपिंग आश्चर्यजनक रूप से सटीक","Virality स्कोरिंग सर्वोत्तम क्लिप प्राथमिकता देती है","उच्च-गुणवत्ता ऑटो-कैप्शन"],"hinglish":["Long-form content repurpose ke liye best","Manual editing mein ghante bachata hai","AI clipping surprisingly accurate","Virality scoring best clips prioritize karti hai","High-quality auto-captions"]}',
  cons = '{"en":["Free tier limits clips per month","AI selection not always best","Credits system can be confusing","Hindi and regional language support limited"],"hi":["मुफ्त टियर प्रति माह क्लिप सीमित","AI सिलेक्शन हमेशा सबसे अच्छा नहीं","क्रेडिट सिस्टम भ्रामक हो सकता है","हिंदी और क्षेत्रीय भाषा समर्थन सीमित"],"hinglish":["Free tier mein per month clips limited","AI selection hamesha best nahi","Credits system confusing ho sakta hai","Hindi aur regional language support limited"]}',
  use_cases = '{"en":["YouTube channel repurposing","Podcasters creating short teaser clips","Online course social content","Webinar highlight reels","Marketing multi-platform content","Influencers maximizing one recording"],"hi":["YouTube चैनल reuse","पॉडकास्टर शॉर्ट टीज़र क्लिप","ऑनलाइन कोर्स सोशल कंटेंट","वेबिनार हाइलाइट रील","मल्टी-प्लेटफॉर्म मार्केटिंग","एक रिकॉर्डिंग से कंटेंट maximize"],"hinglish":["YouTube channel repurposing","Podcasters ke liye short teaser clips","Online course social content","Webinar highlight reels","Multi-platform marketing","Ek recording se content maximize"]}',
  alternatives = ARRAY['vidyo-ai','capcut','descript','invideo-ai'],
  hindi_summary = 'Opus Clip लंबे YouTube वीडियो, पॉडकास्ट से AI से शॉर्ट वायरल क्लिप बनाता है। Reels और Shorts के लिए कंटेंट बनाने में घंटों का काम मिनटों में।'
WHERE slug = 'opus-clip';

-- ── Vidyo.ai ─────────────────────────────────────────────────
UPDATE public.ai_tools SET
  features = '{"en":["Auto short clips from long videos","Smart captions with 95%+ accuracy","Brand kit customization","Social media scheduling integration","Clip scoring and virality prediction","Resize for all platforms","Hindi and multi-language caption support"],"hi":["लंबे वीडियो से शॉर्ट क्लिप","95%+ सटीकता के साथ स्मार्ट कैप्शन","ब्रांड किट कस्टमाइज़ेशन","सोशल मीडिया शेड्यूलिंग","क्लिप स्कोरिंग","सभी प्लेटफॉर्म के लिए resize","हिंदी और बहु-भाषा कैप्शन"],"hinglish":["Long videos se automatically short clips","95%+ accuracy ke saath smart captions","Brand kit customization","Social media scheduling","Clip scoring","Sabhi platforms ke liye resize","Hindi aur multi-language captions"]}',
  pros = '{"en":["Good Hindi caption support for Indian creators","Affordable vs Opus Clip","Brand kit great for agencies","Social scheduling saves time","Multi-language support"],"hi":["भारतीय क्रिएटर के लिए अच्छा हिंदी कैप्शन","Opus Clip से किफायती","ब्रांड किट एजेंसियों के लिए बेहतरीन","सोशल शेड्यूलिंग समय बचाती है","बहु-भाषा समर्थन"],"hinglish":["Indian creators ke liye achha Hindi caption","Opus Clip se affordable","Brand kit agencies ke liye great","Social scheduling time bachati hai","Multi-language support"]}',
  cons = '{"en":["Less known than Opus Clip","AI clip selection needs improvement","Free tier limited uploads","Interface not as polished"],"hi":["Opus Clip से कम जाना-पहचाना","AI क्लिप सिलेक्शन में सुधार जरूरी","मुफ्त टियर सीमित अपलोड","इंटरफेस कम पॉलिश्ड"],"hinglish":["Opus Clip se kam popular","AI clip selection mein improvement ki zaroorat","Free tier limited uploads","Interface kam polished"]}',
  use_cases = '{"en":["Indian creators making Hindi Reels","Brands repurposing webinar content","Digital marketing agencies","YouTube to Instagram Reels","Podcast to short clips","Corporate video content"],"hi":["Hindi Reels बनाने वाले भारतीय क्रिएटर","वेबिनार कंटेंट reuse करने वाले ब्रांड","डिजिटल मार्केटिंग एजेंसी","YouTube से Instagram Reels","पॉडकास्ट से शॉर्ट क्लिप","कॉर्पोरेट वीडियो कंटेंट"],"hinglish":["Hindi Reels banana wale Indian creators","Webinar content repurpose karne wale brands","Digital marketing agencies","YouTube se Instagram Reels","Podcast se short clips","Corporate video content"]}',
  alternatives = ARRAY['opus-clip','capcut','invideo-ai','descript'],
  hindi_summary = 'Vidyo.ai भारतीय कंटेंट क्रिएटर्स के लिए अच्छा टूल है — हिंदी कैप्शन सपोर्ट और किफायती कीमत। लंबे वीडियो से Reels के लिए शॉर्ट क्लिप बनाएं।'
WHERE slug = 'vidyo-ai';

-- ── Pictory AI ───────────────────────────────────────────────
UPDATE public.ai_tools SET
  features = '{"en":["Turn articles or scripts into short videos","AI selects relevant stock footage","Auto-add captions and subtitles","Text-to-video from blog posts","Brand intro and outro templates","AI voiceover in multiple languages","Team collaboration"],"hi":["लेख या स्क्रिप्ट को शॉर्ट वीडियो में बदलें","AI प्रासंगिक स्टॉक फुटेज चुनता है","कैप्शन स्वचालित रूप से जोड़ें","ब्लॉग पोस्ट से टेक्स्ट-टू-वीडियो","ब्रांड इंट्रो और आउट्रो टेम्पलेट","कई भाषाओं में AI वॉइसओवर","टीम सहयोग"],"hinglish":["Articles ya scripts ko short videos mein badlo","AI relevant stock footage select karta hai","Captions automatically add karo","Blog posts se text-to-video","Brand intro aur outro templates","Multiple languages mein AI voiceover","Team collaboration"]}',
  pros = '{"en":["Great for converting blog content to video","Large stock footage library","Auto-captions save significant time","Good for marketing teams","No video editing experience needed"],"hi":["ब्लॉग कंटेंट को वीडियो में बदलने के लिए बेहतरीन","बड़ी स्टॉक फुटेज लाइब्रेरी","ऑटो-कैप्शन महत्वपूर्ण समय बचाते हैं","मार्केटिंग टीम के लिए अच्छा","वीडियो एडिटिंग अनुभव की जरूरत नहीं"],"hinglish":["Blog content ko video mein convert karne ke liye great","Badi stock footage library","Auto-captions significant time bachate hain","Marketing teams ke liye achha","Video editing experience ki zaroorat nahi"]}',
  cons = '{"en":["AI footage selection can be irrelevant","Stock library not as good as custom","Premium required for best features","Limited customization"],"hi":["AI फुटेज सिलेक्शन अप्रासंगिक हो सकता है","स्टॉक लाइब्रेरी कस्टम से कम","सर्वोत्तम फीचर्स के लिए प्रीमियम जरूरी","सीमित कस्टमाइज़ेशन"],"hinglish":["AI footage selection irrelevant ho sakti hai","Stock library custom se kam","Best features ke liye premium zaroori","Limited customization"]}',
  use_cases = '{"en":["Converting blog posts to explainer videos","Video content from newsletters","Marketing video at scale","YouTube from written articles","Training and onboarding videos","Social media from text summaries"],"hi":["ब्लॉग पोस्ट को वीडियो में बदलना","न्यूज़लेटर से वीडियो कंटेंट","बड़े पैमाने पर मार्केटिंग वीडियो","लेखों से YouTube कंटेंट","ट्रेनिंग वीडियो","टेक्स्ट से सोशल मीडिया वीडियो"],"hinglish":["Blog posts ko explainer videos mein convert karna","Newsletters se video content","Scale pe marketing video","Written articles se YouTube content","Training aur onboarding videos","Text se social media video"]}',
  alternatives = ARRAY['invideo-ai','lumen5','capcut','opus-clip'],
  hindi_summary = 'Pictory AI ब्लॉग पोस्ट और आर्टिकल को वीडियो में बदलता है। कंटेंट मार्केटर्स के लिए बेहतरीन — लिखा हुआ कंटेंट वीडियो में convert करके YouTube पर शेयर करें।'
WHERE slug IN ('pictory-ai','pictory');

-- ── Synthesia ────────────────────────────────────────────────
UPDATE public.ai_tools SET
  features = '{"en":["AI avatar video without camera","140+ AI presenter avatars","120+ languages including Hindi","Custom avatar from your photo","SCORM export for LMS","Team collaboration workflows","Brand kit customization"],"hi":["कैमरा के बिना AI अवतार वीडियो","140+ AI प्रेज़ेंटर अवतार","हिंदी सहित 120+ भाषाएं","आपकी फोटो से कस्टम अवतार","LMS के लिए SCORM export","टीम सहयोग","ब्रांड किट कस्टमाइज़ेशन"],"hinglish":["Camera ke bina AI avatar video","140+ AI presenter avatars","Hindi sametan 120+ languages","Aapki photo se custom avatar","LMS ke liye SCORM export","Team collaboration","Brand kit customization"]}',
  pros = '{"en":["No camera, studio or crew needed","Hindi support for Indian businesses","Excellent for corporate training","Professional videos without production cost","Easy to update — just change script"],"hi":["कैमरा, स्टूडियो या क्रू की जरूरत नहीं","भारतीय व्यवसायों के लिए हिंदी समर्थन","कॉर्पोरेट ट्रेनिंग के लिए उत्कृष्ट","प्रोडक्शन लागत के बिना प्रोफेशनल वीडियो","अपडेट करना आसान — बस स्क्रिप्ट बदलें"],"hinglish":["Camera, studio ya crew ki zaroorat nahi","Indian businesses ke liye Hindi support","Corporate training ke liye excellent","Production costs ke bina professional videos","Update karna easy — sirf script badlo"]}',
  cons = '{"en":["Expensive — starts at $22/month","AI avatars look slightly artificial","Limited customization on base plans","Not for cinematic content"],"hi":["महंगा — $22/माह से शुरू","AI अवतार थोड़े कृत्रिम लगते हैं","बेस प्लान पर सीमित कस्टमाइज़ेशन","सिनेमाई कंटेंट के लिए नहीं"],"hinglish":["Mehanga — $22/month se shuru","AI avatars thode artificial lagte hain","Base plans pe limited customization","Cinematic content ke liye nahi"]}',
  use_cases = '{"en":["Employee onboarding and training","Product demo videos","E-learning course creation","Internal corporate communications","Customer support FAQ videos","Multilingual content for global teams"],"hi":["कर्मचारी ऑनबोर्डिंग और ट्रेनिंग","प्रोडक्ट डेमो वीडियो","ई-लर्निंग कोर्स क्रिएशन","आंतरिक कॉर्पोरेट कम्युनिकेशन","कस्टमर सपोर्ट FAQ वीडियो","वैश्विक टीमों के लिए बहुभाषी कंटेंट"],"hinglish":["Employee onboarding aur training","Product demo videos","E-learning course creation","Internal corporate communications","Customer support FAQ videos","Global teams ke liye multilingual content"]}',
  alternatives = ARRAY['heygen','d-id','invideo-ai','fliki'],
  hindi_summary = 'Synthesia AI अवतार से कैमरे के बिना प्रोफेशनल वीडियो बनाता है। हिंदी सहित 120+ भाषाओं में — कॉर्पोरेट ट्रेनिंग और ई-लर्निंग के लिए भारत में बहुत उपयोगी।'
WHERE slug = 'synthesia';

-- ── HeyGen ───────────────────────────────────────────────────
UPDATE public.ai_tools SET
  features = '{"en":["AI avatar video with lip sync","Video translation with lip sync in 40+ languages","Custom avatar from your own video","Talking photo — animate any portrait","Studio quality AI presenters","Voice cloning","API for automated workflows"],"hi":["लिप सिंक के साथ AI अवतार वीडियो","40+ भाषाओं में वीडियो अनुवाद","आपके वीडियो से कस्टम अवतार","Talking photo — कोई भी पोर्ट्रेट एनिमेट करें","Studio गुणवत्ता AI प्रेज़ेंटर","वॉइस क्लोनिंग","स्वचालित वर्कफ्लो के लिए API"],"hinglish":["Lip sync ke saath AI avatar video","40+ languages mein video translation","Aapke video se custom avatar","Talking photo — koi bhi portrait animate karo","Studio quality AI presenters","Voice cloning","Automated workflows ke liye API"]}',
  pros = '{"en":["Best video translation with lip sync","Custom avatar creation is convincing","Talking Photo is impressive","Good for multilingual marketing","API for programmatic video"],"hi":["लिप सिंक के साथ सबसे अच्छा वीडियो अनुवाद","कस्टम अवतार बहुत विश्वसनीय","Talking Photo प्रभावशाली है","बहुभाषी मार्केटिंग के लिए अच्छा","प्रोग्रामेटिक वीडियो के लिए API"],"hinglish":["Lip sync ke saath best video translation","Custom avatar convincing hai","Talking Photo impressive hai","Multilingual marketing ke liye achha","Programmatic video ke liye API"]}',
  cons = '{"en":["Free tier very limited","Quality varies across avatars","Expensive for high volume","Ethical concerns with deepfake-like features"],"hi":["मुफ्त टियर बहुत सीमित","अवतार के अनुसार गुणवत्ता भिन्न","उच्च वॉल्यूम के लिए महंगा","डीपफेक-जैसी क्षमताओं पर नैतिक चिंताएं"],"hinglish":["Free tier bahut limited","Avatars ke across quality vary karti hai","High volume ke liye mehanga","Deepfake-jaise features pe ethical concerns"]}',
  use_cases = '{"en":["Video dubbing into Hindi and regional languages","Personal avatar for YouTube","Customer-facing product videos","Multilingual training","Regional marketing videos","Talking photo for presentations"],"hi":["हिंदी और क्षेत्रीय भाषाओं में वीडियो डबिंग","YouTube के लिए व्यक्तिगत अवतार","ग्राहक-सामना प्रोडक्ट वीडियो","बहुभाषी ट्रेनिंग","क्षेत्रीय मार्केटिंग वीडियो","प्रेज़ेंटेशन के लिए Talking photo"],"hinglish":["Hindi aur regional languages mein video dubbing","YouTube ke liye personal avatar","Customer-facing product videos","Multilingual training","Regional marketing videos","Presentations ke liye talking photo"]}',
  alternatives = ARRAY['synthesia','d-id','invideo-ai','fliki'],
  hindi_summary = 'HeyGen किसी भी वीडियो को हिंदी सहित 40+ भाषाओं में लिप सिंक के साथ translate कर सकता है। भारतीय व्यापारों के लिए मल्टीलिंगुअल वीडियो बनाने का बेहतरीन तरीका।'
WHERE slug = 'heygen';

-- ── D-ID ──────────────────────────────────────────────────────
UPDATE public.ai_tools SET
  features = '{"en":["Animate photos to create talking avatar videos","Text-to-video with AI presenters","100+ languages including Hindi","Custom AI avatar creation","Real-time streaming avatar API","Video chat with AI agent integration","Studio for polished video content"],"hi":["बोलने वाले अवतार वीडियो के लिए फोटो एनिमेट करें","AI प्रेज़ेंटर के साथ टेक्स्ट-टू-वीडियो","हिंदी सहित 100+ भाषाएं","कस्टम AI अवतार","रियल-टाइम स्ट्रीमिंग अवतार API","AI एजेंट के साथ वीडियो चैट","Studio"],"hinglish":["Talking avatar videos ke liye photos animate karo","AI presenters ke saath text-to-video","Hindi sametan 100+ languages","Custom AI avatar","Real-time streaming avatar API","AI agent ke saath video chat","Studio"]}',
  pros = '{"en":["Talking photo works impressively well","Good Hindi voice support","Streaming API for interactive avatars","Affordable entry pricing","Quick personal avatar creation"],"hi":["Talking photo प्रभावशाली रूप से काम करता है","अच्छा हिंदी वॉइस समर्थन","इंटरैक्टिव अवतार के लिए Streaming API","किफायती कीमत","त्वरित व्यक्तिगत अवतार"],"hinglish":["Talking photo impressively kaam karta hai","Achha Hindi voice support","Interactive avatars ke liye Streaming API","Affordable pricing","Quick personal avatar"]}',
  cons = '{"en":["Free tier very limited","Animated photos can look artificial","Less polished than HeyGen","Limited template variety"],"hi":["मुफ्त टियर बहुत सीमित","एनिमेटेड फोटो कृत्रिम लग सकती है","HeyGen से कम पॉलिश्ड","सीमित टेम्पलेट विविधता"],"hinglish":["Free tier bahut limited","Animated photos artificial lag sakti hai","HeyGen se kam polished","Limited template variety"]}',
  use_cases = '{"en":["Animating old family photos","Personal avatar for video content","Corporate presenter videos","Customer service avatars","Interactive AI agent with face","Historical figure recreations"],"hi":["पुरानी पारिवारिक तस्वीरें एनिमेट करना","वीडियो कंटेंट के लिए व्यक्तिगत अवतार","कॉर्पोरेट प्रेज़ेंटर वीडियो","कस्टमर सर्विस अवतार","चेहरे के साथ इंटरैक्टिव AI एजेंट","ऐतिहासिक व्यक्तित्व पुनर्निर्माण"],"hinglish":["Purani family photos animate karna","Video content ke liye personal avatar","Corporate presenter videos","Customer service avatars","Face ke saath interactive AI agent","Historical figures recreate karna"]}',
  alternatives = ARRAY['heygen','synthesia','invideo-ai'],
  hindi_summary = 'D-ID किसी भी फोटो को बोलता हुआ वीडियो बना सकता है। पर्सनल अवतार, कस्टमर सर्विस बॉट, और ऐतिहासिक फोटो को जीवंत बनाने के लिए।'
WHERE slug = 'd-id';

-- ── CapCut ────────────────────────────────────────────────────
UPDATE public.ai_tools SET
  features = '{"en":["Complete mobile and desktop video editor","Auto-captions with high accuracy","AI background removal from video","AI script to video","Trending templates and effects","Text-to-speech in Hindi and more","Free with no watermark on most features"],"hi":["पूर्ण मोबाइल और डेस्कटॉप वीडियो एडिटर","उच्च सटीकता के साथ ऑटो-कैप्शन","वीडियो से AI बैकग्राउंड रिमूवल","AI स्क्रिप्ट टू वीडियो","ट्रेंडिंग टेम्पलेट","हिंदी में टेक्स्ट-टू-स्पीच","अधिकांश फीचर्स पर बिना वॉटरमार्क मुफ्त"],"hinglish":["Complete mobile aur desktop video editor","High accuracy ke saath auto-captions","Video se AI background removal","AI script to video","Trending templates aur effects","Hindi mein text-to-speech","Zyaadatar features pe bina watermark free"]}',
  pros = '{"en":["Best free editor for Reels and Shorts","Excellent auto-captions for Indian languages","No watermark on free plan","Massive template library","Easy to learn with Hindi tutorials"],"hi":["Reels और Shorts के लिए सबसे अच्छा मुफ्त एडिटर","भारतीय भाषाओं के लिए उत्कृष्ट ऑटो-कैप्शन","मुफ्त प्लान पर कोई वॉटरमार्क नहीं","विशाल टेम्पलेट लाइब्रेरी","हिंदी ट्यूटोरियल से सीखना आसान"],"hinglish":["Reels aur Shorts ke liye best free editor","Indian languages ke liye excellent auto-captions","Free plan pe koi watermark nahi","Massive template library","Hindi tutorials se seekhna easy"]}',
  cons = '{"en":["Some advanced features require subscription","Owned by ByteDance — privacy concerns","Can be banned on some networks","Heavy app size on mobile"],"hi":["कुछ उन्नत फीचर्स के लिए सब्सक्रिप्शन","ByteDance की मालिकाना — गोपनीयता चिंताएं","कुछ नेटवर्क में बैन हो सकता है","मोबाइल पर भारी ऐप साइज़"],"hinglish":["Kuch advanced features ke liye subscription","ByteDance ownership — privacy concerns","Kuch networks mein ban ho sakta hai","Mobile pe heavy app size"]}',
  use_cases = '{"en":["Instagram Reels and YouTube Shorts","TikTok-style trending content","Auto-caption for accessibility","Product promotional videos","Dance and lip sync editing","Vlog and travel video editing"],"hi":["Instagram Reels और YouTube Shorts","TikTok-स्टाइल ट्रेंडिंग कंटेंट","पहुंच के लिए ऑटो-कैप्शन","प्रोडक्ट प्रमोशनल वीडियो","डांस और लिप सिंक एडिटिंग","व्लॉग और ट्रैवल वीडियो"],"hinglish":["Instagram Reels aur YouTube Shorts","TikTok-style trending content","Accessibility ke liye auto-captions","Product promotional videos","Dance aur lip sync editing","Vlog aur travel video"]}',
  alternatives = ARRAY['invideo-ai','opus-clip','vidyo-ai','descript'],
  hindi_summary = 'CapCut भारत में सबसे पॉपुलर फ्री वीडियो एडिटिंग ऐप है। Instagram Reels, YouTube Shorts — बिना वॉटरमार्क, बिना पैसे। हिंदी auto-caption भी शानदार।'
WHERE slug = 'capcut';

-- ── Fliki ────────────────────────────────────────────────────
UPDATE public.ai_tools SET
  features = '{"en":["Text-to-video with AI voiceover","900+ realistic AI voices including Hindi","Script to video with stock footage","Blog post to video conversion","Social media templates","Multiple aspect ratios","Brand kit customization"],"hi":["AI वॉइसओवर के साथ टेक्स्ट-टू-वीडियो","हिंदी सहित 900+ AI आवाज़ें","स्टॉक फुटेज के साथ स्क्रिप्ट टू वीडियो","ब्लॉग पोस्ट टू वीडियो","सोशल मीडिया टेम्पलेट","कई आस्पेक्ट रेशियो","ब्रांड किट कस्टमाइज़ेशन"],"hinglish":["AI voiceover ke saath text-to-video","Hindi sametan 900+ AI voices","Stock footage ke saath script to video","Blog post to video conversion","Social media templates","Multiple aspect ratios","Brand kit customization"]}',
  pros = '{"en":["Excellent Hindi voice options for Indian creators","Fast and simple text-to-video","Good for faceless YouTube channels","Affordable pricing","Large stock media library"],"hi":["भारतीय क्रिएटर के लिए उत्कृष्ट हिंदी वॉइस विकल्प","तेज़ और सरल टेक्स्ट-टू-वीडियो","Faceless YouTube चैनल के लिए अच्छा","किफायती कीमत","बड़ी स्टॉक मीडिया लाइब्रेरी"],"hinglish":["Indian creators ke liye excellent Hindi voice options","Fast aur simple text-to-video","Faceless YouTube channels ke liye achha","Affordable pricing","Large stock media library"]}',
  cons = '{"en":["AI voices sound robotic for long content","Stock footage not always relevant","Limited animation capabilities","Free tier tight limits"],"hi":["लंबे कंटेंट के लिए AI आवाज़ें रोबोटिक","स्टॉक फुटेज हमेशा प्रासंगिक नहीं","सीमित एनिमेशन क्षमताएं","मुफ्त टियर सख्त सीमाएं"],"hinglish":["Lambe content ke liye AI voices robotic","Stock footage hamesha relevant nahi","Limited animation capabilities","Free tier mein strict limits"]}',
  use_cases = '{"en":["Hindi faceless YouTube channel","News summary video in Hindi","Explainer videos for Indian businesses","Regional language social media","Converting text to video","Podcast to video with auto-visuals"],"hi":["Hindi faceless YouTube चैनल","हिंदी में न्यूज़ सारांश वीडियो","भारतीय व्यवसायों के लिए एक्सप्लेनर वीडियो","क्षेत्रीय भाषाओं में सोशल मीडिया","टेक्स्ट को वीडियो में बदलना","ऑटो-विज़ुअल के साथ पॉडकास्ट टू वीडियो"],"hinglish":["Hindi faceless YouTube channel","Hindi mein news summary videos","Indian businesses ke liye explainer videos","Regional languages mein social media","Text ko video mein convert karna","Auto-visuals ke saath podcast to video"]}',
  alternatives = ARRAY['invideo-ai','pictory-ai','synthesia','lumen5'],
  hindi_summary = 'Fliki हिंदी में faceless YouTube वीडियो बनाने के लिए बेहतरीन टूल है। 900+ AI आवाज़ें, हिंदी वॉइसओवर — बिना कैमरे के प्रोफेशनल वीडियो।'
WHERE slug = 'fliki';

-- ── Lumen5 ────────────────────────────────────────────────────
UPDATE public.ai_tools SET
  features = '{"en":["AI converts blog posts to videos","Large licensed media library","Drag-and-drop video editor","Brand kit with custom fonts and colors","Team collaboration","Multiple export formats","Social media format presets"],"hi":["AI ब्लॉग पोस्ट को वीडियो में बदलता है","लाइसेंस्ड मीडिया की बड़ी लाइब्रेरी","ड्रैग-एंड-ड्रॉप वीडियो एडिटर","कस्टम फ़ॉन्ट और रंग के साथ ब्रांड किट","टीम सहयोग","कई export formats","सोशल मीडिया फॉर्मेट प्रीसेट"],"hinglish":["AI blog posts ko videos mein convert karta hai","Licensed media ki badi library","Drag-and-drop video editor","Custom fonts aur colors ke saath brand kit","Team collaboration","Multiple export formats","Social media format presets"]}',
  pros = '{"en":["Great for content marketers and bloggers","Large licensed media library","Team collaboration features","Professional output quality","Good brand customization"],"hi":["कंटेंट मार्केटर और ब्लॉगर के लिए बेहतरीन","बड़ी लाइसेंस्ड मीडिया लाइब्रेरी","टीम सहयोग फीचर्स","प्रोफेशनल आउटपुट गुणवत्ता","अच्छा ब्रांड कस्टमाइज़ेशन"],"hinglish":["Content marketers aur bloggers ke liye great","Badi licensed media library","Team collaboration features","Professional output quality","Achha brand customization"]}',
  cons = '{"en":["Free plan very limited","More expensive than Fliki","AI accuracy not always on point","Less suitable for short-form social"],"hi":["मुफ्त प्लान बहुत सीमित","Fliki से अधिक महंगा","AI सटीकता हमेशा सटीक नहीं","शॉर्ट-फॉर्म सोशल के लिए कम उपयुक्त"],"hinglish":["Free plan bahut limited","Fliki se zyada mehanga","AI accuracy hamesha on point nahi","Short-form social ke liye kam suitable"]}',
  use_cases = '{"en":["Marketing team video from blog posts","News website video summaries","Corporate social media content","Brand awareness video campaigns","LinkedIn B2B video content","Internal company communications"],"hi":["ब्लॉग पोस्ट से मार्केटिंग टीम वीडियो","न्यूज़ वेबसाइट वीडियो सारांश","कॉर्पोरेट सोशल मीडिया कंटेंट","ब्रांड जागरूकता वीडियो","LinkedIn B2B वीडियो","आंतरिक कंपनी कम्युनिकेशन"],"hinglish":["Blog posts se marketing team video","News website video summaries","Corporate social media content","Brand awareness campaigns","LinkedIn B2B video","Internal company communications"]}',
  alternatives = ARRAY['pictory-ai','invideo-ai','fliki','synthesia'],
  hindi_summary = 'Lumen5 ब्लॉग और आर्टिकल से मार्केटिंग वीडियो बनाने के लिए पेशेवर AI टूल है। बड़ी कंपनियों और मार्केटिंग टीमों के लिए।'
WHERE slug = 'lumen5';

-- ── Beautiful.ai ──────────────────────────────────────────────
UPDATE public.ai_tools SET
  features = '{"en":["AI-powered presentation design","DesignerBot: generate full presentations from prompts","Smart slides auto-adjust to content","Real-time collaboration","100+ professionally designed templates","Presentation analytics","Export to PowerPoint and PDF"],"hi":["AI-पावर्ड प्रेज़ेंटेशन डिज़ाइन","DesignerBot: प्रॉम्प्ट से पूरी प्रेज़ेंटेशन","स्मार्ट स्लाइड ऑटो-एडजस्ट","रियल-टाइम सहयोग","100+ प्रोफेशनल टेम्पलेट","प्रेज़ेंटेशन analytics","PowerPoint और PDF में export"],"hinglish":["AI-powered presentation design","DesignerBot: prompts se full presentations","Smart slides auto-adjust","Real-time collaboration","100+ professional templates","Presentation analytics","PowerPoint aur PDF mein export"]}',
  pros = '{"en":["Slides always look professional","DesignerBot generates full decks in minutes","Smart layout prevents ugly slides","Good for team collaboration","Better design than traditional PowerPoint"],"hi":["स्लाइड हमेशा प्रोफेशनल दिखती हैं","DesignerBot मिनटों में पूरे डेक बनाता है","स्मार्ट लेआउट बदसूरत स्लाइड रोकता है","टीम सहयोग के लिए अच्छा","पारंपरिक PowerPoint से बेहतर डिज़ाइन"],"hinglish":["Slides hamesha professional dikhti hain","DesignerBot minutes mein full decks banata hai","Smart layout ugly slides prevent karta hai","Team collaboration ke liye achha","Traditional PowerPoint se better design"]}',
  cons = '{"en":["Subscription required — no free tier","Less control than manual tools","PowerPoint import can lose formatting","Limited offline access"],"hi":["सब्सक्रिप्शन जरूरी — कोई मुफ्त टियर नहीं","मैन्युअल टूल से कम नियंत्रण","PowerPoint import फॉर्मेटिंग खो सकता है","सीमित ऑफलाइन एक्सेस"],"hinglish":["Subscription zaroori — koi free tier nahi","Manual tools se kam control","PowerPoint import formatting lose kar sakta hai","Limited offline access"]}',
  use_cases = '{"en":["Investor pitch decks","Sales proposal presentations","Quarterly business reviews","Academic and conference presentations","Company onboarding materials","Marketing and product launch decks"],"hi":["निवेशक पिच डेक","सेल्स प्रपोज़ल प्रेज़ेंटेशन","तिमाही बिज़नेस समीक्षाएं","अकादमिक और कॉन्फ्रेंस प्रेज़ेंटेशन","कंपनी ऑनबोर्डिंग","मार्केटिंग और प्रोडक्ट लॉन्च डेक"],"hinglish":["Investor pitch decks","Sales proposal presentations","Quarterly business reviews","Academic aur conference presentations","Company onboarding","Marketing aur product launch decks"]}',
  alternatives = ARRAY['gamma-app','tome','napkin-ai','canva-ai-magic-studio'],
  hindi_summary = 'Beautiful.ai AI से प्रोफेशनल प्रेज़ेंटेशन बनाता है। DesignerBot से मिनटों में पूरी प्रेज़ेंटेशन — निवेशकों और क्लाइंट्स के लिए पिच डेक बनाने का आसान तरीका।'
WHERE slug = 'beautiful-ai';
"""

with open(path, 'a', encoding='utf-8') as f:
    f.write(sql)

print("Video tools batch appended successfully.")
